### ISSUE TITLE
Smelt [Issue]

### ISSUE THREAD

**Issue by jakubcze1** [GC-spigot/battle-pass#10]
**Describe the bug**
 If I want to complete the task, bake 128 gold ingots, it seems to me that it is not working properly, or I have something badly set up, but what. If I want it to add to me all the ingots, then somehow it doesn't work. Click to select ingots from the SHIFT furnace and add to me instead of, for example, 30 ingots.

**Screenshots / Video**
 https://youtu.be/gNrya2peff0

**Server Information (please complete the following information):**
- Server Version: 1.16.4
- Plugin Version: 3.13

**Comment by GC-spigot** [comment]
Fixed!
