### ISSUE TITLE
[Issue] wolf training bug

### ISSUE THREAD

**Issue by Hitman477** [GC-spigot/battle-pass#101]
**Describe the bug** 
Found a mistake, if there is a quest to tame wolves and reload the plugin, then if the player tamed the wolves and reload, then the information will be reset and all must be over again 
**To Reproduce** 
Train the wolf and reload the plugin 
**Server Information (please complete the following information):** 
- Server Version: purpurclip-1.16.5-1171.jar 
- Plugin Version: BattlePass 3.15.3

**Comment by GC-spigot** [comment]
Cannot recreate
