### ISSUE TITLE
The problem is caused by overriding the plugins.

### ISSUE THREAD

**Issue by Bestlnwza007** [GC-spigot/battle-pass#103]
![image](https://user-images.githubusercontent.com/94585571/142345671-d629c2a3-c2b5-4f27-9a6f-7288438d3975.png)
how to fix
[latest.log](https://github.com/GC-spigot/battle-pass/files/7559641/latest.log)

**Comment by GC-spigot** [comment]
Change your GUI name or remove plugins which are incompatible (e.g. other battlepass plugins)
