### ISSUE TITLE
block place & block break

### ISSUE THREAD

**Issue by yellow-pillow** [GC-spigot/battle-pass#104]
and also the tasks related to breaking elites do not work
[12:41]
+ I had a big problem with the "put a block" tasks 

I made a task to build a lighthouse and people end up doing one block put it, break it, put it, break it... and so on to infinity...

it is possible to link 2 checks to put and break the block that if a person put and broke the block within half an hour for example putting the block is not counted

the same can be done with breaking blocks, what do you think?

(I would be shocked if I got an answer, since my previous bug notifications were simply ignored and then deleted)

**Comment by GC-spigot** [comment]
Issues are closed when they are resolved or not following format required for issues, I cannot comprehend how it's possible not to follow required format and feel entitled enough to get help.

**Comment by yellow-pillow** [comment]
** Error description**
if you create a quest on the block you can just break and install the same block and the quest will count :(
You just need to put, break, put, break, etc...

**Replay**.
if you create a quest on the block, you can just break and install the same block and the quest will count :(

**Screenshots/video**
https://drive.google.com/file/d/1DbkT4DDRM0AfKYYhNRDV_ah3Mehw76Il/view?usp=sharing

**Server info (please fill in the following information):**.
- Server version: [ssspigot 1.16.5].
- Plugin version: [latest 3.5.18].

**How to fix it.
you can link 2 checks, block_break and block_place, and if a person puts and breaks a block within half an hour, for example, the block is not counted

the same can be done with block_break, what do you think?

**Comment by GC-spigot** [comment]
It does work like that as described, placing block -> saves location, https://gyazo.com/709954daae5b95754a2a889805c478eb
