### ISSUE TITLE
McMMO Error

### ISSUE THREAD

**Issue by RafaelWirth** [GC-spigot/battle-pass#108]
**Describe the bug**
When I break a crop, this error results

**To Reproduce**
Break crops using McMMO on the server

**Screenshots / Video**
https://www.toptal.com/developers/hastebin/apavekecum.properties

**Server Information (please complete the following information):**
- Server Version: AtomSpigot 1.8.8
- Plugin Version: [e.g. 3.5.16]

**Comment by GC-spigot** [comment]
What McMMO version are you using? Yours seems to not be supported
