### ISSUE TITLE
[Issue] EXP values smaller than 1 for jobs_gain_exp quests don't progress the quest

### ISSUE THREAD

**Issue by Dakotaa** [GC-spigot/battle-pass#109]
**Describe the bug**
When using a jobs_gain_exp quest type, jobs which reward EXP values smaller than 1 do not progress the player's quest.

**To Reproduce**
Create a jobs_gain_exp quest for a job that has EXP rewards less than one. Do the job action, no progress towards the quest will be made.

**Server Information (please complete the following information):**
- Server Version: Purpur 1.16.5
- Plugin Version: 3.5.17

**Comment by GC-spigot** [comment]
Fixed
