### ISSUE TITLE
elytra break

### ISSUE THREAD

**Issue by yellow-pillow** [GC-spigot/battle-pass#110]
**Error description**
The elytra breaking task is broken and doesn't work

**Replay**.
try breaking elytra

**Screenshots/video**
https://drive.google.com/file/d/19TKEyoIfYlx2TkBBcTnhhKo_jVV382HP/view?usp=sharing

**Server info (please fill in the following information):**.
- Server version: [ssspigot 1.16.5].
- Plugin version: [latest 3.5.18].

**addition**.
watch the end of the video! despite the fact that the hoe is shown on the task itself about breaking elytra and I showed you the yml file

**Comment by GC-spigot** [comment]
item-break is for items in hand, not armor
