### ISSUE TITLE
[Request] World Whitelist/Blacklist

### ISSUE THREAD

**Issue by Superalex0102** [GC-spigot/battle-pass#111]
**Describe the Request**

Add an option so each quest can have a whitelist or blacklist of worlds where you can complete them.

**Comment by yellow-pillow** [comment]
What's the point? Can you give me an example of where this might be useful?

**Comment by Superalex0102** [comment]
> What's the point? Can you give me an example of where this might be useful?

For example you want to create a quest where you only want the players to kill mobs in the mobarena, not in the normal survival world.
