### ISSUE TITLE
[Issue] execute-command not working

### ISSUE THREAD

**Issue by kdeano** [GC-spigot/battle-pass#120]
**Describe the bug**
If a command is handled by another plugin (i.e. DeluxeMenus) then it is not registered as executed by BattlePass.

**To Reproduce**
Setup an execute-command type challenge with a command that is handled by another plugin and execute it in chat.

**Server Information (please complete the following information):**
- Server Version: [e.g. PaperSpigot-792 1.16.5]
- Plugin Version: [e.g. 3.6.2]

**Comment by GC-spigot** [comment]
DeluxeMenus "commands" aren't commands but rather just chat messages. You'll need to check for chat messages rather unfortunately.
