### ISSUE TITLE
[Issue] Bug in the CrazyCrates API

### ISSUE THREAD

**Issue by thiagogebrimm** [GC-spigot/battle-pass#128]
`[00:00:27 ERROR]: [BattlePass] Plugin BattlePass v3.6.6 has failed to register events for class io.github.battlepass.quests.quests.external.CrazyCratesQuests because me/badbones69/crazycrates/api/events/PlayerPrizeEvent does not exist.`

Recently crazycrates released a new version for 1.18 dev and the compatibility stopped working

**Comment by thiagogebrimm** [comment]
https://jenkins.badbones69.com/job/Crazy-Crates-1.18/

**Comment by GC-spigot** [comment]
Fixed
