### ISSUE TITLE
Could not pass event McMMOPlayerXpGainEvent to BattlePass

### ISSUE THREAD

**Issue by FinnChildress** [GC-spigot/battle-pass#129]
**Describe the bug**
Since I am using an unsupported version of mcMMO, the console gets spammed with errors whenever a player gains mcMMO exp.
I understand that the integration will not work. However, it is very annoying to have the console spam. 
- Instead of spamming the console, please add a check for the mcMMO version before throwing the error and send a warning message at plugin enable if the mcMMO version is not supported.

**To Reproduce**
1. Install mcMMO classic 1.5.04
2. Gain mcMMO exp

**Screenshots / Video**
Console error: https://www.toptal.com/developers/hastebin/beyamunara.apache

**Server Information (please complete the following information):**
- Server Version: PaperSpigot 1.8.8 
- Plugin Version: 3.6.0

**Comment by GC-spigot** [comment]
Resolved
