### ISSUE TITLE
/bpa set points adds to the players current balance [Issue]

### ISSUE THREAD

**Issue by rainbows123** [GC-spigot/battle-pass#13]
**Describe the bug**
Using /bpa set points <player> will add the points provided to the players balance than actually setting their balance to the amount.

**To Reproduce**
Use /bpa set points <player> and you will see it adds the points to their balance.

**Screenshots / Video**
https://prnt.sc/10pq81j (for some reason it doesn't even add the correct amount provided)

**Server Information (please complete the following information):**
- Server Version: 1.8.8
- Plugin Version: 3.13

**Comment by GC-spigot** [comment]
Fixed
