### ISSUE TITLE
bossbar

### ISSUE THREAD

**Issue by yellow-pillow** [GC-spigot/battle-pass#133]
**Describe the bug**
idk what is it check screens (bossbar message)

**To Reproduce**
check screens

**Screenshots / Video**
![image](https://user-images.githubusercontent.com/90108493/152078009-1eb05f6c-1dde-414e-a824-8a312e8ff297.png)
![image](https://user-images.githubusercontent.com/90108493/152078099-91314ece-b575-4aa6-864e-60ae806f20d0.png)

**Server Information (please complete the following information):**
- Server Version: [e.g. Ssspigot 1/16/5]
- Plugin Version: [e.g. 3.6.9]

**Comment by GC-spigot** [comment]
It doesn't support multiple lines - have everything in one line

**Comment by yellow-pillow** [comment]
This is understandable, but the problem is that the chat supports line break, I have made such an alert for the chat, 

then you can add separate alerts for both chat and this place
