### ISSUE TITLE
Tiers are messed up

### ISSUE THREAD

**Issue by Restland** [GC-spigot/battle-pass#134]
![image](https://user-images.githubusercontent.com/84740054/152157270-015b3d3d-19b2-45be-9035-7756c7510525.png)
![image](https://user-images.githubusercontent.com/84740054/152157297-108e9e33-83ce-4df1-a569-a0a502cb92c3.png)
![image](https://user-images.githubusercontent.com/84740054/152157376-161992dc-5896-46c9-8b67-cdcb0e80f59f.png)
![image](https://user-images.githubusercontent.com/84740054/152157391-30a3fa72-542b-4592-90fa-6694ca7bcfed.png)
There are tiers that messed up , for example as you see in the screenshots bellow the tier 6 is on the first page and then tier 6 re appears on the second list aswell which makes it unclaimable, and on the premium pass aswell, last tier is 76 and then another one appears tier 70. I have looked in the config files but I have failed to find and issue.

Paper version git-Paper-152 (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT) (Git: 78999b5)
Plugin Version 3.6.9

**Comment by GC-spigot** [comment]
Fixed
