### ISSUE TITLE
[Issue] The smelt type does not work in a smoker

### ISSUE THREAD

**Issue by Woody-Man** [GC-spigot/battle-pass#137]
**Describe the bug**
The plugin does not count if you fry food in a smoker.
In an ordinary furnace , it counts.
  
`14: # Quest id
    type: smelt
    variable: cooked_beef:0
    name: '&6➲ &eНеделя 1 - ≪ №14 ≫'
    required-progress: 300
    points: 4
    item:
      material: cooked_beef:0
      name: '&e➲ ≪ №14 ≫'
      lore:
        - ''
        - '&fЗадание:'
        - '&7Пожарить 300 стейков'
        - ''
        - '&fНаграда:'
        - '&e✩ 4 поинта'
        - ''
        - '&7➥ &fВаш прогресс: &e%total_progress%&7/&6%required_progress%'`

**Server Information (please complete the following information):**
- Server Version: Airplane-1.17.1
- Plugin Version: 3.6.10

**Comment by GC-spigot** [comment]
Fixed
