### ISSUE TITLE
[Issue] Disabled Hooks Feature not working for mcMMO Classic

### ISSUE THREAD

**Issue by MattTek** [GC-spigot/battle-pass#139]
I was attemping to disable the mcMMO hook through battlepass' hook disabler because I was receiving this error (pastebin link) whenever I attacked a mob (either a normal Minecraft mob or Mythic Mob). However, even after adding it to the disabled-plugin-hooks section, the hook would remain enabled for mcMMO classic, causing the same error to flood my console. To fix this issue, either mcMMO classic support would need to be added (#118) or the disabled-plugin-hooks feature would need to properly disable the hook between mcMMO classic and battlepass. I hope to see this fixed soon. Thank you for all your hard work!

Error when attacking mob: https://pastebin.com/fx5KEEPe
![image](https://user-images.githubusercontent.com/52072006/155609071-db269087-c6aa-463c-beca-94b973afadd4.png)

**Comment by GC-spigot** [comment]
Update
