### ISSUE TITLE
Balance Check

### ISSUE THREAD

**Issue by EneRGO22** [GC-spigot/battle-pass#14]
Hi, can you add validation for actions?
I want to make such a counter in the menu when you click on an item, then money is withdrawn and a paid battle pass is issued.
I want to implement through the Dkcoins plugin
It could be done with teams, but if the player does not have the required amount on the balance, then he will write to him that there is not enough balance and will still issue a permit, but the plugin needs to check if the player has enough money and, if so, will issue the permission, and if not , then he will write a message that there is not enough money

**Comment by GC-spigot** [comment]
This is a very specific request and unfortunately I can't add this as it won't benefit a lot of plugin users.
