### ISSUE TITLE
[Issue] Legacy plugin?

### ISSUE THREAD

**Issue by analnyroztahovac** [GC-spigot/battle-pass#142]
Hi, Im running 1.17.1 paper server **( PAPER-b409 ; 1.17.1 )**
with latest version of BattlePass **( v3.6.18 )**
and getting this error at **randomly** given times:  https://paste.denizenscript.com/View/94244
it freezes my entire server for nearly 2 seconds
I dont think you can somehow reproduce those errors since they happen randomly.
Feel free to contact me for more informations if needed.

**Comment by GC-spigot** [comment]
Are you using items somewhere with IDs as numbers? That's what the problem may be. Either way, error won't show anymore starting next update

**Comment by analnyroztahovac** [comment]
no, just their name IDs , ex iron_sword... etc
