### ISSUE TITLE
[Request] Pass

### ISSUE THREAD

**Issue by dinobossytnew** [GC-spigot/battle-pass#148]
**Describe the Request**
To be able to create more passes without limit because only free and premium ruin the essence of it.

**Comment by dinobossytnew** [comment]
https://mcpaste.com/4236da5566c9d16d51f25bad2d6c6493 
also if it is possible that only the tiers can be uploaded only 1 per day.

**Comment by OpticFusion1** [comment]
That link is invalid, please use something like pastebin.com
