### ISSUE TITLE
[Issue] save data!!!!1

### ISSUE THREAD

**Issue by dinobossytnew** [GC-spigot/battle-pass#149]
**Describe the bug**
https://pastebin.com/e3rf3fGZ
Basically I modified things in the battlepass premium.yml so that it was like this and that's what happens to me, I tried to put it as before and it still happens, help me more and more, the save system is breaking more and more!

**To Reproduce**
I don't know, so it doesn't make sense.

**Screenshots / Video**
null

**Server Information (please complete the following information):**
- Server Version: paper 1.12.2
- Plugin Version: 3.7.3

**Comment by GC-spigot** [comment]
Plugin hasn't had any changes with saving for 2 years, literally 2 years. No one has had issues ever. Show your premium.yml file, it's 100% a configuration issue.

**Comment by GC-spigot** [comment]
What do you mean - is the issue resolved or not?

**Comment by dinobossytnew** [comment]
not... resolved...

**Comment by dinobossytnew** [comment]
the same thing keeps happening to me in 1.12.2

**Comment by GC-spigot** [comment]
Zip your battlepass folder and send it over please

**Comment by dinobossytnew** [comment]
ok
