### ISSUE TITLE
[Issue] Self-placed blocks

### ISSUE THREAD

**Issue by Dibsymodzz** [GC-spigot/battle-pass#15]
The placed blocks do not count when you place them, so only things that are generated by the world

**Comment by GC-spigot** [comment]
Can you provide an example quest? Plugin Version? Server version? There's an issues template when you create an issue for a reason.

**Comment by Dibsymodzz** [comment]
Latest example 1.16.5 first install the coal miner quest first week

**Comment by GC-spigot** [comment]
I still don't understand what you want, if this is a issue report or a request. I assume you are asking to ignore player placed blocks with block-break quest, added that.
