### ISSUE TITLE
Warns in Console

### ISSUE THREAD

**Issue by Restland** [GC-spigot/battle-pass#150]
**Describe the bug**
I get a lot of warnings in console that drops the tps 
https://pastebin.com/z8yS39et

**To Reproduce**
It happens randomly

**Screenshots / Video**
![image](https://user-images.githubusercontent.com/84740054/161722741-afd45832-5ff3-4d4f-a61d-6e1dc53d2f9c.png)

**Server Information (please complete the following information):**
- Server Version:  Paper version git-Paper-234 1.18.2
- Plugin Version: 3.7.3

**Comment by GC-spigot** [comment]
Check your `quest-slots` configuration inside `plugins\BattlePass\menus\daily-quests.yml` file - configuration issue
