### ISSUE TITLE
citizens_kill doesn't work

### ISSUE THREAD

**Issue by drevyaa** [GC-spigot/battle-pass#151]
I prepared citizens_kill quest but when i kill NPC, quest doesn't progress.
I try citizens_damage. It's work but citizens_kill doesn't work.

https://www.hizliresim.com/b2xlndh

- Server Version: Purpur-1171 1.16.5
- BattlePass Version: 3.6.17
- Citizens Version: 2.0.27-SNAPSHOT (build 2217)
- Sentinel Version: 2.4.0-SNAPSHOT (build 444)

**Comment by GC-spigot** [comment]
Resolved next update
