### ISSUE TITLE
[Issue]  battlepass plugin can't start

### ISSUE THREAD

**Issue by xF3d33** [GC-spigot/battle-pass#153]
**The bug**
Even if i'm using paper, the plugin can't start

**Errors:**
this: https://paste.olympusmc.it/awebajayoz is the error with 3.7.3 version
and this: https://paste.olympusmc.it/duwoweqisi is the error with 3.7.4 version 

`java.lang.ClassCastException: class java.util.ArrayList cannot be cast to class java.lang.String (java.util.ArrayList and java.lang.String are in module java.base of loader 'bootstrap')`

`java.lang.NullPointerException: Cannot invoke "io.github.battlepass.quests.workers.reset.DailyQuestReset.getCurrentQuests()" because "<parameter1>" is null`

my daily quests: 
[ticket link](https://discord.com/channels/376425582139015168/962459156160331787/962679414758465627)
(check battlepass-0477 ticket on discord)

**Server Information:**
- Server Version: Paper 1.18.2 v283
- Plugin Version: 3.7.3 and 3.7.4

**Comment by GC-spigot** [comment]
This is a configuration issue with quests, looking into it now for you
