### ISSUE TITLE
[Request] Formatted %points% placeholder and please add %points_needed% placeholder

### ISSUE THREAD

**Issue by Golicraft** [GC-spigot/battle-pass#154]
**Describe the Request**
Hi, I would very much like on my server to have Battle Pass more as a level system with a high amount of points reqiured for each level. 

I would like to display the "Points/Exp" you already have in a format. For example everything above 1000 will be formatted with a K. 

Examples:
1,2k (1200) 5k (5000) 7,3k (7300), 21k (21000) and so on. Only needed for format with "K (thousand)". 

Pictures to show why I need this. 

![image](https://user-images.githubusercontent.com/11066952/162848346-e61b87de-776d-44b7-9eac-b2fba67dd240.png)
This shows how the format is at the moment.

The 10281/10k, the 10k will be the %points_needed% placeholder. Just like here
![image](https://user-images.githubusercontent.com/11066952/162848438-fde3b310-d75e-4bda-bcf2-e5478f774b58.png)

Only with the "K" format instead. 

So new placeholders: %battlepass_points_formatted% and %battlepass_points_needed_formatted%

**Comment by Golicraft** [comment]
More examples:

The highest Level I'll have is 370,000 Points

So on the scoreboard if you have 125,340 Points 

It will say 125k / 370k

**Comment by Golicraft** [comment]
Hi @GC-spigot. Can I know your thoughs on this?

**Comment by Faln** [comment]
Added. Please update to latest version.

**Comment by Golicraft** [comment]
> Added. Please update to latest version.

Thank you. What is the placeholders? 
![image](https://user-images.githubusercontent.com/11066952/181211798-aea97494-333b-48d8-936b-85ab68b27a62.png)

**Comment by Golicraft** [comment]
@Faln what is the last placeholder? It doesn't work. 

![image](https://user-images.githubusercontent.com/11066952/194960947-13b5f9d4-c67a-40a1-84d6-9b401ec95fba.png)

My config: 
        - '&8▎ &7Exp: &f%battlepass_points_formatted%&8/&f%battlepass_points_required_formatted%'
      
I also tried: 
        - '&8▎ &7Exp: &f%battlepass_points_formatted%&8/&f%battlepass_points_needed_formatted%'
