### ISSUE TITLE
New MythicMobs-5.0.2 doesn't work with BP

### ISSUE THREAD

**Issue by SoniXlash** [GC-spigot/battle-pass#156]
Quests 'mythicmobs_kill_mob' doesn't work with latest MM
ERROR appears in console on the startup

`[Server thread/ERROR]: [BattlePass] Plugin BattlePass v3.7.5 has failed to register events for class io.github.battlepass.quests.quests.external.MythicMobsQuests because io/lumine/xikage/mythicmobs/api/bukkit/events/MythicMobDeathEvent does not exist.
`

- Server Version: paper 1.18.2-263
- Plugin Version: 3.7.5

**Comment by HexedHero** [comment]
Same issue, having to wait for a fix before I can publish my season live.

**Comment by Faln** [comment]
Issue have been fixed, please update to lastest version.
