### ISSUE TITLE
[Request] Different icon when completing quests for the week

### ISSUE THREAD

**Issue by duarbala** [GC-spigot/battle-pass#160]
In the Battlepass plugin, in section **menus / quest-overview.yml** 

Add an option to display a different icon / lore when the player completes all the quests for that week and it would look like this:

¹week-item: icon for unlocked week
²locked-week-item: icon for locked week
³week-completed: icon for when the player completes all missions for that week

if you also add a progress system to see how many missions you complete each week it would be perfect: %weekprogress% / %weekquests%

**Comment by thiagogebrimm** [comment]
Would be great!

**Comment by thiagogebrimm** [comment]
@GC-spigot marked as complete but didn't see any updates about :(
