### ISSUE TITLE
[Issue] Instant Crafting BattlePass

### ISSUE THREAD

**Issue by ItzFabb-uwu** [GC-spigot/battle-pass#165]
**Describe the bug**
I found a bug when you press the shift key and right-click the mouse after instant crafting, the quest progression is bugging i crafted a stick with 128 oak planks and i had 256 sticks instead the battlepass count the stick crafted to 64 stick 

**To Reproduce**
Make a craft quest type on daily and put the required-progress to 1024 and then try to craft the stick

**Screenshots / Video**
https://youtu.be/KrSTQD5fuxQ

**Server Information (please complete the following information):**
- Server Version: This server is running Paper version git-Paper-"d3c1023" (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT) (Git: d3c1023)
- Plugin Version: [Battlepass 3.8.0]

**Comment by Faln** [comment]
Fixed. Please update to latest.
