### ISSUE TITLE
[Issue] Item menu dup

### ISSUE THREAD

**Issue by prochedary** [GC-spigot/battle-pass#166]
**Describe the bug**
There is bug, that you can get items from BP menu at MC version 1.16.5 a lower. At 1.17 and 1.18 it works fine.

**Screenshots / Video**
https://ctrlv.tv/uGfl

**Server Information (please complete the following information):**
- Server Version: Purpur-1612
- Plugin Version: 3.8.0

**Comment by GC-spigot** [comment]
Try using a different server platform from purpur, it's terrible.

**Comment by prochedary** [comment]
I tried last paper but it still works.

**Comment by GC-spigot** [comment]
Can you send the video or upload it on youtube? I wasn't able to view it
