### ISSUE TITLE
[Issue] Battlepass mysql saving issues at 1.17.1

### ISSUE THREAD

**Issue by PasteDev** [GC-spigot/battle-pass#167]
**Describe the bug**
When the server is restarted or shut down the plugin does not save the data

**To Reproduce**
Prolly just restarting the server 1.17.1 missions are not being saved.

**Screenshots / Video**
[Logs](https://bin.bloom.host/gaxiponego)

**Server Information (please complete the following information):**
- Server Version: "This server is running Purpur version git-Purpur-1428 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 9beb23b on ver/1.17.1)"
- Plugin Version: "BattlePass version 3.8.0"

**Comment by SirJben** [comment]
Update Battlepass. 
![image](https://user-images.githubusercontent.com/63577950/168480871-fedc5912-f979-4116-b97b-51da32b812a5.png)
