### ISSUE TITLE
[Issue] mysql reset data player someone

### ISSUE THREAD

**Issue by uploadx10** [GC-spigot/battle-pass#168]
**Describe the bug**
When restarting the server will have some players' data reset to 0

**To Reproduce**
When restart server

**Screenshots / Video**

**Server Information (please complete the following information):**
- Server Version: Paper-216 1.18.1
- Plugin Version: 3.8.0

**Comment by uploadx10** [comment]
+BattlePass Type: Craft Bug!!
https://youtu.be/JNl5F59oInA

+BattlePass Type: Smelt Bug!!
https://youtu.be/2SFjWvvQWbE

**Comment by SirJben** [comment]
Update Battlepass.
![image](https://user-images.githubusercontent.com/63577950/168480887-bdfb6a4f-c3d0-40c6-957b-75b1a34470d8.png)
