### ISSUE TITLE
[Issue]Error

### ISSUE THREAD

**Issue by xBeratE** [GC-spigot/battle-pass#169]
**Describe the bug**
error in console

**To Reproduce**
i am using superiorskyblock and battlepass on my server and i have this error

**Server Information (please complete the following information):**
- Server Version: [e.g. Airplane 1.17.1]
- Plugin Version: [e.g. 3.8.0]

Error :    https://mclo.gs/qyAQnSP

**Comment by GC-spigot** [comment]
Fixed
