### ISSUE TITLE
[Issue] MySql 

### ISSUE THREAD

**Issue by lerndmina** [GC-spigot/battle-pass#171]
**Describe the bug**
Plugin unable to connect to Local MySQL database

**To Reproduce**
Install the plugin
Boot the server
Edit config to place in MySQL details
Restart the server
Observe error, plugin fails to load

**Screenshots / Video**
[Current MYSQL Version](https://i.imgur.com/NKGyh0s.png)
[Error log in question](https://pastebin.com/QDNi0B9c)

**Server Information (please complete the following information):**
- Server Version: [Purpur 1612 (MC: 1.18.2)](https://i.thalwyrn.com/JMQpk.png)
- Plugin Version: 3.8.1 (Latest at time of posting)
- Server Proxy Version: [Waterfall](https://i.thalwyrn.com/Fqpn6.png)

**Comment by GC-spigot** [comment]
Fixed
