### ISSUE TITLE
java.lang.NoClassDefFoundError: io/github/battlepass/hikari/HikariConfig

### ISSUE THREAD

**Issue by lengnuandk** [GC-spigot/battle-pass#172]
**Describe the bug**
When i connect to mysql database and i make sure my configuration is not wrong it shows this

**Screenshots / Video**
If applicable, add screenshots or videos to help explain/ show your problem.
![4T}T328CAVNTX5@MO%QD38O](https://user-images.githubusercontent.com/105548254/168428824-198b3722-4f4a-44ce-80b2-a64d3b3279fa.png)

**Server Information (please complete the following information):**
- Server Version: [PaperSpigot-1.12.2] [Catservert1.12.2]
- Plugin Version: [3.8.1]

**Comment by GC-spigot** [comment]
Fixed
