### ISSUE TITLE
[BUG] Pass type change if saving on mysql 

### ISSUE THREAD

**Issue by antasetyawan** [GC-spigot/battle-pass#178]
**Describe the bug**
Pass type ( Free type ) Change to premium every time ( its randomly ) .

**To Reproduce**
- Check Luckperms, and player not have permission for premium type
- Check database mysql, and player bp type is free
- if i increase time for saving in mysql, is work ( i mean, saving on mysql become data changing ) 

**Server Information (please complete the following information):**
- paper 1.18.2
- Plugin Version: latest

**Comment by GC-spigot** [comment]
Please post your config.yml file, thanks.
