### ISSUE TITLE
[Issue] Block-break quest can be bypassed using Pistons

### ISSUE THREAD

**Issue by goreziller** [GC-spigot/battle-pass#181]
**Describe the bug**
Block break quest where you mine ores can be easily bypassed by moving ores with Pistons

**To Reproduce**
Place the necessary ores in front of a piston and move them now counts the ores as newly generated ores and gives you progress for the quest

**Server Information (please complete the following information):**
- Server Version: forge-1.16.5-36.2.26
- Plugin Version: 3.8.8

**Comment by GC-spigot** [comment]
Resolved

**Comment by goreziller** [comment]
Can still bypassed the Quests in v.3.9.0 with Pistons
