### ISSUE TITLE
[Issue] MoneyHunters quests not working.

### ISSUE THREAD

**Issue by Ainashi** [GC-spigot/battle-pass#182]
After upgrading to the newer version of MoneyHunters, the tasks related to this plugin stopped working.

Startup error:
`[Server thread/ERROR]: [BattlePass] Plugin BattlePass v3.8.7 has failed to register events for class io.github.battlepass.quests.quests.external.MoneyHuntersQuests because su/nightexpress/moneyhunters/api/events/PlayerJobLevelUpEvent does not exist.`

BattlePass v. 3.8.7
MoneyHunters v. 7.0.3

**Comment by Awpmeister2170** [comment]
Update to the Latest Version of Battlepass, This issue should be Resolved
