### ISSUE TITLE
[Issue] BattlePass crashes server (Probably due to an endless amount of created async schedulers)

### ISSUE THREAD

**Issue by goreziller** [GC-spigot/battle-pass#185]
**Describe the bug**
Server crash after probably after creating a amount of endless async schedulers

**Screenshots / Video**
[crash-2022-06-12_00.00.21-server.txt](https://github.com/GC-spigot/battle-pass/files/8884829/crash-2022-06-12_00.00.21-server.txt)

**Server Information (please complete the following information):**
- Server Version: arclight-1.16.5-1.0.24-SNAPSHOT-156b78b4
- Minecraft Version: 1.16.5
- Plugin Version: 3.8.9

**Comment by GC-spigot** [comment]
All errors are coming from votifier

**Comment by johnfriedrich** [comment]
@GC-spigot Hi, thats not correct. If you search for "BattlePass" you will see ~5700 occurences in the thread section. It definitely BattlePass

**Comment by johnfriedrich** [comment]
We got another 10 crashes because of that:
Here is one:
https://pastebin.com/HEeJpGCK
"BattlePass"
Could we get a debug version which prints to consoel each time a thread is started together with a method name that started that thread? This would easily allow us to find the culprit
