### ISSUE TITLE
[Issue] craft Quests can be easily completed with shift

### ISSUE THREAD

**Issue by goreziller** [GC-spigot/battle-pass#186]
**Describe the bug**
When you take your items from Crafting with Shift the progress of the Quest will be done

**Server Information (please complete the following information):**
- Server Version: arclight-1.16.5-1.0.24-SNAPSHOT-156b78b4
- Plugin Version: 3.8.9

**Comment by goreziller** [comment]
So is this normal then 32 melons are needed that shift crafting with one melon counts all 32 for the quest?

**Comment by SirvydasS** [comment]
![image](https://user-images.githubusercontent.com/8950371/175095764-edf8cee7-adc8-4a0d-9f1b-6dfdb4e7ebf4.png)
If you take this with SHIFT it will craft only 4, but in BP mission it counts as 64.

**Comment by johnfriedrich** [comment]
> ![image](https://user-images.githubusercontent.com/8950371/175095764-edf8cee7-adc8-4a0d-9f1b-6dfdb4e7ebf4.png) If you take this with SHIFT it will craft only 4, but in BP mission it counts as 64.

Its fixed with the next release
