### ISSUE TITLE
Quest with CMI commands.

### ISSUE THREAD

**Issue by SirJben** [GC-spigot/battle-pass#192]
This issue has been raised by harold#1385 | 253962059929092097
Discord [1st Transcript](https://tickettool.xyz/direct?url=https://cdn.discordapp.com/attachments/841740907467636756/988823399100993606/transcript-battlepass-0578.html) and [2nd Transcript](https://tickettool.xyz/direct?url=https://cdn.discordapp.com/attachments/841740907467636756/992389961460486205/transcript-cmi-spawn-bp.html) 

Quest with execute-command type is not working with CMI plugin. 

Example quest with CMI plugins from harold#1385
```
type: execute-command
variable: spawn
```

Take note: `/spawn` with CMI plugin also registered as `/cmi spawn`

**Comment by GC-spigot** [comment]
Looking into this, would recommend trying to use `cmi spawn` instead as `spawn` is just an alias for it

**Comment by SirJben** [comment]
> Looking into this, would recommend trying to use `cmi spawn` instead as `spawn` is just an alias for it

I suggested this to him but he also replies that it also does not work.
