### ISSUE TITLE
[Issue] After restart BattlePass dailymission changes

### ISSUE THREAD

**Issue by SirvydasS** [GC-spigot/battle-pass#198]
**Describe the bug**
After server restart BattlePass dailymission changes all the time.
My server auto restarts at 04:00 and dailymission refresh at 08:00, so dailymissions change few times.

**To Reproduce**
Restart server and watch how will change dailymission after that.

**Server Information (please complete the following information):**
- Server Version: This server is running Paper version git-Paper-81 (MC: 1.19) (Implementing API version 1.19-R0.1-SNAPSHOT) (Git: 86f87ba)
- Plugin Version: 3.9.9

**Comment by kforbro** [comment]
the same with /bpa reload

**Comment by GC-spigot** [comment]
Looking into this!

**Comment by GC-spigot** [comment]
Should be resolved
