### ISSUE TITLE
Flying

### ISSUE THREAD

**Issue by jakubcze1** [GC-spigot/battle-pass#20]
**Describe the bug**
Flying doesn't work with elytra!

  7:
    name: 'Týden 1. - Proleť se 20000 bloků'
    type: fly
    variable: none
    required-progress: 20000
    points: 15
    exclusive: premium
    item:
      material: elytra:0
      amount: 1
      name: '&eProleť se 20000 bloků'
      lore:
        - '&7pro splnění úkolů.'
        - ''
        - '&c&lPremium úkol'
        - ' &fTento úkol vyžaduje mít'
        - ' &faktivovaný premium BattlePass &6/store&f!'
        - ''
        - ' &eBody: &6+15'
        - ' &ePostup: &f%total_progress%&7/&f%required_progress%'

**Screenshots / Video**
If applicable, add screenshots or videos to help explain/ show your problem.

**Server Information:
- Server Version: 1.16.5
- Plugin Version: 3.14

**Comment by GC-spigot** [comment]
Added support!
