### ISSUE TITLE
[Issue] Default minecraft message Disable 

### ISSUE THREAD

**Issue by PanHaskins** [GC-spigot/battle-pass#201]
[22:54:39 INFO]: Showing new title for Metxiiiiq
[22:54:39 INFO]: Showing new subtitle for Metxiiiiq

Good evening. I have a question about the task completion report. BattlePass creates a Title and Subtitle using the default minecraft function. I'd like to turn this off, as it's spamming the chat quite a bit. (Those who have some given rights and also in the console)

**Comment by GC-spigot** [comment]
Try setting `/gamerule sendCommandFeedback false` gamerules :)

**Comment by PanHaskins** [comment]
This Gamerule doesn´t work correctly. And Gamerule only works for a given world since some version.
