### ISSUE TITLE
Shopgui+ API Changes with Battlepass

### ISSUE THREAD

**Issue by SirCraftypants** [GC-spigot/battle-pass#202]
**Describe the bug**

`[10:09:16 ERROR]: [BattlePass] Plugin BattlePass v3.10.1 has failed to register events for class io.github.battlepass.quests.quests.external.ShopGuiPlusQuests because net/brcdev/shopgui/shop/ShopItem does not exist.`

**To Reproduce**
Install latest Shopgui+ with Battlepass, there's been API changes.

**Server Information (please complete the following information):**
- Server Version:  PaperSpigot-132 1.19.2]
- BP Version:   3.10.2
- SG+ Version:   1.78.0

**Comment by SirCraftypants** [comment]
Bumping

**Comment by GC-spigot** [comment]
Fixed
