### ISSUE TITLE
[Issue] Battlepass Quest craft observer not progressing

### ISSUE THREAD

**Issue by Tant33** [GC-spigot/battle-pass#203]
**Describe the bug**
I don't progress in the quest make observers. When I change the variable it works again.

**To Reproduce**
- See screenshot

**Screenshots / Video**
![image](https://user-images.githubusercontent.com/111907054/186229291-f6306270-f23e-4397-90f3-243258bd7f83.png)

**Server Information (please complete the following information):**
- Server Version: Paper version git-Paper-81 (MC: 1.19) (Implementing API version 1.19-R0.1-SNAPSHOT) (Git: 86f87ba)
- Plugin Version: [3.9.9.]

**Comment by GC-spigot** [comment]
For some reason vanilla defines it as `OBSERVER:3`, use that instead of `observer` as your variable :)

**Comment by Tant33** [comment]
Okay, thx for the help :)
