### ISSUE TITLE
Add Support FabledSkyblock, Ultimate Core, Boss™, and Dungeons.

### ISSUE THREAD

**Issue by JLucassz** [GC-spigot/battle-pass#21]
I see that the BattlePass plugin adds support for many other plugins, on my server I use the ones I mentioned above, I will give some suggestions to be added:

1. FabledSkyblock: 
- Quest when creating an island.
- Quest when it reaches a certain island level.
- Quest when you reach a certain number of votes on the island.
- Quest when changing the island's biome.
- Quest when it changes the climate of the island.
- Quest when you reach the island level TOP 1.
- Quest when it reaches the Top 1 of island vote.
- Quest when it reaches a certain island size.

2. Ultimate Core
- Quest when it reaches a certain skill level
- Quest when you reach the last level of each skill
- Quest when unlocking a collection
- Quest of when it reaches a certain collection level
- Quest of when it reaches the last level of each collection
- Quest when you create a pet.
- Quest when you reach a certain level of the pet.
- Quest when crafting any item on the HyperCrafting workbench.
- Quest when to enchant an item on the HyperEnchantments enchantment table.
- Quest when you trade something in Hypertrades.
- Quest of when it reaches a certain level of each attribute of the player.

3. Boss™
- Quest when you kill a specific boss.

4. Dungeons
- Quest when you complete a specific dungeon.
- Quest when you go to a dungeon for the first time
- Quest when you reach a specific number of dungeon failures.

I believe that adding support for these plugins and these quests will allow more options to create new quests and thus also attract more people who use these plugins, I hope it can be added, thank you for your attention and support.

**Comment by OpticFusion1** [comment]
Please provide links to these resources, otherwise the issue will be closed due to not enough information
