### ISSUE TITLE
crops, left-click and block-break event error (Please solve the error as soon as possible)

### ISSUE THREAD

**Issue by Sangnamja123** [GC-spigot/battle-pass#210]
**Describe the bug**
left-click and block-break does not count wheat seed, potato is not working

**To Reproduce**
4:
    name: '1주 - 농부는 힘들구나... (1)'
    type: left-click-block
    variable: crops:7 #i used crops, wheat, potato, potatos, carrot but this not worked
    required-progress: 200
    points: 10
    item:
      material: diamond_hoe:0
      amount: 1
      name: '&e농부는 힘들구나... (1)'
      lore:
        - ''
        - '&6● &e200개&f의 &e밀&f을 수확 해보자!'
        - ''
        - '&6● &f진행도: &e%total_progress%&7/&a%required_progress%'
        - ''

**Screenshots / Video**
If applicable, add screenshots or videos to help explain/ show your problem.

**Server Information (please complete the following information):**
- Server Version: [e.g. paper-1.12.2-1620]
- Plugin Version: [e.g. battle-pass-3.10.4]

**Comment by GC-spigot** [comment]
https://battlepass.advancedplugins.net/useful/harvesting-crops
