### ISSUE TITLE
seeds, block-place event error (Please solve the error as soon as possible)

### ISSUE THREAD

**Issue by Sangnamja123** [GC-spigot/battle-pass#211]
**Describe the bug**
and when using block-place event, seeds:0 item is not counted

**To Reproduce**
  4:
    name: '2주 - 농부는 힘들구나... (1)'
    type: block-place
    variable: seeds:0
    required-progress: 100
    points: 10
    item:
      material: diamond_hoe:0
      amount: 1
      name: '&e농부는 힘들구나... (1)'
      lore:
        - ''
        - '&6● &e100개&f의 &e씨앗&f을(를) 심어보자!'
        - ''
        - '&6● &f진행도: &e%total_progress%&7/&a%required_progress%'
        - ''

**Screenshots / Video**
If applicable, add screenshots or videos to help explain/ show your problem.

**Server Information (please complete the following information):**
- Server Version: [e.g. paper-1.12.2-1620]
- Plugin Version: [e.g. battle-pass-3.10.4]

**Comment by Entenlias** [comment]
Can you try "weed_seeds:0"?

**Comment by OpticFusion1** [comment]
Use the new "crops-planted" quest. If this issue still persists, create a new issue
