### ISSUE TITLE
[Issue] Daily quests 2 messages

### ISSUE THREAD

**Issue by Domzzo** [GC-spigot/battle-pass#213]
**Describe the bug**
The plugin sends 2 messages when daily quests reset.

**To Reproduce**
Not sure how to reproduce other than waiting for timer to pass.

**Screenshots / Video**
![2022-09-11_10 59 57](https://user-images.githubusercontent.com/107621105/191542449-fcb5e315-7193-4439-8735-3d9561f8aaee.png)

**Server Information (please complete the following information):**
Server: 1.19.2
Plugin: 3.10.7

**Comment by GC-spigot** [comment]
Can you send your configuration?

**Comment by Domzzo** [comment]
> Can you send your configuration?
You mean settings.yml? https://pastecode.io/s/fphgode1
If for other files id rather send them privately.

**Comment by Domzzo** [comment]
@GC-spigot

**Comment by GC-spigot** [comment]
Is it the `daily-quest-reset` message that shows 2 times?

**Comment by GC-spigot** [comment]
Nevermind, found the issue!

**Comment by Domzzo** [comment]
Thank you!
