### ISSUE TITLE
[Issue] envoy quests dont work

### ISSUE THREAD

**Issue by TheNimbleNinja** [GC-spigot/battle-pass#214]
**Describe the bug**
collecting the envoy chests dont add progress to quest
**To Reproduce**
A way to reliability reproduce the bug.

**Screenshots / Video**
If applicable, add screenshots or videos to help explain/ show your problem.

**Server Information (please complete the following information):**
spigot-1.19.2.jar
BattlePass-3.10.4.jar

**Comment by Erdi-GitHub** [comment]
Should be fixed in the next update
