### ISSUE TITLE
[Request] support to fancy crafting table

### ISSUE THREAD

**Issue by TheNimbleNinja** [GC-spigot/battle-pass#215]
**Describe the Request**
currently using this plugin breaks all crafting quests wat i want is support added to this plugin thanks

**Comment by OpticFusion1** [comment]
Please link the resource

**Comment by TheNimbleNinja** [comment]
https://www.spigotmc.org/resources/1-8-1-19-4-%E2%AD%90-battlepass-%E2%AD%90-unlimited-practical-customizable-quests-%E2%9A%94%EF%B8%8F-30-sale.63076/
