### ISSUE TITLE
Tier bug

### ISSUE THREAD

**Issue by DJ-Daniel** [GC-spigot/battle-pass#22]
When I add points to a player to level up to the next tier it unlocks all of the tiers at once. 

![unknown](https://user-images.githubusercontent.com/19392499/113418581-103a5c80-93c6-11eb-82cd-59c05da49b35.png)

- Server Version: Tunity 1.16.5-R0.1
- Plugin Version: 3.16

**Comment by Mentembentem** [comment]
I also had the problem that when I reached tier 50, it says in the prefix: Tier 51. 

Also when I reached tier 3 (I configurated the points etc. good) then I got set back to tier 2.

**Comment by GC-spigot** [comment]
Fixed
