### ISSUE TITLE
[Issue] - Rewards not showing up (bug)

### ISSUE THREAD

**Issue by Hegyiboii** [GC-spigot/battle-pass#220]
Umm, @GC-spigot, Hi, So basically I added a bunch of cool rewards (in rewards.yml), but when I reloaded and checked my tiers, nothing. Literally. 'Lore-addon:' was not there, and if I claimed a tier reward, I'd just get nothing. I checked with a helper on Discord and he has the same problem if using my config. (wich is apparentally fine & funcional)

To reproduce:
No real way was found to reproduce the bug, but what I can give you is my rewards config (in txt)

Screenshots + my config attached below ->
![Badlion Client Screenshot 2022 10 02 - 20 44 53 02](https://user-images.githubusercontent.com/114878925/193473901-50ebc30e-09d0-4ffd-9dc5-06ef8f063713.png)
![Badlion Client Screenshot 2022 10 02 - 20 44 53 85](https://user-images.githubusercontent.com/114878925/193473907-a20bb8c4-db54-4d50-914d-b99027b326fa.png)

**MY CONFIG IN TXT:** [rewards.txt](https://github.com/GC-spigot/battle-pass/files/9693386/rewards.paste.text.into.rewards.yml.txt)

-> Server Version: 1.17.1
-> Plugin Verison: 3.10.4

**Comment by GC-spigot** [comment]
This is a configuration issue: https://yaml.helpch.at

![image](https://user-images.githubusercontent.com/13188801/193527277-9d133eda-5131-4a03-93b1-055862dfddf7.png)

**Comment by Hegyiboii** [comment]
Ayy! Alright, well thanks so much for the quick reply & fix!

**Comment by Hegyiboii** [comment]
New: Nvm... (@GC-spigot ) Mine is a command, and I pasted in a totally working command. works in game, but yaml.helpch.at still tells me bad indentation, somewhere at the 'Display: Name:' section. Wich means I cannot use custom names for items? Isn't it supposed to be any command? Please help me out here

With custom name it won't work:
![Desktop Screenshot 2022 10 03 - 15 25 42 29](https://user-images.githubusercontent.com/114878925/193589100-c561535d-0918-4bd5-8b4b-3de9e51dc927.png)

But with just enchants, it will!!:
![Desktop Screenshot 2022 10 03 - 15 25 58 28](https://user-images.githubusercontent.com/114878925/193589179-7a2fb516-4a83-409d-8e11-4e94c7dc7c47.png)

Please help me/fix this...
