### ISSUE TITLE
[Issue] - Rewards not showing up (new)

### ISSUE THREAD

**Issue by Hegyiboii** [GC-spigot/battle-pass#222]
Hi again, @GC-spigot.
So, I added my rewards nice & neat into rewards.yml, and this issue keeps happening. (please see files linked below) - Basically, when adding a command reward and pasting a command that gives the player an item with a custom name, it'll glitch out or something like that. (please check files linked below) Oh, and the ting is that after removing the custom name and leaving only the enchantment, config works fine. Weird. **(Also, my command (WITH the custom name too) works ingame perfectly fine. I tested it by using a command block instead, and I got the item.)

To reproduce:
Add a reward as command, and add an item with enchantment and a custom name.

Screenshot of problem as described by HelpChat Parser (I don't understand why it's not completely valid...) + my current rewards.yml config attached below ->

**After removing custom name and leaving enchantment, config works fine, but the command should be working. (it worked ingame)**
![Desktop Screenshot 2022 10 03 - 18 30 13 95](https://user-images.githubusercontent.com/114878925/193907067-0ad75fa3-1619-4789-8ff9-0777f00c19fb.png)

Because it works ingame, but not in config, I suppose it's something with the BattlePass reward config settings.. maybe?
Thank you in advance for the help, would love to get a solid fix =)

**Comment by Hegyiboii** [comment]
Also, looks like by removing some brackets & square brackets, it makes the text valid, BUT this again prevents it from actually being a working command (would give nothing ingame anyway...)

![Desktop Screenshot 2022 10 04 - 21 27 52 74](https://user-images.githubusercontent.com/114878925/193908497-2a4be8ab-c028-4289-b9d1-e665b1d371aa.png)

**Comment by OpticFusion1** [comment]
Please send your rewards.yml. Chances are your syntax is incorrect, but we cannot be certain without it
