### ISSUE TITLE
[Issue] MySQL synchronization player data loss.

### ISSUE THREAD

**Issue by RusBrook** [GC-spigot/battle-pass#223]
**Describe the bug**
MySQL synchronization player data loss.

**To Reproduce**
After MySQL is enabled
The player's point/level data probability is lost when switching servers for many times and obtaining points

Both battle-pass-3.11.3 and battle-pass-3.11.2 have tried

In configuration file
Bungee fix: true and bungee fix: false
All tried
All have this serious problem

**Screenshots / Video**
If applicable, add screenshots or videos to help explain/ show your problem.

**Server Information (please complete the following information):**
- Server Version: [ paper-1.19.2-196 ]
- Plugin Version: [ battle-pass-3.11.3 and battle-pass-3.11.2]

**Comment by Erdi-GitHub** [comment]
This should be resolved in the latest version (See #363)
If this is still a problem for you in the latest version, you can open a new issue
