### ISSUE TITLE
[Issue] Plugin BattlePass v3.11.3 has failed to register events

### ISSUE THREAD

**Issue by passaport** [GC-spigot/battle-pass#225]
09.10 19:58:42 [Server] ERROR Plugin BattlePass v3.11.3 has failed to register events for class io.github.battlepass.quests.quests.external.MoneyHuntersQuests because su/nightexpress/moneyhunters/basic/api/event/PlayerJobExpGainEvent does not exist.

**Comment by Entenlias** [comment]
Do you have the MoneyHunters plugin installed?
