### ISSUE TITLE
[Issue] Placeholders are not working in weekly menus

### ISSUE THREAD

**Issue by Askarionn** [GC-spigot/battle-pass#226]
**Describe the bug**
Placeholders are not working in Weekly menus

**To Reproduce**
Add an item with papi placeholders

**Screenshots / Video**
https://imgur.com/a/G6yOMYB

**Server Information (please complete the following information):**
- Server Version: Pufferfish 1.19.2
- Plugin Version: 3.11.3

**Comment by GC-spigot** [comment]
Fixed
