### ISSUE TITLE
Sometimes the BattlePass plugin slows down my server a lot

### ISSUE THREAD

**Issue by DimaSergeew** [GC-spigot/battle-pass#230]
**Describe the bug**
How much it sometimes freezes my server you will see from the spark report

**To Reproduce**
it happens in moments

**Screenshots / Video**
Spark: https://spark.lucko.me/AHILW1kyDk

**Server Information (please complete the following information):**
- Server Version: [PurPur 1.19.2]
- Plugin Version: [battle-pass-3.11.3]

**Comment by GC-spigot** [comment]
Should be resolved / improved
