### ISSUE TITLE
Server crashed when using battle pass and mcmmo's treefeller due to, to many runneables/hooks[Issue]

### ISSUE THREAD

**Issue by dahbawz** [GC-spigot/battle-pass#234]
When MCMMO and battle pass are used at the same time, the server crashes due to a memory shortage. Battlepas uses too many hooks/runneables/ As soon as battlepas is turned off, there is nothing to worry about.

**To Reproduce**
Use MCMMO treefeller when battlepas is on. Doesnt matter how much RAM you give your server. Packets will be to large.

**Server Information (please complete the following information):**
- Server Version: [e.g. PaperSpigot-123 1.19
- Plugin Version: [e.g. 3.11.7

**Comment by ItzRobin** [comment]
Hi hi, we are still having this problem. I see the ticket has been closed by now, what has been the solution?

**Comment by austv** [comment]
@ItzRobin @dahbawz @GC-spigot Did you solve the problem? I have to disable my BattlePass since a month. I tried to disable tree feller but still is crashing
