### ISSUE TITLE
new configuration error

### ISSUE THREAD

**Issue by ImYenil** [GC-spigot/battle-pass#236]
**Describe the bug**
There is an error in the newly added quest file

**To Reproduce**
https://pastebin.com/gKs2MjtL
**Screenshots / Video**
If applicable, add screenshots or videos to help explain/ show your problem.

**Server Information (please complete the following information):**
- Server Version: [e.g. PaperSpigot-123 1.8.8]
- Plugin Version: [e.g. 6.7.8]

**Comment by ImYenil** [comment]
updated new version still issue
https://pastebin.com/XBZV3b9K

**Comment by GC-spigot** [comment]
Resolved in next version, regen your daily-quests file :)
