### ISSUE TITLE
[Request] Add papi support for the item's material

### ISSUE THREAD

**Issue by LXY010327** [GC-spigot/battle-pass#239]
**Describe the Request**
You know, I must use material: 'head:%player_name%' when I want to show the skull with the skin of the player who open the GUI. But sadly, the material dose not support PAPI. I hope it will in the future.

**Comment by NaTorOG** [comment]
I agree, I also tried as GC told me with {player_name} but its not working

**Comment by GC-spigot** [comment]
Added for next version: https://battlepass.advancedplugins.net/general/custom-heads-in-menus#players-head-in-gui
