### ISSUE TITLE
[Issue] Cooking salmon is not working(only for salmon)

### ISSUE THREAD

**Issue by NaTorOG** [GC-spigot/battle-pass#240]
**Describe the bug**
Smelt mission doesn't work for Food Cooked_Salmon, while its working perfectly with other foods

  3: # Quest id
    name: 'Cuoco - 1' # The name given to the quest.
    type: smelt # The type of quest
    variable: cooked_porkchop:0 OR cooked_beef:0 OR cooked_mutton:0 OR cooked_rabbit:0 OR cooked_chicken:0 OR cooked_salmon OR cooked_cod:0 OR baked_potato:0 # The block the player must break.
    required-progress: 100 # The amount of times the player should break the coal ore block.
    points: 1 # The amount of points that will be rewarded
    # exclusive: premium
    item: # The item that will be displayed in menus.
      material: wooden_sword:0
      customModelData: 10005
      amount: 1
      name: '&cCuoco I'
      lore:
        - '&7Cucina &f100&7 alimenti'
        - ''
        - '&7Carne &f- &7Pesce &f- &7Patate'
        - ''
        - '&c%progress_bar% &c%percentage_progress%'

**Screenshots / Video**
If applicable, add screenshots or videos to help explain/ show your problem.

**Server Information (please complete the following information):**
- This server is running Pufferfish version git-Pufferfish-42 (MC: 1.19.2) (Implementing API version 1.19.2-R0.1-SNAPSHOT) (Git: dda277a on HEAD)versio
- BattlePass version 3.12.3

**Comment by NaTorOG** [comment]
also with cooked_salmon:0 not working

**Comment by NaTorOG** [comment]
UP

**Comment by NaTorOG** [comment]
Still not working in 3.12.7

**Comment by NaTorOG** [comment]
Any Updates? @GC-spigot

**Comment by GC-spigot** [comment]
Fixed, it was COOKED_SALMON:1, now it's COOKED_SALMON only !
