### ISSUE TITLE
Multiple rewards bug if one of them stop working [Issue]

### ISSUE THREAD

**Issue by SirvydasS** [GC-spigot/battle-pass#242]
**Describe the bug**
I was having a serious bug... In my rewards, I have a double reward: MONEY reward and SELLSTICK reward (giving item).
So for some reason, the Sellstick plugin crashes one day and player can take that one rewards infinitely times and have a lot of money.

Reward config example:

'8': # FREE
  type: command
  name: 'Pinigai'
  lore-addon:
    - '&7 - &ePinigai - 80000!'
  commands:
    - 'eco give %player% 80000'
    - 'sellstick give %player% 1 80'

**To Reproduce**
1. Create reward as in the example (I think you can use any other plugin, not required Sellstick (NOT SURE)).
2. Corrupt the plugin or simple way with plugman: /plugman disable SellStick
3. Claim the prize (click infinity).

**Screenshots / Video**
https://youtu.be/pWKrTc-3154

**Server Information (please complete the following information):**
- Server Version: Current: git-Purpur-1848 (MC: 1.19.2)*
- Plugin Version: battle-pass-3.11.0

**Suggestion**
Make rewards funcion simple. If player press button rewards instant marks as taken. So that it is not seen whether all the commands are working or not. Maybe if plugin sees something not quit work write to player that was error in one reward.

**Comment by SirvydasS** [comment]
This bug was tested and on battle-pass-3.12.1

**Comment by GC-spigot** [comment]
Pataisysiu, aciu uz pranesima :D
