### ISSUE TITLE
[Issue] Crafting quests can be completed by clicking the crafted item, in a crafting table, with an another item.

### ISSUE THREAD

**Issue by Hoknyy** [GC-spigot/battle-pass#243]
**Describe the bug**
Crafting quests can be completed by clicking the crafted item, in a crafting table, with an another item.

**To Reproduce**
Have a craftin quest available : craft the item once, but instead of picking the final result of the recipe (ex : paper), click it with another item (ex: diamond). Look the video below for more explanation.

**Screenshots / Video**
[If applicable, add screenshots or videos to help explain/ show your problem.](https://youtu.be/APm8VOIxe2o)

**Server Information (please complete the following information):**
- Server Version: InterStellar 1.8 (TacoSpigot fork 1.8)
- Plugin Version: Latest (updated it to be sure and the issue is still there)

**Comment by GC-spigot** [comment]
Should be resolved
