### ISSUE TITLE
[Issue] Bug while getting battlepass premium after user has already completed some weeks.

### ISSUE THREAD

**Issue by NaTorOG** [GC-spigot/battle-pass#245]
**Describe the bug**
Usually, players purchase the BattlePass Premium after playing for a while or completing some weeks.
That's what happened.
A user completed 2 weeks of free quests and unlocked the third-week of quests.
Now that he has purchased the battlepass, this is what he sees. https://imgur.com/a/vJqkOrk
2nd-week is locked, as it should be because I have set that you are able to access a week only after you complete all the previous week's quests.
So to be correct, now he should only be able to see the 1st-week again because he has purchased Premium and he needs to finish also 1st-week premium quests to be able to access other weeks.

**To Reproduce**
Without battlepass premium, complete 2 or more free week quests(with unlock-week option only if you finished all the previous week quests)
After completing the free quests, get the Premium permission for battlepass premium and you will see the error, because if it was correct, all the week except for week 1 should have been locked again, till the users finish also week 1 premium quests to unlock week 2 quests.

**Screenshots / Video**
https://imgur.com/a/vJqkOrk

**Server Information (please complete the following information):**
- Server Version: Pufferfish+ 1.19.2
- Plugin Version: [3.12.7]

**Comment by KPGTB** [comment]
Hey! The problem has been fixed. It will be available in the next update
