### ISSUE TITLE
[Issue]

### ISSUE THREAD

**Issue by PROMETEOLEGEND** [GC-spigot/battle-pass#248]
**Describe the bug**
After updating to the latest version of mythicmobs, the battle pass mythicmobs mob killing missions do not work correctly. 

**To Reproduce**
simply create a mission to defeat a mythicmob mob

**Screenshots / Video**
![image](https://user-images.githubusercontent.com/120188190/206711616-cb7391d7-8e5e-439b-b0ac-1a3204e51d35.png)

**Server Information (please complete the following information):**
- Server Version: Purpur 1.19.2
- Plugin Version: MythicMobs-5.2.1-SNAPSHOT (lastdevbuild) & battle-pass-3.12.9

**Comment by Erdi-GitHub** [comment]
This is no longer an issue in the latest version of BattlePass
If you are still having problems in the latest version, you can open a new issue
