### ISSUE TITLE
Not counted properly when crafting with shift [Issue]

### ISSUE THREAD

**Issue by SirvydasS** [GC-spigot/battle-pass#249]
**Describe the bug**
Not counted properly when crafting with shift. Example crafting Cookies if you craft with shift, you craftin a lot more cookies, but plugint counts only 64l

**To Reproduce**
Watch video.

**Screenshots / Video**
https://youtu.be/ZKXztWiHb0Y

**Server Information (please complete the following information):**
- Server Version: Current: git-Purpur-1858 (MC: 1.19.2)*
- Plugin Version: battle-pass-3.11.0

**Comment by NaTorOG** [comment]
I have also noticed it, in my purpose its okay, basically it counts the single unit.
So you produce 8 cookies with a single crafting, but it counts 1 cookie produced, this happens for every item that when crafted gives more than the single unit.
Another example is with torch
