### ISSUE TITLE
[Issue] Not Loading In

### ISSUE THREAD

**Issue by ItsNoWorry** [GC-spigot/battle-pass#251]
**Describe the bug**
The jar is disabled when the server starts

**Server Information (please complete the following information):**
- Wine Spigot
---------------ERROR---------------
14.12 21:37:47 [Server] ERROR Error occurred while enabling BattlePass v3.12.2 (Is it up to date?)
14.12 21:37:47 [Server] INFO java.lang.NullPointerException
14.12 21:37:47 [Server] INFO at io.github.battlepass.cache.QuestCache.cache(QuestCache.java:88) ~[?:?]
14.12 21:37:47 [Server] INFO at io.github.battlepass.BattlePlugin.load(BattlePlugin.java:268) ~[?:?]
14.12 21:37:47 [Server] INFO at io.github.battlepass.BattlePlugin.onEnable(BattlePlugin.java:98) ~[?:?]
14.12 21:37:47 [Server] INFO at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[custom.jar:1_8_R3]
14.12 21:37:47 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:321) ~[custom.jar:1_8_R3]
14.12 21:37:47 [Server] INFO at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:420) ~[custom.jar:1_8_R3]
14.12 21:37:47 [Server] INFO at com.rylinaux.plugman.util.PluginUtil.enable(PluginUtil.java:62) ~[?:?]
14.12 21:37:47 [Server] INFO at com.rylinaux.plugman.command.EnableCommand.execute(EnableCommand.java:127) ~[?:?]
14.12 21:37:47 [Server] INFO at com.rylinaux.plugman.PlugManCommandHandler.onCommand(PlugManCommandHandler.java:95) ~[?:?]
14.12 21:37:47 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[custom.jar:1_8_R3]
14.12 21:37:47 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:163) ~[custom.jar:1_8_R3]
14.12 21:37:47 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:709) ~[custom.jar:1_8_R3]
14.12 21:37:47 [Server] INFO at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1448) ~[custom.jar:1_8_R3]
14.12 21:37:47 [Server] INFO at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1255) ~[custom.jar:1_8_R3]
14.12 21:37:47 [Server] INFO at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45) ~[custom.jar:1_8_R3]
14.12 21:37:47 [Server] INFO at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1) ~[custom.jar:1_8_R3]
14.12 21:37:47 [Server] INFO at net.minecraft.server.v1_8_R3.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:34) ~[custom.jar:1_8_R3]
14.12 21:37:47 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_312]
14.12 21:37:47 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_312]
14.12 21:37:47 [Server] INFO at net.minecraft.server.v1_8_R3.SystemUtils.a(SystemUtils.java:11) [custom.jar:1_8_R3]
14.12 21:37:47 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:945) [custom.jar:1_8_R3]
14.12 21:37:47 [Server] INFO at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:371) [custom.jar:1_8_R3]
14.12 21:37:47 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:870) [custom.jar:1_8_R3]
14.12 21:37:47 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:760) [custom.jar:1_8_R3]
14.12 21:37:47 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_312]
14.12 21:37:47 [Server] INFO Disabling BattlePass v3.12.2
14.12 21:37:47 [Server] ERROR Error occurred while disabling BattlePass v3.12.2 (Is it up to date?)
14.12 21:37:47 [Server] INFO java.lang.NullPointerException
14.12 21:37:47 [Server] INFO at io.github.battlepass.storage.DailyQuestStorage.lambda$serializer$2(DailyQuestStorage.java:33) ~[?:?]
14.12 21:37:47 [Server] INFO at me.hyfe.simplespigot.storage.storage.Storage.save(Storage.java:50) ~[?:?]
14.12 21:37:47 [Server] INFO at io.github.battlepass.BattlePlugin.unload(BattlePlugin.java:322) ~[?:?]
14.12 21:37:47 [Server] INFO at io.github.battlepass.BattlePlugin.onDisable(BattlePlugin.java:110) ~[?:?]
14.12 21:37:47 [Server] INFO at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:323) ~[custom.jar:1_8_R3]
14.12 21:37:47 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:349) ~[custom.jar:1_8_R3]
14.12 21:37:47 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:325) ~[custom.jar:1_8_R3]
14.12 21:37:47 [Server] INFO at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:420) ~[custom.jar:1_8_R3]
14.12 21:37:47 [Server] INFO at com.rylinaux.plugman.util.PluginUtil.enable(PluginUtil.java:62) ~[?:?]
14.12 21:37:47 [Server] INFO at com.rylinaux.plugman.command.EnableCommand.execute(EnableCommand.java:127) ~[?:?]
14.12 21:37:47 [Server] INFO at com.rylinaux.plugman.PlugManCommandHandler.onCommand(PlugManCommandHandler.java:95) ~[?:?]
14.12 21:37:47 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[custom.jar:1_8_R3]
14.12 21:37:47 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:163) ~[custom.jar:1_8_R3]
14.12 21:37:47 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:709) ~[custom.jar:1_8_R3]
14.12 21:37:47 [Server] INFO at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1448) ~[custom.jar:1_8_R3]
14.12 21:37:47 [Server] INFO at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1255) ~[custom.jar:1_8_R3]
14.12 21:37:47 [Server] INFO at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45) ~[custom.jar:1_8_R3]
14.12 21:37:47 [Server] INFO at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1) ~[custom.jar:1_8_R3]
14.12 21:37:47 [Server] INFO at net.minecraft.server.v1_8_R3.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:34) ~[custom.jar:1_8_R3]
14.12 21:37:47 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_312]
14.12 21:37:47 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_312]
14.12 21:37:47 [Server] INFO at net.minecraft.server.v1_8_R3.SystemUtils.a(SystemUtils.java:11) [custom.jar:1_8_R3]
14.12 21:37:47 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:945) [custom.jar:1_8_R3]
14.12 21:37:47 [Server] INFO at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:371) [custom.jar:1_8_R3]
14.12 21:37:47 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:870) [custom.jar:1_8_R3]
14.12 21:37:47 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:760) [custom.jar:1_8_R3]
14.12 21:37:47 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_312]
14.12 21:37:47 [Server] INFO NoWorry issued server command: /plugman enable BattlePass
14.12 21:37:48 [Server] INFO Fetching all due players...

**Comment by GC-spigot** [comment]
Fixed
