### ISSUE TITLE
[Issue] Death Quest error

### ISSUE THREAD

**Issue by YKDZ** [GC-spigot/battle-pass#254]
**Describe the bug**
It seems that plugin can not invoke death event.
https://mcpaste.com/2309ed4b9ba13f121a1f409b4a1cebf6

**To Reproduce**
Just install the plugin.

**Server Information (please complete the following information):**
- Server Version: Purpur 1857 1.19.2
- Plugin Version: 3.13.1

**Comment by GC-spigot** [comment]
Fixed
