### ISSUE TITLE
Could not pass event PlayerCommandPreprocessEvent to BattlePass v3.13.5

### ISSUE THREAD

**Issue by DimaSergeew** [GC-spigot/battle-pass#256]
**Describe the bug**
It happens from time to time in my server console

**To Reproduce**
-

**Screenshots / Video**
https://mclo.gs/dF7mdNI

**Server Information (please complete the following information):**
- Server Version: Purpur 1.19.2-R0.1-SNAPSHOT
- Plugin Version: BattlePass v3.13.5

**Comment by GC-spigot** [comment]
Fixed
