### ISSUE TITLE
[Issue] Glow items bugs in daily and week quests

### ISSUE THREAD

**Issue by RSLuke** [GC-spigot/battle-pass#264]
**Describe the bug**

For daily quests : The glow just does not appear when the quest is completed

For week quests :
- When someone on the server finishes a week quest, the glow appears for everyone on the server
- After a season is renewed with the bpa new season command, the glow doesnt reset until there is a reload or a restart

**Server Information (please complete the following information):**
Paper 1.19.2
battle-pass-3.14.1

**Comment by KPGTB** [comment]
Hey! I can't reproduce your problem with daily quests, but I fixed problems with week quests that you mentioned. It will be available in the next update
