### ISSUE TITLE
[Issue] Cocoa ids small bug

### ISSUE THREAD

**Issue by RSLuke** [GC-spigot/battle-pass#266]
**Describe the bug**
I don't know if you can do something about it but since cocoa have infinite ages, we have to use something like `cocoa:3 OR cocoa:4 OR cocoa:5 OR cocoa:6 OR cocoa:7 OR cocoa:8 OR cocoa:9 OR cocoa:10 OR cocoa:11 OR cocoa:12` for it to count properly when a player breaks it

Server Information (please complete the following information):
Paper 1.19.2
battle-pass-3.14.1

**Comment by Erdi-GitHub** [comment]
Hi,
You can use a negative data value as a wildcard, like so: 
```
    type: block-break
    variable: cocoa:-1
```
