### ISSUE TITLE
[Issue] 1st tier issue

### ISSUE THREAD

**Issue by RSLuke** [GC-spigot/battle-pass#269]
**Describe the bug**
The 1st tier is always bugged but it reacts differently whether you have admin permission or not

When you are a player : 
The 1st tier is seen as unlocked from the beginning of the season (without doing any quests) but it unlocks properly and gives rewards when reached

When you are an admin :
The 1st tier is seen as unlocked as well, but when you reach it, it automatically switches to "rewards already recieved" item and doesn't give any rewards when you click on it since it is counted as recieved already

Server Information (please complete the following information):
Paper 1.19.2
battle-pass-3.14.1

**Comment by KPGTB** [comment]
Hey! Problem has been fixed. It will be available in the next update.
