### ISSUE TITLE
[Request] Bosses

### ISSUE THREAD

**Issue by dinobossytnew** [GC-spigot/battle-pass#274]
**Describe the Request**
Add support for kill [bossses](https://builtbybit.com/resources/boss-unbelievable-custom-monsters.21619/) mobs

**Comment by dinobossytnew** [comment]
If they manage to kill bosses name.

**Comment by KPGTB** [comment]
Hey! We won't add plugin support as it's paid plugin and only you want support for it, but I added `custom-name` subroot to `kill-mob` quest, so you'll be able to make this quest using boss name
