### ISSUE TITLE
Wrong api

### ISSUE THREAD

**Issue by Lerphie** [GC-spigot/battle-pass#275]
**Describe the bug**
When opening the case to reproduce an error in the console

**To Reproduce**
Download https://www.spigotmc.org/resources/excellentcrates-advanced-custom-crates-now-even-better.48732/
And write the command /case forceopen diamond

**Screenshots / Video**
![image](https://user-images.githubusercontent.com/66962762/213729648-372ce683-0d8c-41c7-a02f-cab943cc5f07.png)

**Server Information (please complete the following information):**
Purpur-1898 (MC: 1.19.3)
BattlePass 3.14.2

**Comment by Lerphie** [comment]
@GC-spigot  This is a very serious problem that occurs almost every time you connect via the api

**Comment by GC-spigot** [comment]
Fixed, excellentcrates updated their api
