### ISSUE TITLE
DMCA Notice

### ISSUE THREAD

**Issue by jeqostudios** [GC-spigot/battle-pass#277]
January 23, 2023

Dear GC,

I am writing to bring to your attention an infringement of my copyrighted work that appears on your website/platform. The infringing material can be found at the following URL: https://advancedplugins.net/item/Immersive-BattlePass-UI.110. The copyrighted work in question is the entirety of the Battle Pass UIs; the original assets can be found here: https://mcmodels.net/model/battle-pass-ui/. All original works were created by myself, Jeqo, which include 5 graphic user interfaces, around 10 sprites, and menu and language configurations.

I am the exclusive copyright owner of the above-mentioned material. The unauthorized use of my copyrighted work is a violation of the Digital Millennium Copyright Act (DMCA). I respectfully request that you take immediate action to remove or disable access to the infringing material within 7 days from the receipt of this notice and confirm the removal of the infringing material in writing.

Please be advised that any active licenses held by you or your organization for the use of the copyrighted material in question are immediately revoked, and any future licenses will be denied. Furthermore, any unauthorized use, distribution, or reproduction of my copyrighted work will result in legal action.

Please also be advised that under the DMCA, any person who knowingly materially misrepresents that material or activity is infringing may be subject to liability.

I appreciate your cooperation in this matter and thank you for your prompt attention to this matter.

Sincerely,
Jeqo

**Comment by Ringlings** [comment]
Hi, did this get followed up on? From the looks of things nothing was changed and it was just closed instantly.

**Comment by Awpmeister2170** [comment]
Yes the Menu has changed, it has been remade and posted. as you can see by our page it is different.
