### ISSUE TITLE
Battlepass GUI slots 38, 41, 43 dont accept any type of fillers 

### ISSUE THREAD

**Issue by aXe18** [GC-spigot/battle-pass#278]
**Describe the bug**
On ticket #battlepass-0865 customer came whit problem that slots 38, 41 and 43 wont accept any fillers. 

**To Reproduce**
I tried his configs and then i tried on my own, even me did not get those slots accept any type of fillers, but i did not try anything else than fillers.
![Screenshot_703](https://user-images.githubusercontent.com/26152540/214684756-e0e5780e-b59b-44db-92c4-07bece2fc55f.png)
![Screenshot_701](https://user-images.githubusercontent.com/26152540/214684808-d4b589af-88ee-4cd5-a3f5-cf42bd32329c.png)

**Server Information (please complete the following information):**
- Server Version: customer 1.19.3 purpur and me 1.19.3 paper #384
![image](https://user-images.githubusercontent.com/26152540/214686277-674efc1b-7074-48c5-ac49-b5da3f010b51.png)

- Plugin Version: Both used latest 3.14.3

**Comment by GC-spigot** [comment]
Fixed
