### ISSUE TITLE
PyroFishingPro and Specialised Crates support.

### ISSUE THREAD

**Issue by SirCraftypants** [GC-spigot/battle-pass#28]
Hi,

Please can you make it compatible with:

[Specialised Crates](
https://www.spigotmc.org/resources/%E2%9C%85-specialized-crates-%E2%AD%90-7-custom-crate-animations-special-crates-%E2%AD%90-easy-to-use-in-game-gui-editor%E2%AD%95.9047/)
&
[PyroFishing/PyroFishingPro](https://www.spigotmc.org/resources/pyrofishingpro-1-14-x-1-16-x-1-fishing-plugin.60729/)

**Comment by OpticFusion1** [comment]
There is not enough information here for us to be able to do anything. Please re-make the issue using the new "Quest Type" issue template.

**Comment by OpticFusion1** [comment]
There is not enough information here for us to be able to do anything. Please re-make the issue using the new "Quest Type" issue template. Please also make two separate issues, one for each request.
