### ISSUE TITLE
Rewards and tiers are messed up in version 3.14.4

### ISSUE THREAD

**Issue by aXe18** [GC-spigot/battle-pass#280]
**Describe the bug**
Rewards GUI is broken on version 3.14.4, changes slots and tiers are messed up time to time 

**To Reproduce**
Download version 3.14.4 and try moving in menu, use menu or anything 

**Screenshots / Video**

![Screenshot_746](https://user-images.githubusercontent.com/26152540/215490107-9bb73ac1-b48a-4a47-8750-5ce851f0e9ad.png)
![Screenshot_749](https://user-images.githubusercontent.com/26152540/215490112-151d53ac-3c8b-454b-a803-6c7b3477eab7.png)
![Screenshot_748](https://user-images.githubusercontent.com/26152540/215490113-b8bd80f1-b124-4ee1-a848-69ae49e7aeab.png)
![Screenshot_747](https://user-images.githubusercontent.com/26152540/215490114-a1986ab5-5ca3-4f34-a820-3465709731a9.png)

**Server Information (please complete the following information):**
- Server Version: paper 1.19.3
- Plugin Version: 3.14.4

**Comment by aXe18** [comment]
[transcript-battlepass-0873.pdf](https://github.com/GC-spigot/battle-pass/files/10536340/transcript-battlepass-0873.pdf)

**Comment by Yoloman0013** [comment]
Same thing with 3.14.5

**Comment by GC-spigot** [comment]
Fixed
