### ISSUE TITLE
Random rewards showing after the last rewards

### ISSUE THREAD

**Issue by SalomonPicos** [GC-spigot/battle-pass#281]
**Describe the bug**
Hello. Basically when i scroll to the last page of the rewards gui, after the last reward wich is the 50th, it just puts more random rewards till the last available slot.

**To Reproduce**
Set the rewards to have more then 1 page of the gui and not fill competely the last page rewards slots.

**Screenshots / Video**
In this image you can see the last reward, wich is slot 50
![immagine](https://user-images.githubusercontent.com/88857385/216586856-fd9d0ce6-8a38-4ddb-aeb1-5682299c2b8f.png)

All the underlined rewards should not be there.
![Immagine 2023-02-03 115940](https://user-images.githubusercontent.com/88857385/216586991-9c4585f2-5ed4-4168-bf22-59d85f050e0a.png)

It goes from 50 to 42 randomly.
![immagine](https://user-images.githubusercontent.com/88857385/216587130-7facd1db-d537-4387-a2ea-9299137a92b6.png)

![immagine](https://user-images.githubusercontent.com/88857385/216587185-98be8a83-0e80-4785-b681-e8d98e69dd8b.png)

**Server Information (please complete the following information):**
- This server is running Paper version git-Paper-307 (MC: 1.19.2) (Implementing API version 1.19.2-R0.1-SNAPSHOT) (Git: 476ef25)
You are running the latest version
Previous version: git-Paper-379 (MC: 1.19.3)
- Plugin Version: 3.14.5

**Comment by GC-spigot** [comment]
Already fixed in latest version
