### ISSUE TITLE
[Issue] Rewards

### ISSUE THREAD

**Issue by ySakite** [GC-spigot/battle-pass#282]
**Describe the bug**
Awards that have a high "ID" don't display correctly (for example, at level 50 free/premium)

**To Reproduce**
Moderator Jben has the files and said he would check it out, and I was supposed to write issue here

**Server Information (please complete the following information):**
- Server Version: Purpur-1907 - MC 1.19.3
- Plugin Version: 3.14.6

**Comment by GC-spigot** [comment]
We can't recreate it, please continue in the ticket.
