### ISSUE TITLE
Enchant quest issue

### ISSUE THREAD

**Issue by razzeking** [GC-spigot/battle-pass#284]
**Describe the bug**
When doing a quest including enchanting stuff, nothing happens when you enchant stuff

**To Reproduce**
1. Enchant the required item with the required enchant

**Screenshots / Video**
https://streamable.com/h8de9c <-- here is a video showing me doing a enchant quest

**Server Information (please complete the following information):**
- Server Version: Paper version git-Paper-307 (MC: 1.19.2)
- Plugin Version: 3.14.6

**Comment by GC-spigot** [comment]
Can you provide quest configuration?

**Comment by razzeking** [comment]
> Can you provide quest configuration?

https://pastebin.com/Ss8PJq22

**Comment by razzeking** [comment]
> Can you provide quest configuration?

https://pastebin.com/0W66R2kb

**Comment by razzeking** [comment]
i dont know if its the same with the week ones too

**Comment by OpticFusion1** [comment]
It's broken for the week ones as well. It's possible BP is just not getting the correct values from the quest config
