### ISSUE TITLE
[Issue] Loop premium reward.

### ISSUE THREAD

**Issue by SirJben** [GC-spigot/battle-pass#285]
**Describe the bug**
When a player loses his premium pass and has it back players can reclaim their premium rewards in that season.

**To Reproduce**
Add rank on you ->  Collect premium rewards -> Remove your rank -> Add rank on you ->  Collect premium rewards... (Looping)

**Screenshots / Video**
N/A

**Server Information (please complete the following information):**
- Plugin Version: [3.14.6]

A temporary solution for this is to not give players their premium back in that season.

**Comment by KPGTB** [comment]
Hey! The problem has been fixed. It will be available in the next update
