### ISSUE TITLE
[Request] Add support for AdvancedMobs

### ISSUE THREAD

**Issue by ShockCharge** [GC-spigot/battle-pass#286]
**Describe the Request**
Similar to MythicMobs its going to be advancedmobs_kill_mob

![image](https://user-images.githubusercontent.com/48907444/217010736-9d62ee70-3a9f-4595-8969-b58423b7a1b7.png)
![image](https://user-images.githubusercontent.com/48907444/217011604-8f65a377-5dc7-4dfb-a105-ab59d244f1d4.png)
![image](https://user-images.githubusercontent.com/48907444/217011047-21c0f9f1-99e4-4569-bca4-f905695bedf9.png)

**Comment by KPGTB** [comment]
Hey! Will be available soon
