### ISSUE TITLE
[Issue] CrazyCrates not being counted when opening crates

### ISSUE THREAD

**Issue by ShockCharge** [GC-spigot/battle-pass#287]
![image](https://user-images.githubusercontent.com/48907444/217014050-c6f4879b-a4b4-4d08-9037-d4d5f91795ba.png)
![image](https://user-images.githubusercontent.com/48907444/217010736-9d62ee70-3a9f-4595-8969-b58423b7a1b7.png)
![image](https://user-images.githubusercontent.com/48907444/217011604-8f65a377-5dc7-4dfb-a105-ab59d244f1d4.png)
![image](https://user-images.githubusercontent.com/48907444/217011047-21c0f9f1-99e4-4569-bca4-f905695bedf9.png)

- Server Version: git-Purpur-1428 (MC: 1.17.1)
- Plugin Version: battle-pass-3.14.6

https://pastebin.com/UQiHKDfm

**Comment by Erdi-GitHub** [comment]
This was recently fixed (#408)
