### ISSUE TITLE
[Issue] block-break type doesn't work

### ISSUE THREAD

**Issue by iBuseWinner** [GC-spigot/battle-pass#29]
**Describe the bug**
Can't complete quests with `block-break` type

**Server Information (please complete the following information):**
- Server Version: git-Purpur 1.16.5
- Plugin Version: 3.24

**Comment by ZakShearman** [comment]
Can you zip and attach your entire battlepass folder as well as specify the week and ID of the quest not working

**Comment by iBuseWinner** [comment]
> Can you zip and attach your entire battlepass folder as well as specify the week and ID of the quest not working

https://drive.google.com/file/d/17eHa04sSV9JNGxb65G25EZ6A7vFjkcpW/view?usp=sharing
