### ISSUE TITLE
Battlepass giving error if you have excellentcrates too

### ISSUE THREAD

**Issue by aXe18** [GC-spigot/battle-pass#290]
**Describe the bug**
Battlepass gives "Could not pass event CrateOpenEvent to BattlePass" error on console if both plugins are installed

**To Reproduce**
Any battlepass version at least from 3.14.3 and excellentcrates

**Screenshots / Video**
[excellentcrates.txt](https://github.com/GC-spigot/battle-pass/files/10678187/excellentcrates.txt)

**Server Information (please complete the following information):**
- Server Version: at least on paper 1.19.3
- Plugin Version: 3.14.3 ->

**Comment by Need3v** [comment]
same here

**Comment by Erdi-GitHub** [comment]
Recently fixed (#407)
