### ISSUE TITLE
[Issue] Issues concerning smelting

### ISSUE THREAD

**Issue by Julilaa** [GC-spigot/battle-pass#293]
Hello,

I've got some bug concerning the missions of smelting: 

There are two problems with the melting and cooking missions.

- First bug : Let's imagine that the player has to cook 20 potatoes. When the 20 potatoes are cooked, if he clicks on his throw key on one of the cooked potatoes, 20 cooked potatoes are counted in the mission. 
And so on, so there are 19 cooked potatoes left in the oven, if the player throws one of the potatoes back, 19 potatoes are counted. 
- Second bug: The **cooked_salmon** are not counted at all.

Thanks in advance !

**Comment by GC-spigot** [comment]
First:
 - Fixed
Second:
 - Fixed, it was COOKED_SALMON:1, now it's COOKED_SALMON only !
