### ISSUE TITLE
[Issue] Issue concerning the anvil

### ISSUE THREAD

**Issue by Julilaa** [GC-spigot/battle-pass#294]
Hello,

Bug concerning enchantments via anvil: 

Let's say a player needs to enchant an item with a mending book. He places a diamond helmet and a mending book in the anvil. 
However, the player did not have enough xp on him to perform this action, but since he does not know or has not seen it, he clicks on the final item that is supposed to be enchanted with mending.
The book is not consumed but the action of enchanting with the book is still taken into account by the battle pass. 

Thanks in advance !

**Comment by memosoff** [comment]
https://github.com/GC-spigot/battle-pass/issues/292

**Comment by GC-spigot** [comment]
Fixed
