### ISSUE TITLE
Errors on console 3.14.9

### ISSUE THREAD

**Issue by aXe18** [GC-spigot/battle-pass#298]
**Describe the bug**
New 3.14.9 version gives alot errors on console

**To Reproduce**
Download new version 

**Screenshots / Video**
![Screenshot_921](https://user-images.githubusercontent.com/26152540/219627768-39ae1524-263e-4e03-88fe-619a2170eb5f.png)

https://pastebin.com/cM8rLqvy

**Server Information (please complete the following information):**
- Server Version: paper 1.19.3 #404
- Plugin Version: 3.14.9

**Comment by GC-spigot** [comment]
Fixed
