### ISSUE TITLE
[Issue] Could not pass event BlockBreakEvent to BattlePass v3.15.2

### ISSUE THREAD

**Issue by AVuTuVA** [GC-spigot/battle-pass#300]
### Describe the bug

break any block on version 1.12.2 and this error in the console

### How to reproduce

break any block on version 1.12.2 and this error in the console

### Server Log

https://yaso.su/v9hwzghP

**Comment by DIDIRUS4** [comment]
It's can be introducing in 3.15.1 ang highter. In 3.15.0 and below no error occured while breaking any blocks. It's bread harvest quest error (Added in 3.15.1)

**Comment by OpticFusion1** [comment]
The link is invalid, please use something like pastebin.com

**Comment by AVuTuVA** [comment]
new link: https://yaso.su/v9hwzghP

**Comment by AVuTuVA** [comment]
@OpticFusion1

**Comment by GC-spigot** [comment]
Resolved next update

**Comment by AVuTuVA** [comment]
@GC-spigot 
error left: https://yaso.su/battepass
