### ISSUE TITLE
Jobs quests not synchronized

### ISSUE THREAD

**Issue by JSN54000** [GC-spigot/battle-pass#302]
### Describe the bug

Hello, I have set up quests using Internal Quest Types "Jobs", more specifically, "jobs_gain_exp" & "jobs_level_up". However, when players level up in their professions, progress is not synced in BattlePass quests, players are still at 0%.

I send you, attached, 2 videos exposing the situation, as well as the configuration file of my job quests.

### How to reproduce

To reproduce the situation, I reset the job quests to be sure, then I simply leveled up the jobs concerned and found that the progress in the battlepass quests was not synchronized.

I provided a GIF showing how to reproduce my situation.

### Screenshots / Videos

![gif jobs quests BattlePass](https://user-images.githubusercontent.com/127223020/223464329-9f856051-1f29-4701-9dc2-6423fbcfec28.gif)
[quests Jobs.txt](https://github.com/GC-spigot/battle-pass/files/10910913/quests.Jobs.txt)

### Server Log

https://mcpaste.io/02ac0d80e6ea8a09

**Comment by KPGTB** [comment]
Hey! I see that jobs plugin, only triggers gain exp event, if you get exp by doing job. When using command, jobs plugin doesn't trigger gain exp event
