### ISSUE TITLE
[Request] Save daily quests in MySQL

### ISSUE THREAD

**Issue by Mithranduil** [GC-spigot/battle-pass#303]
### Describe the feature

it should be possible to synchronize quests per mysql about more than one servers.

so if i start as an player my three dailyquests (1, 2 and 3) on server1, and now switching to server2 (like spawn server and gameserver), my character should has the same three quests, 1, 2 and 3. currently i got random quests on every server, so i start on server1 with quests 1 2 3 and go to server2, i got quests 7 8 9 or something.
that makes it impossible to use battlepass on more than one server

also should it be possible to limit the amount of dailyquests a player can use, because currently they can absolve all of the quests, at the same time - but they should only use 3, for this day, and the next day it should be 3 others

**Comment by KPGTB** [comment]
Feature added - will be available in the next update
