### ISSUE TITLE
MMOCORE, MMOITEMS integrations

### ISSUE THREAD

**Issue by antasetyawan** [GC-spigot/battle-pass#305]
### Describe the quest

can u add MMOCORE and mmoitems Integrations with Battlepass.

Mmocore have Custom Block Mine Event, u can get it on 
https://gitlab.com/phoenix-dvpmt/mmocore/-/blob/master/MMOCore-API/src/main/java/net/Indyuce/mmocore/api/event/CustomBlockMineEvent.java

[Conditional] CustomPlayerFishEvent 
https://gitlab.com/phoenix-dvpmt/mmocore/-/blob/master/MMOCore-API/src/main/java/net/Indyuce/mmocore/api/event/CustomPlayerFishEvent.java

For MMOITEMS
CraftMMOItemEvent
(https://gitlab.com/phoenix-dvpmt/mmoitems/-/blob/master/MMOItems-API/src/main/java/net/Indyuce/mmoitems/api/event/CraftMMOItemEvent.java)

**Comment by Erdi-GitHub** [comment]
MMOCore has already been integrated, but now MMOItems integration has also been added.
Namely, mmoitems_use_station and mmoitems_repair will be present in the next update
