### ISSUE TITLE
Lag with placeholderapi quests while not even being used

### ISSUE THREAD

**Issue by SladeHazard** [GC-spigot/battle-pass#306]
### Describe the bug

Server version: 1.12.2 paper
the plugin causes lag with placeholderapi for no reason, even though I'm not using any placeholderapi quests
can you please add an option to disable this completely or fix the lag?

![image](https://user-images.githubusercontent.com/45261094/225665919-b42e7998-8119-4474-832e-74710b8b1bd8.png)

![image](https://user-images.githubusercontent.com/45261094/225665949-a836a2e3-16da-4cc7-9189-2098e9c5da6f.png)

### How to reproduce

use the plugin on the server with placeholderapi installed

### Screenshots / Videos

n/a

### Server Log

n/a

**Comment by GC-spigot** [comment]
It may be only initializing placeholderapi hence the one lag spike, did you run the server for more than couple of mins?
