### ISSUE TITLE
Battlepass not parsing UI correctly with itemsadder

### ISSUE THREAD

**Issue by Truongvv10** [GC-spigot/battle-pass#308]
### Describe the bug

Just downloaded `IMMERSIVE BATTLEPASS UI ADDON` and saw that the GUI didn't parse the textures correctly. It only shows plain text instead of the texture. 

I have also checked if I uploaded everything correctly, and yes I have. I used papi parse to see if I can see the UI textures.

![image](https://user-images.githubusercontent.com/67742370/226073069-4d784534-1099-46fd-807b-a0f6820211ef.png)

### How to reproduce

![image](https://user-images.githubusercontent.com/67742370/226073362-069bb8eb-b959-4680-99a4-3101683583ea.png)

Using these versions

### Server Log

https://mcpaste.io/6d10d3754a4e393b

**Comment by GC-spigot** [comment]
Hi! contact us via Discord, that's where we'll be able to help best - pack works fine for us! :)
