### ISSUE TITLE
block-place doesn't work with seeds

### ISSUE THREAD

**Issue by dahbawz** [GC-spigot/battle-pass#310]
### Describe the bug

Quest where seeds are planted, don't progress. (block-place)

After debugging with staff in a discord(advanced plugins) ticket, they send me here to report it.

### How to reproduce

  9:
    name: 'Niveau 4 - Farmer III'
    type: block-place
    variable: pumpkin_seeds:0
    required-progress: 30
    points: 9
    item:
      material: pumpkin_seeds:0
      name: '&eNiveau 4 - Farmer III'
      lore:
        - '&7Bouw een pumpkin farm'
        - '&7Door minimaal 30 pumpkin seeds te plaatsen'
        - ''
        - '&7Progress &e%total_progress%&7/&e%required_progress%'
        
          9:
    name: 'Niveau 5 - Farmer IV'
    type: block-place
    variable: beetroot_seeds:0
    required-progress: 30
    points: 9
    item:
      material: BEETROOT:0
      name: '&eNiveau 5 - Farmer IV'
      lore:
        - '&7Maak een beetroot farm met,'
        - '&7minimaal 30 beetroot seeds'
        - ''
        - '&7Progress &e%total_progress%&7/&e%required_progress%'

**Comment by dahbawz** [comment]
Any updates on this?

**Comment by dahbawz** [comment]
Any update on this issue?

**Comment by dahbawz** [comment]
?

**Comment by aXe18** [comment]
Could someone check this ? Me and Jben both tried solve this on ticket, but no luck, even with root and all

**Comment by aXe18** [comment]
+

**Comment by Erdi-GitHub** [comment]
Hi,
block-place uses the block id rather than the item id.

For beetroot, it would be `beetroots`
For wheat, it would be `wheat`
For melons, it would be `melon_stem`
For pumpkins, it would be `pumpkin_stem`
