### ISSUE TITLE
Console spam ! [Tue 10:19:00 WARN  BattlePass] Task #403519 for BattlePass v3.15.7 generated an exception

### ISSUE THREAD

**Issue by WolfLiSteel** [GC-spigot/battle-pass#312]
### Describe the bug

Console spam ! [Tue 10:19:00 WARN  BattlePass] Task #403519 for BattlePass v3.15.7 generated an exception

It doesnt stop.

### How to reproduce

Keeps spamming the console after restart

### Server Log

https://mcpaste.io/452f9683491d522a

**Comment by WolfLiSteel** [comment]
It still keeps spamming this

**Comment by GC-spigot** [comment]
You've had this issue open for 2 days, that is not a long time - we will fix this for next update. Our new developer must have made a mistake, my apologies

> It still keeps spamming this. Will this ever be fixed?
> 
> ! [Thu 07:53:19 WARN BattlePass] Task #10401035 for BattlePass v3.15.7 generated an exception

**Comment by WolfLiSteel** [comment]
I created also a ticket in discord. Look at the log for how much error spam i has in one night.
