### ISSUE TITLE
new command to open menus

### ISSUE THREAD

**Issue by hazexo** [GC-spigot/battle-pass#313]
### Describe the feature

is it possible to add a command like this: /bpa menu open <menu-name> <player-name>
and that will work for every menu of the plugin
like all the weeks
and more

or just make the command /bp menu <menu name> to recognize the quest folder as well

**Comment by SirJben** [comment]
I'll elaborate on his suggestion.
I also like this idea.

So for now, the `bp open <menu name>` command only recognizes the menus in the `menu` folders and not the quest folder. I think it should also work on the quest folder to open a specific week's quest menus.
