### ISSUE TITLE
Brewing potions counting bug

### ISSUE THREAD

**Issue by SirvydasS** [GC-spigot/battle-pass#315]
### Describe the bug

When you brew 3 potions in missions adds only 2 brew

### How to reproduce

Brew potion and take from stand.

### Screenshots / Videos

https://youtu.be/JC299OYiu60

**Comment by RSLuke** [comment]
With some others tests it looks like it progresses the brewed potions by the number of potion in the brewing stand -1
If you brew 1 potion, it doesn't progress, 2 it gives 1 and 3 it gives 2

**Comment by RSLuke** [comment]
Still no updates on a major issue ?

**Comment by Erdi-GitHub** [comment]
I have just fixed this, stay tuned for the next update!
