### ISSUE TITLE
Placeholderapi Lag

### ISSUE THREAD

**Issue by SladeHazard** [GC-spigot/battle-pass#322]
### Describe the bug

the lag from placeholderapi still hasn't been fixed, Im not using placeholders anywhere

![image](https://user-images.githubusercontent.com/45261094/231257177-640878e4-984c-4ddd-a97a-69c327d43fe3.png)

![image](https://user-images.githubusercontent.com/45261094/231258362-bb445a74-8d03-4bbe-b1be-fb1d46917acf.png)

### How to reproduce

install the plugin

**Comment by GC-spigot** [comment]
Those are like 5 tasks, keep the timings / spark running for longer time then post it. If it initializes that's the cause of the spike. You can see the lag comes from papi, not us, just because we initialize it

**Comment by SladeHazard** [comment]
I have many other plugins using placeholderapi perfectly fine, none of them cause lag. and I'm not even using papi with battlepass can't you add a disable option maybe? and I'll keep it running longer and send again, battlepass is always the top consumer

**Comment by GC-spigot** [comment]
Should be resolved
