### ISSUE TITLE
Player can progress the type swim when exploring with a boat

### ISSUE THREAD

**Issue by RSLuke** [GC-spigot/battle-pass#323]
### Describe the bug

With the     type: swim
The play can progress the quest by using a boat

### How to reproduce

  107: # Quest id
    type: swim
    variable: none
    name: "Natation"
    required-progress: 3000
    points: 5
    item:
      material: water_bucket
      name: "&e&lNatation"
      lore:
        - ""

**Comment by GC-spigot** [comment]
Fixed!
