### ISSUE TITLE
Could not pass event CrateOpenEvent to BattlePass v3.16.5

### ISSUE THREAD

**Issue by KalviPL** [GC-spigot/battle-pass#325]
### Describe the bug

I use the ExcellentCrates plugin
And a gamepass problem pops up after opening crates

https://mclo.gs/7gZKbzZ

I am using the latest version of both plugins and server spigot 1.19.4

### How to reproduce

Edit or open chests with ExcellentCrates, then an error pops up with battlepass

### Server Log

https://mclo.gs/a73YNJa

**Comment by dinobossytnew** [comment]
update plugin.
