### ISSUE TITLE
Console Spam from FakePlayers (NPCs etc)

### ISSUE THREAD

**Issue by sarhatabaot** [GC-spigot/battle-pass#335]
### Describe the bug

Error is being spammed in console from BP.

### How to reproduce

1. Install Citizens, Battlepass.
2. Create NPC.
3. Kill NPC.

I tried re-creating it using the steps above but could not do so. 
Still this issue occurs, and did not appear in previous versions.

### Screenshots / Videos

https://pastebin.com/7wudvULY

### Server Log

https://mcpaste.io/31a0c71bf4b60960

**Comment by GC-spigot** [comment]
Should be resolved
