### ISSUE TITLE
Movement quest lag

### ISSUE THREAD

**Issue by SladeHazard** [GC-spigot/battle-pass#341]
### Describe the bug

After some recent update, movement quest now causes lag, can you please tell me which one it is specifically so I can disable it:
![image](https://github.com/GC-spigot/battle-pass/assets/45261094/fa469d41-c592-46ec-8737-7742069abe55)

### How to reproduce

install the plugin with movement quests

**Comment by GC-spigot** [comment]
This doesn't look like much, however I did do some improvements.
