### ISSUE TITLE
Craft quest issue

### ISSUE THREAD

**Issue by naikyys** [GC-spigot/battle-pass#343]
### Describe the bug

You can complete a crafting challenge and you don't even have to craft anything.

### How to reproduce

It's enough to have a full inventory and just click on the item in crafting to sort of put it in the inventory, but since the inventory is full, it can't but the quest is done.

### Screenshots / Videos

https://github.com/GC-spigot/battle-pass/assets/67881641/d6fa72f2-6c24-438b-8f87-a400314e9002

### Server Log

No need log for this error

**Comment by duhneeno** [comment]
I've also experienced an issue with crafting quests, where if a player crafts the required item, once they select the crafted item, they can continue clicking many times without bring the item to their inventory, and each click will count as a new item crafted even tho it is the same item

**Comment by Erdi-GitHub** [comment]
Hi,
This issue was fixed when issue #368 was fixed, and should no longer be an issue in 4.0.0
