### ISSUE TITLE
Contact the plugin programmer

### ISSUE THREAD

**Issue by games4681** [GC-spigot/battle-pass#344]
### Describe the feature

I purchased this plugin: battle pass, recently through stripe for my spigot profile and I did not receive the plugin. I would appreciate it if you could bring it to me manually.
I contacted you here because I was unable to contact you directly at the spigot

**Comment by aXe18** [comment]
> ### Describe the feature
> I purchased this plugin: battle pass, recently through stripe for my spigot profile and I did not receive the plugin. I would appreciate it if you could bring it to me manually. I contacted you here because I was unable to contact you directly at the spigot

You should come our discord for help :)
