### ISSUE TITLE
Placeholder not updating correctly

### ISSUE THREAD

**Issue by Pwnzeye** [GC-spigot/battle-pass#345]
### Describe the bug

The placeholder: %battlepass_time_to_daily_reset% isn't updating live. This wasn't always the case, updates have broke the placeholder so it's stuck in the daily quest GUI. And other people reported that it's not updating if used in other places as well. This is mostly a visual bug, but it makes the battlepass menu to look bugged and is not in line with other plugins where placeholders are updated automatically.

Thank you for looking into this.

### How to reproduce

Using the placeholder: %battlepass_time_to_daily_reset%

**Comment by KPGTB** [comment]
Hey! I can't reproduce that error. Do you have any video or something like that?
