### ISSUE TITLE
ChestShop Bug

### ISSUE THREAD

**Issue by Faln** [GC-spigot/battle-pass#347]
### Describe the bug

Currently the "chestshop_spend" progresses for the seller instead of the intended buyer.

### How to reproduce

Using 1.19.4 mc version with both latest BattlePass and ChestShop. Any quest with "chestshop_spend"

**Comment by Erdi-GitHub** [comment]
I can't replicate this. chestshop_spend seems to progress for the appropriate person. Do you have any videos of this happening?
