### ISSUE TITLE
[Issue] Premium pass wrong tiers

### ISSUE THREAD

**Issue by CallMeIshh** [GC-spigot/battle-pass#35]
**Describe the bug**
When making a tier '2'  (or any other) and opening the bp in-game, it shows tier 2 in slot 1, called tier 2. (so when '3' it shows in slot 2 named tier 3)

**To Reproduce**
Create a tier (only in the premium pass)

**Screenshots / Video**
https://gyazo.com/5021c5320ae6cdf81adf2ecff458fe35

**Server Information (please complete the following information):**
- Server Version: paper-1.16.5-601
- Plugin Version: 3.24

**Comment by GC-spigot** [comment]
This is all related to your slots configuration for rewards menu. Create Tier 1 rewards and change slots to this for example:
```premium-reward-slots:
  slots: '18, 19, 20, 21, 22, 23, 24, 25, 26'```
Or remove slot 18 if you don't want tier 2 to be in the 1st slot
