### ISSUE TITLE
Exclusive Quests are not showing seperate from regular

### ISSUE THREAD

**Issue by iFranticman** [GC-spigot/battle-pass#351]
### Describe the bug

When having the Custom Battlepass UI and the Battlepass plugins. When you set the flag for exclusive it will not put in right area

### How to reproduce

Default config for battlepass show's this just look all of the weekly 1 quests have this issue of not showing exlusive premium quests below

**Comment by KPGTB** [comment]
Hey! Have you copied configs from immersive UI?
