### ISSUE TITLE
getting error on join

### ISSUE THREAD

**Issue by ProtoGhost** [GC-spigot/battle-pass#353]
### Describe the bug

04.06 05:03:42 [Server] INFO [AltDetector] 0_ProtoGhost may be an alt of 0_ProtoGhost
04.06 05:03:43 [Server] WARN [BattlePass] Task #204 for BattlePass v3.17.3 generated an exception
04.06 05:03:43 [Server] INFO java.lang.NullPointerException: Cannot invoke "io.github.battlepass.objects.user.User.getQuestStore()" because "<parameter1>" is null
04.06 05:03:43 [Server] INFO at io.github.battlepass.controller.QuestController.lambda$new$0(QuestController.java:16) ~[battle-pass-3.17.3.jar:?]
04.06 05:03:43 [Server] INFO at io.github.battlepass.controller.QuestController.failedIndex(QuestController.java:101) ~[battle-pass-3.17.3.jar:?]
04.06 05:03:43 [Server] INFO at io.github.battlepass.controller.QuestController.getQuestProgress(QuestController.java:55) ~[battle-pass-3.17.3.jar:?]
04.06 05:03:43 [Server] INFO at io.github.battlepass.quests.workers.pipeline.steps.QuestValidationStep.proceed(QuestValidationStep.java:96) ~[battle-pass-3.17.3.jar:?]
04.06 05:03:43 [Server] INFO at io.github.battlepass.quests.workers.pipeline.steps.QuestValidationStep.processCompletion(QuestValidationStep.java:88) ~[battle-pass-3.17.3.jar:?]
04.06 05:03:43 [Server] INFO at io.github.battlepass.quests.workers.pipeline.QuestPipeline.handle(QuestPipeline.java:51) ~[battle-pass-3.17.3.jar:?]
04.06 05:03:43 [Server] INFO at io.github.battlepass.quests.service.executor.QuestExecutionBuilderImpl.buildAndExecute(QuestExecutionBuilderImpl.java:34) ~[battle-pass-3.17.3.jar:?]
04.06 05:03:43 [Server] INFO at io.github.battlepass.quests.quests.external.executor.ExternalQuestExecutor.execute(ExternalQuestExecutor.java:53) ~[battle-pass-3.17.3.jar:?]
04.06 05:03:43 [Server] INFO at io.github.battlepass.quests.quests.external.executor.ExternalQuestExecutor.execute(ExternalQuestExecutor.java:58) ~[battle-pass-3.17.3.jar:?]
04.06 05:03:43 [Server] INFO at io.github.battlepass.quests.quests.external.executor.ExternalQuestExecutor.execute(ExternalQuestExecutor.java:63) ~[battle-pass-3.17.3.jar:?]
04.06 05:03:43 [Server] INFO at io.github.battlepass.quests.quests.external.executor.ExternalQuestExecutor.execute(ExternalQuestExecutor.java:42) ~[battle-pass-3.17.3.jar:?]
04.06 05:03:43 [Server] INFO at io.github.battlepass.quests.quests.external.PlaceholderApiQuests.lambda$placeholderRun$2(PlaceholderApiQuests.java:51) ~[battle-pass-3.17.3.jar:?]
04.06 05:03:43 [Server] INFO at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.19.4.jar:git-Purpur-1980]
04.06 05:03:43 [Server] INFO at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[purpur-1.19.4.jar:git-Purpur-1980]
04.06 05:03:43 [Server] INFO at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1510) ~[purpur-1.19.4.jar:git-Purpur-1980]
04.06 05:03:43 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:488) ~[purpur-1.19.4.jar:git-Purpur-1980]
04.06 05:03:43 [Server] INFO at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1424) ~[purpur-1.19.4.jar:git-Purpur-1980]
04.06 05:03:43 [Server] INFO at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1195) ~[purpur-1.19.4.jar:git-Purpur-1980]
04.06 05:03:43 [Server] INFO at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:325) ~[purpur-1.19.4.jar:git-Purpur-1980]
04.06 05:03:43 [Server] INFO at java.lang.Thread.run(Thread.java:833) ~[?:?]

### How to reproduce

04.06 05:03:42 [Server] INFO [AltDetector] 0_ProtoGhost may be an alt of 0_ProtoGhost
04.06 05:03:43 [Server] WARN [BattlePass] Task #204 for BattlePass v3.17.3 generated an exception
04.06 05:03:43 [Server] INFO java.lang.NullPointerException: Cannot invoke "io.github.battlepass.objects.user.User.getQuestStore()" because "<parameter1>" is null
04.06 05:03:43 [Server] INFO at io.github.battlepass.controller.QuestController.lambda$new$0(QuestController.java:16) ~[battle-pass-3.17.3.jar:?]
04.06 05:03:43 [Server] INFO at io.github.battlepass.controller.QuestController.failedIndex(QuestController.java:101) ~[battle-pass-3.17.3.jar:?]
04.06 05:03:43 [Server] INFO at io.github.battlepass.controller.QuestController.getQuestProgress(QuestController.java:55) ~[battle-pass-3.17.3.jar:?]
04.06 05:03:43 [Server] INFO at io.github.battlepass.quests.workers.pipeline.steps.QuestValidationStep.proceed(QuestValidationStep.java:96) ~[battle-pass-3.17.3.jar:?]
04.06 05:03:43 [Server] INFO at io.github.battlepass.quests.workers.pipeline.steps.QuestValidationStep.processCompletion(QuestValidationStep.java:88) ~[battle-pass-3.17.3.jar:?]
04.06 05:03:43 [Server] INFO at io.github.battlepass.quests.workers.pipeline.QuestPipeline.handle(QuestPipeline.java:51) ~[battle-pass-3.17.3.jar:?]
04.06 05:03:43 [Server] INFO at io.github.battlepass.quests.service.executor.QuestExecutionBuilderImpl.buildAndExecute(QuestExecutionBuilderImpl.java:34) ~[battle-pass-3.17.3.jar:?]
04.06 05:03:43 [Server] INFO at io.github.battlepass.quests.quests.external.executor.ExternalQuestExecutor.execute(ExternalQuestExecutor.java:53) ~[battle-pass-3.17.3.jar:?]
04.06 05:03:43 [Server] INFO at io.github.battlepass.quests.quests.external.executor.ExternalQuestExecutor.execute(ExternalQuestExecutor.java:58) ~[battle-pass-3.17.3.jar:?]
04.06 05:03:43 [Server] INFO at io.github.battlepass.quests.quests.external.executor.ExternalQuestExecutor.execute(ExternalQuestExecutor.java:63) ~[battle-pass-3.17.3.jar:?]
04.06 05:03:43 [Server] INFO at io.github.battlepass.quests.quests.external.executor.ExternalQuestExecutor.execute(ExternalQuestExecutor.java:42) ~[battle-pass-3.17.3.jar:?]
04.06 05:03:43 [Server] INFO at io.github.battlepass.quests.quests.external.PlaceholderApiQuests.lambda$placeholderRun$2(PlaceholderApiQuests.java:51) ~[battle-pass-3.17.3.jar:?]
04.06 05:03:43 [Server] INFO at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.19.4.jar:git-Purpur-1980]
04.06 05:03:43 [Server] INFO at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[purpur-1.19.4.jar:git-Purpur-1980]
04.06 05:03:43 [Server] INFO at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1510) ~[purpur-1.19.4.jar:git-Purpur-1980]
04.06 05:03:43 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:488) ~[purpur-1.19.4.jar:git-Purpur-1980]
04.06 05:03:43 [Server] INFO at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1424) ~[purpur-1.19.4.jar:git-Purpur-1980]
04.06 05:03:43 [Server] INFO at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1195) ~[purpur-1.19.4.jar:git-Purpur-1980]
04.06 05:03:43 [Server] INFO at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:325) ~[purpur-1.19.4.jar:git-Purpur-1980]
04.06 05:03:43 [Server] INFO at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by GC-spigot** [comment]
Fixed!
