### ISSUE TITLE
Towny Advanced block break event priority bug

### ISSUE THREAD

**Issue by Truongvv10** [GC-spigot/battle-pass#354]
### Describe the bug

When people try and do quest for example harvesting crops, people are able to complete the quest super fast by breaking crops in a town claim that's not theirs. 

It cancels them breaking the crop but it counts in the battlepass... please fix MAJOR ISSUE

### How to reproduce

Have towny advanced and battlepass plugin installed, let someone make a town and you try breaking blocks (pref crops) there as a non town member while quest is active

### Screenshots / Videos

![image](https://github.com/GC-spigot/battle-pass/assets/67742370/7378e74a-29e1-4e37-80e0-52d7fdb243bb)
![image](https://github.com/GC-spigot/battle-pass/assets/67742370/c78b7c07-d603-4b93-9e8a-fe8414c56e38)
![image](https://github.com/GC-spigot/battle-pass/assets/67742370/49aaac13-5609-492d-bbb0-bf92efb9b0f8)

**Comment by Truongvv10** [comment]
![image](https://github.com/GC-spigot/battle-pass/assets/67742370/42b7b74e-0e6b-4054-ba62-9f977f21bdb5)
/paper dumplisteners org.bukkit.event.block.BlockBreakEvent

**Comment by Erdi-GitHub** [comment]
This is an issue with the harvest-crops quest rather than with blocks in general (block-break)
This should be fixed in the next update!
