### ISSUE TITLE
Custom Model Data removed on quest completion

### ISSUE THREAD

**Issue by Nissimmizrachi** [GC-spigot/battle-pass#357]
### Describe the bug

when you complete a quest and you have the glow on completion set to on, the custom model data of the quest item is getting removed.

### How to reproduce

just put a model data to one of the quest item, make sure you have the glow option on in settings.yml
complete the quest, and you should see the original item without the modeldata

### Screenshots / Videos

![Screenshot_1](https://github.com/GC-spigot/battle-pass/assets/64379390/e748877f-27f0-40b6-9b31-d1594cf99e4b)

### Server Log

https://mcpaste.io/b3aa9619bc28cd2f

**Comment by GC-spigot** [comment]
Change `completionCustomModelData` as well in settings.yml, but for next update it should be resolved
