### ISSUE TITLE
honey-comb-extract not working

### ISSUE THREAD

**Issue by Superalex0102** [GC-spigot/battle-pass#361]
### Describe the bug

honey-comb-extract doesn't count the extraction

  2: # Quest id
    name: 'Hét - 4' # The name given to the quest.
    type: honey-comb-extract # The type of quest
    variable: 'bee_nest' # The block the player must break.
    required-progress: 20 # The amount of times the player should break the coal ore block.
    points: 150 # The amount of points that will be rewarded
    item: # The item that will be displayed in menus.
      material: bee_nest
      amount: 1
      name: '&e&lQUEST: &fMéh'
      lore:
        - ' &8» &7Gyűjts be &e20x méhsejtet'
        - ''
        - '&e&lINFORMÁCIÓ:'
        - ' &8» &7Típus: &fIngyenes'
        - ' &8» &7Pont: &f150'
        - ' &8» &7Teljesítmény: &a%percentage_progress%'

### How to reproduce

Version: 3.17.8

**Comment by GC-spigot** [comment]
Variable should be: `BEEHIVE` as that is the material for bee hive block

**Comment by Superalex0102** [comment]
I want it to be extracted from Bee Nest, not from bee hive

**Comment by Superalex0102** [comment]
@GC-spigot
