### ISSUE TITLE
Craft bug instead of 64 offsets only 64

### ISSUE THREAD

**Issue by SirvydasS** [GC-spigot/battle-pass#362]
### Describe the bug

When you craft Mud Bricks with 4x64 ant take crafted items with shift it only shows that you crafted 64 instead of 256.

### How to reproduce

1. Put in crafting table 256 packed mud.
2. Take mud bricks from craft.

### Screenshots / Videos

https://youtu.be/JDJbEVszkzs

**Comment by Erdi-GitHub** [comment]
Recently fixed (#368) in v4.0.0
