### ISSUE TITLE
MySQL synchronization player data loss

### ISSUE THREAD

**Issue by MuMuMuCODE** [GC-spigot/battle-pass#363]
### Describe the bug

MySQL synchronization player data loss.

### How to reproduce

After MySQL is enabled
The player's point/level data probability is lost when switching servers for many times and obtaining points
Both battle-pass-3.17.0 - 3.17.9

In configuration file
Bungee fix: true and bungee fix: false
All tried
All have this serious problem

Server Version: [ purpur-1.18.2 ]

### Screenshots / Videos

`[10:06:28 WARN]: [BattlePass] Task #90 for BattlePass v3.17.0 generated an exception java.lang.NullPointerException: Cannot invoke "io.github.battlepass.objects.user.User.getQuestStore()" because "<parameter1>" is null         at io.github.battlepass.controller.QuestController.lambda$new$0(QuestController.java:16) ~[battle-pass-3.17.0.jar:?]         at io.github.battlepass.controller.QuestController.failedIndex(QuestController.java:101) ~[battle-pass-3.17.0.jar:?]         at io.github.battlepass.controller.QuestController.getQuestProgress(QuestController.java:55) ~[battle-pass-3.17.0.jar:?]         at io.github.battlepass.quests.workers.pipeline.steps.QuestValidationStep.proceed(QuestValidationStep.java:96) ~[battle-pass-3.17.0.jar:?]         at io.github.battlepass.quests.workers.pipeline.steps.QuestValidationStep.processCompletion(QuestValidationStep.java:88) ~[battle-pass-3.17.0.jar:?]         at io.github.battlepass.quests.workers.pipeline.QuestPipeline.handle(QuestPipeline.java:47) ~[battle-pass-3.17.0.jar:?]         at io.github.battlepass.quests.service.executor.QuestExecutionBuilderImpl.buildAndExecute(QuestExecutionBuilderImpl.java:34) ~[battle-pass-3.17.0.jar:?]         at io.github.battlepass.quests.quests.internal.PlayTimeQuest.lambda$run$0(PlayTimeQuest.java:21) ~[battle-pass-3.17.0.jar:?]         at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.18.2.jar:git-Purpur-1632]         at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[purpur-1.18.2.jar:git-Purpur-1632]         at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1559) ~[purpur-1.18.2.jar:git-Purpur-1632]         at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:522) ~[purpur-1.18.2.jar:git-Purpur-1632]         at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1483) ~[purpur-1.18.2.jar:git-Purpur-1632]         at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1247) ~[purpur-1.18.2.jar:git-Purpur-1632]         at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:321) ~[purpur-1.18.2.jar:git-Purpur-1632]         at java.lang.Thread.run(Thread.java:1589) ~[?:?]`

**Comment by GC-spigot** [comment]
Alreaday resolved
