### ISSUE TITLE
Doesn't count sniffer breed quest

### ISSUE THREAD

**Issue by SirvydasS** [GC-spigot/battle-pass#364]
### Describe the bug

When breeding sniffers, doesn't count in the quest.

### How to reproduce

Make the quest with breed:
`quests:
  1:
    name: 'Sniffer breed'
    type: breed
    variable: sniffer
    required-progress: 1
    points: 5
    item:
      material: sniffer_egg:0
      amount: 1
      name: '&eSniffer breed'
      lore:
        - '&7Apvaistinti Sniffer!'
        - ''
        - '&e%total_progress%&7/&e%required_progress%'
        - '%progress_bar% &7(&a%percentage_progress%&7)'`
        
        and then breed sniffers with the  Torchflower seed.

**Comment by Erdi-GitHub** [comment]
This should be fixed in the next update!
