### ISSUE TITLE
Random picking weekly quests

### ISSUE THREAD

**Issue by anhcraft** [GC-spigot/battle-pass#366]
### Describe the feature

Using a custom tool, my server achieves hundreds of procedural quests. Unlike daily quests which allow for setting limit, weekly quests will load all of them. I would like to have a similar option to `daily-quest-amount`. 

**Example how the feature works in detail:**
- When a season starts, randomize and pick quests from four weekly quest files: week-1-quests.yml, week-2-quests.yml, etc
- The setting `weekly-quest-amount` refers to each weekly quest file
- Selected quests are saved and remain until the season ends (e.g if we update the quest pool in the middle of the season, it will not cause any issues)

**Further improvements:**
- Separate limit for free and premium passes? e.g: free pass can do certain X daily quests and Y weekly quests, while premium pass can do up to M daily quests and N weekly quests

**Comment by KPGTB** [comment]
Hey! I added this feature. It will be available in the next update
