### ISSUE TITLE
Brew Quest

### ISSUE THREAD

**Issue by RWslayer** [GC-spigot/battle-pass#367]
### Describe the bug

Variable: REGENERATION not working

variable: SPEED is working

### How to reproduce

set variable to REGENERATION

### Screenshots / Videos

![Capture](https://github.com/GC-spigot/battle-pass/assets/124497848/bf07484b-910a-424c-a37a-ea8672cffe81)

**Comment by GC-spigot** [comment]
There's a space before `REGENERATION` word, have you tried removing that and seeing if issue is fixed?

**Comment by RWslayer** [comment]
> There's a space before `REGENERATION` word, have you tried removing that and seeing if issue is fixed? There's no difference internally between those two

Yes we have tried that. Still doesn't seem to be working.

**Comment by Erdi-GitHub** [comment]
`REGENERATION` isn't a valid potion type internally, you have to replace it with `REGEN` instead:
```yaml
    type: brew
    variable: REGEN
```
