### ISSUE TITLE
Bug with craft 

### ISSUE THREAD

**Issue by Distolfix** [GC-spigot/battle-pass#368]
### Describe the bug

I would like to report a critical bug that I encountered using the Battlepass plugin in the Craft module.

When performing a crafting mission, for example crafting 300 rails, and using the combination of SHIFT + LEFT CLICK to pick up the entire stack of crafted rails, the count is not performed correctly. This error also occurs when creating signs, so it seems to be a general problem with the count of crafted products when using the aforementioned key combination.

As a result, users are forced to pick up one item at a time to ensure the count is correct. This is obviously not ideal and causes considerable frustration.

I kindly ask you to investigate this issue and resolve it as promptly as possible. It appears to be a widespread issue with the Craft module in the Battlepass plugin and therefore requires your immediate attention.

Thank you in advance for your support and attention to this issue. I am waiting for your response.

### How to reproduce

Using crafting table

**Comment by Erdi-GitHub** [comment]
Fixed
