### ISSUE TITLE
Quests are not completing

### ISSUE THREAD

**Issue by daniel-skopek** [GC-spigot/battle-pass#372]
### Describe the bug

Quests are not completing with BattlePass 3.18.0 when using MySQL.

### How to reproduce

1. Use BattlePass 3.18.0
2. Set up MySQL
3. No quest can be completed (no progress)

**Comment by thiagogebrimm** [comment]
Same problem

**Comment by Erdi-GitHub** [comment]
Hi,
I cannot replicate this using 3.19.1. Do you still have this issue in 3.19.1?

**Comment by Erdi-GitHub** [comment]
> I think it's fixed in the latest version.

Alright, thank you for your response. In that case, I will be closing this issue
