### ISSUE TITLE
Server Crash

### ISSUE THREAD

**Issue by daniel-skopek** [GC-spigot/battle-pass#373]
### Describe the bug

When I use BattlePass version 3.18.0 and a few players connect, the server freeze and crashes after a player connects.

### How to reproduce

Use BattlePass 3.18.0

### Server Log

https://pastebin.com/raw/DPYxkSb2

**Comment by valeriorobert** [comment]
Same here, I think the problem in my case is that BattlePass isn't compatible with PlotSquared v7

https://pastebin.com/S5s2kfSm

I opened a post into the Discord Forum too

**Comment by SirvydasS** [comment]
SAME. :(
https://pastebin.com/DNqnmcrV

**Comment by GC-spigot** [comment]
@SirvydasS @daniel-skopek @valeriorobert Are any of you using MySQL for battlepass?

**Comment by SirvydasS** [comment]
No,
storage-method: JSON

**Comment by GC-spigot** [comment]
Gonna be posting an update in couple of minutes, please try it out and let me know if this resolves all issues for you

**Comment by valeriorobert** [comment]
> @SirvydasS @daniel-skopek @valeriorobert Are any of you using MySQL for battlepass? 

I m using Json.

Unlike other 2 guys when I use battlePass in a fresh server  1.20.1 Paper (just with chat control, featherboard,cmi and mycommand) it works without problem.
I have problem only with the server with Plots squared v7 in 1.20.1.

**Comment by valeriorobert** [comment]
The 3.18.1 fixed for me

**Comment by GC-spigot** [comment]
Considering this fixed!
