### ISSUE TITLE
Chat quests not working

### ISSUE THREAD

**Issue by Parlamentum** [GC-spigot/battle-pass#376]
### Describe the bug

The chat quest doesn't progress when i write on chat

### How to reproduce

Just using Battlepass 3.18.0 create a chat quest and try to complete it

**Comment by GC-spigot** [comment]
![image](https://github.com/GC-spigot/battle-pass/assets/13188801/abdb334d-b1f7-4df4-9074-d7bb8ac677cd)
This is from the default quests, it's working fine. Try updating to 3.18.2
