### ISSUE TITLE
Custom model doesn't work

### ISSUE THREAD

**Issue by Parlamentum** [GC-spigot/battle-pass#377]
### Describe the bug

in some of the items in the quests, the model data is not shown on the item and instead i see it as a normal item.
tried to find the reason but couldn't, i just have some items working fine and others not despite the configuration being the exact same.

### How to reproduce

here is an example of an item that doesn't work. and yes i checked that the model data is correct.
`  3:`
`    name: 'test'`
`    type: placeholderapi_match_player_has_permission_misteryman`
`    required-progress: 1`
`    variable: 'yes'`
`    points: 10`
`    item:`
`      material: paper`
`      customModelData: 10187`
`      amount: 1`
`      name: '&etest'`
`      lore:`
`        - '&7test'`

**Comment by Timoti11** [comment]
me too...

**Comment by Timoti11** [comment]
> Hey! I can't reproduce that problem (also when using your config). Are you sure that resource pack with model is configured correctly?

Yes, in my case rp is ok and I can easy take it with help of commands like `/give paper ...`, and then I use it in my quests it works fine few moment, but every time (or day, or progress idk) it lost... My custom items drops for fedault paper, and I can't fix it - only recreate ID of quest
