### ISSUE TITLE
jobs_gain_exp doesn't work properly

### ISSUE THREAD

**Issue by WhatsTheBadNews** [GC-spigot/battle-pass#378]
### Describe the bug

The wiki claims that for the jobs_gain_exp quest "progress is the exp gained". However, this is not the case. It seems that only 1 progress is awarded each time Jobs Exp is gained.

### How to reproduce

1.) Make a quest for jobs_gain_exp
2.) Earn EXP from a job with 1 action
3.) See that you only gained 1 progress in the quest instead of the amount of Jobs EXP you gained

**Comment by Erdi-GitHub** [comment]
This should now be fixed, stay tuned for the next update!
