### ISSUE TITLE
MySQL error

### ISSUE THREAD

**Issue by Toki-teki** [GC-spigot/battle-pass#38]
Hello. I have this error. How to fix?
https://pastebin.com/ccSLVef9
My login details are 100% correct

**Comment by GC-spigot** [comment]
Try updating to 3.30 and let me know if it helps.

**Comment by Toki-teki** [comment]
When I download the latest version from your site, the jar is called 1.30. But the console shows that it is version 1.29 you may have loaded the wrong jar)

**Comment by GC-spigot** [comment]
Yes, sorry about that. Try now and let me know if it works. PaperSpigot and Spigot keep switching their mysql providers and causes chaos this way.

**Comment by Toki-teki** [comment]
Okay. I can do it in about 8 hours

**Comment by Toki-teki** [comment]
Yes. This work
Thanl u :)

**Comment by Toki-teki** [comment]
hello. Errors back on 1.16.5

**Comment by Toki-teki** [comment]
https://pastebin.com/hXvFFcJH

**Comment by Toki-teki** [comment]
Perhaps you should take full control of the MySQL connection so that the plugin connection does not depend on the core code.
