### ISSUE TITLE
Kill Aura completes quests over and over again

### ISSUE THREAD

**Issue by iFranticman** [GC-spigot/battle-pass#380]
### Describe the bug

When a  user is using their sword and they have kill aurora from advanced enchantments plugins
They get rewarded many times for the quests

### How to reproduce

When a  user is using their sword and they have kill aurora from advanced enchantments plugins
They get rewarded many times for the quests
Have the sword in hand when you are about to do the quest and player can kill mobs in mass amounts to complete quests

### Screenshots / Videos

1:
    type: kill-mob
    variable: none
    name: 'Daily - Pure Killer'
    required-progress: 20
    points: 50
    item:
      material: zombie_spawn_egg
      name: '&a&lQUEST: &fPure Killer'
      lore:
        
'&8 » &7To complete this quest, you must'
'&8 » &7murder 20 mobs of any kind.'
''
'&a&lINFORMATION'
'&8 » &7Points: &f50x'
'&8 » &7Battlepass: &fFree'
'&8 » &7Progress: &a%total_progress%&8/&c%required_progress%'

**Comment by WhatsTheBadNews** [comment]
We have a similar issues with kill-mob quest, we are also using advanced enchantment.

![image](https://github.com/GC-spigot/battle-pass/assets/29821149/1c714206-171c-43af-9c5f-6ac21368563c)
