### ISSUE TITLE
Incorrect Reward Item Amount

### ISSUE THREAD

**Issue by duhneeno** [GC-spigot/battle-pass#381]
### Describe the bug

One of my rewards is a stack of emerald blocks. But when players claim the reward they do not get the full stack.

Here is the yaml from rewards.yaml

`'5':
  type: item
  lore-addon:
    - ' &fStack of Emerald Blocks!'
  items: 
    '1':
      material: emerald_block 
      amount: 64 `

### How to reproduce

Use 64 emerald blocks as a reward. Claim reward and you wont get all 64

**Comment by sennby** [comment]
fix this its been months.. for real.

**Comment by GC-spigot** [comment]
@sennby @duhneeno I can't recreate this issue, can one of you record a video with this? Also send your BattlePass folder zipped so I can drag and drop this.

**Comment by Erdi-GitHub** [comment]
I cannot seem to replicate this, either... for me, it works on both Paper and Spigot, on both extreme ends of versions (1.8.8 and 1.20.1)
My best guess is a plugin incompatibility, or configuration mishap. @duhneeno / @sennby do you still have this issue? If so, can you send your plugin list and the BattlePass folder?

**Comment by haroldrc** [comment]
same problem

**Comment by Erdi-GitHub** [comment]
> same problem
Could you attach your BattlePass folder, zipped? What's your server software and version?

**Comment by KPGTB** [comment]
Hey! I can't reproduce that problem. Can you send tiers & rewards configuration? Also you can attach a video of that problem
