### ISSUE TITLE
Players can re-claim premium rewards after getting pass again

### ISSUE THREAD

**Issue by LordYarkan** [GC-spigot/battle-pass#383]
### Describe the bug

Hi
i had configured a permission for the battle pass, and when i give the permission to the player he claims all the prizes. then i remove the permission and the whole premium row is blocked and when i give him back the permission he can claim all the prizes again. can i avoid that?

### How to reproduce

The problem that every time they buy pass they can claim all the rewards again from the premium queue.

**Comment by KPGTB** [comment]
Hey! This issue is a duplication of #285 . Problem has been fixed. It will be available in the next update
