### ISSUE TITLE
Bugged Quests

### ISSUE THREAD

**Issue by razzeking** [GC-spigot/battle-pass#384]
### Describe the bug

the quest _Griefer_ **place 3 lava buckets** does not work on our server, one other player reported an issue with the quest _Blacksmith_ **craft 4 swords of any material.** im not sure how that glitch work but he was able to complete the quest by clicking in the crafting slots and then completing the without crafting all 4

### How to reproduce

when i tried to test this, i gave myself 9 iron, crafted 3 buckets, went and picked up natuarlly spawned lava, then placed it, as for blacksmith im not sure, but i quote what our player said, as thats all info i got on this atm "when you have to complete the mission blacksmith make 4 equal swords you can just click in the craft box without it costing materials and you still get progress"

### Screenshots / Videos

https://github.com/GC-spigot/battle-pass/assets/47952472/fd818e20-d51c-4e19-bf19-dd85b44cea2f

### Server Log

https://mcpaste.io/4bdbe6aca6d10de1

**Comment by GC-spigot** [comment]
Looking into this!

**Comment by GC-spigot** [comment]
So for lava quests, if you are using default quests you'll need to just simply regenerate your default quest files for next update and this will be resolved, otherwise change your lava bucket quest to this:
```yaml
  18: # Quest id
    type: bucket-place
    variable: lava_bucket
    name: 'Griefer'
    required-progress: 3
    points: 10
    item:
      material: lava_bucket
      name: '&eGriefer'
      lore:
        - '&7To complete this quest, you must'
        - '&7place 3 lava buckets'
        - ''
        - '&7(&a%percentage_progress%&7)'
