### ISSUE TITLE
cratereloaded_open quest doesn't work

### ISSUE THREAD

**Issue by WhatsTheBadNews** [GC-spigot/battle-pass#386]
### Describe the bug

`[BattlePass] Failed to register events for class io.github.battlepass.quests.quests.external.CrateReloadedQuests because com/hazebyte/crate/api/event/RewardReceiveEvent does not exist.`

### How to reproduce

1.) Try to make a cratereloaded_open quest

2.) Get this error on startup:
`[BattlePass] Failed to register events for class io.github.battlepass.quests.quests.external.CrateReloadedQuests because com/hazebyte/crate/api/event/RewardReceiveEvent does not exist.`

**Comment by GC-spigot** [comment]
Resolved!
