### ISSUE TITLE
Bug with BattlePass UI (hosting with bisect server hosting)

### ISSUE THREAD

**Issue by 5tartv** [GC-spigot/battle-pass#387]
### Describe the bug

I am using the wiki video to install the UI using oraxen. The oraxen portion of the file seems to be working. However when I put the BattlePass config files into the plug-in folder it gives me this message when restarting the server. Would love any and all help!

### How to reproduce

Followed the instructions on the wiki on how to install the BattlePass UI. Tried many times and have been getting this error message in console. BattlePass stops working when I drag files from BattlePass config (for oraxen) into the BattlePass plug-in folder 

### Screenshots / Videos

![Screenshot_2023-07-23_151251](https://github.com/GC-spigot/battle-pass/assets/139995555/31dc4e70-5378-4df4-9661-4da453d68970)

**Comment by KPGTB** [comment]
Join our discord to get help with installation
