### ISSUE TITLE
placeholder integer warn (prossibly simple fix)

### ISSUE THREAD

**Issue by austv** [GC-spigot/battle-pass#388]
### Describe the bug

I have a plugin that uses placeholderapi to make variables. And sometimes this variables is set in float format (1.0).
When this happens, we have this bug: https://mclo.gs/L4uga0h when using **`placeholderapi_integer_placeholder`** quest type.

### How to reproduce

1. Have some float placeholder
2. Create a placeholderapi_integer_placeholder quest about this placeholder. You can use **%player_health%**
3. Wait until the message on console. I have lots of players so the console is spamming for me

### Server Log

https://mclo.gs/L4uga0h

**Comment by GC-spigot** [comment]
Resolved next update
