### ISSUE TITLE
Model data still dissapears in quests

### ISSUE THREAD

**Issue by Parlamentum** [GC-spigot/battle-pass#389]
### Describe the bug

Model data dissapears from items after completing the quest.
I'm using the latest plugin version (3.18.5) in which this issue should be fixed but it is still happening.

### How to reproduce

This the configuration of one of the quests
  5:
    name: 'I שבוע 1 - מצביען' # The name given to the quest.
    type: votifier_vote
    variable: none
    required-progress: 4
    points: 15
    item:
      material: brick
      customModelData: 194
      name: '&eI מצביען'
      lore:
        - '&7תצביע לשרת &e4'
        - '&7פעמים'
        - ''
        - '&7נקודות: 15'
        - '%progress_bar% &7(&a%percentage_progress%&7)'

### Screenshots / Videos

Here are the quests items before and after completion
https://i.imgur.com/kLYeFT1.png
https://i.imgur.com/2XoOJ0n.png

**Comment by Parlamentum** [comment]
Still happens in version 3.18.6 of the plugin.

**Comment by SirJben** [comment]
Disable `quest-glow-on-completion: true` on settings.yml
