### ISSUE TITLE
Fishing mission won't work property

### ISSUE THREAD

**Issue by SirvydasS** [GC-spigot/battle-pass#392]
### Describe the bug

When the mission is to fish COD, when you catch the random item it counts like you catched the COD. No problem when you catch other fish.

### How to reproduce

`  8:
    name: 'Žvejyba'
    type: fish
    variable: cod
    required-progress: 64
    points: 4
    item:
      material: raw_cod:0
      amount: 1
      name: '&eŽvejyba'
      lore:
        - '&7Pagauti raw cod!'
        - ''
        - '&e%total_progress%&7/&e%required_progress%'
        - '%progress_bar% &7(&a%percentage_progress%&7)'`

### Screenshots / Videos

https://medal.tv/games/minecraft/clips/1naDtnN7dE_hfQ/9Zeu4g7hAFw7?invite=cr-MSwzeFMsNDkzMjA5MjEs

**Comment by Erdi-GitHub** [comment]
What version of BattlePass do you have installed? I cannot replicate this in 3.19.1

**Comment by SirvydasS** [comment]
Using 4.0.7.
Have bug agian:
https://streamable.com/igk33c
https://streamable.com/hbowfa

This bug works with pufferfish too.

Maybe this bug relates to mcMMO, because these items from that plugin

**Comment by SirvydasS** [comment]
@Erdi-GitHub maybe can you reopen the issue, because there is definitely an bug.
