### ISSUE TITLE
CratesReloaded quests not working

### ISSUE THREAD

**Issue by BorisOZ** [GC-spigot/battle-pass#395]
### Describe the bug

Any quests using the CratesReloaded plugin do not appear to be working. Console says "Failed to register events"

### How to reproduce

Have BattlePass and CratesReloaded plugin on the server
Create a CratesReloaded quest
Open corresponding key/crate, nothing is tracked

### Server Log

https://mcpaste.io/351a8e10f6c7c4a7

**Comment by GC-spigot** [comment]
Resolved!
