### ISSUE TITLE
Placeholders are not working in the lore of rewards

### ISSUE THREAD

**Issue by Verzante** [GC-spigot/battle-pass#396]
### Describe the bug

Using PAPI Placeholders in lores of the rewards are simply not parsing. On discord support I was told this is supposed to work so thats why I am reporting this bug. No errors in the console.

Battlepass version: 3.18.7

### How to reproduce

To reproduce this is simple, just put any placeholder in the lore of the rewards. Below are images and a video of me showing it:

### Screenshots / Videos

**----------------------------------------------------**
**VIDEO LINK:** https://imgur.com/a/5HDOSQE
**----------------------------------------------------**
![image](https://github.com/GC-spigot/battle-pass/assets/81901320/ded424fb-5f49-4f50-b943-25ed1e15acb5)
![image](https://github.com/GC-spigot/battle-pass/assets/81901320/5a7ba37b-6fba-4f15-b648-d19a5aba2fdc)

**Comment by KPGTB** [comment]
Hey! Problem has been fixed. It will be available in the next update
