### ISSUE TITLE
Cant translate message ("There have been some quests that have reset")

### ISSUE THREAD

**Issue by SirvydasS** [GC-spigot/battle-pass#397]
### Describe the bug

Can't found where translate this message.
"There have been some quests that have reset"

### How to reproduce

Wait when refreshing daily mission

### Screenshots / Videos

https://cdn.discordapp.com/attachments/1139605911057469492/1139605969215692911/image.png

**Comment by Erdi-GitHub** [comment]
I can't replicate this. Do you still have this issue in the latest version?

**Comment by SirvydasS** [comment]
This is fixed, thanks
