### ISSUE TITLE
cant make a button that bring me to week quest

### ISSUE THREAD

**Issue by OnlyLemons** [GC-spigot/battle-pass#398]
### Describe the bug

i can make a button that do that
'[menu] {daily-quests}'

but i cant do it with week 
'[menu] {week}'

i tried to add a fast button for week quest inside the daily quest but dont work

### How to reproduce

( plugins/BattlePass/menus/daily-quests.yml )

menu-title: '<shift:-64> <glyph:lemon_gui_battlepass_quest_daily>'
menu-rows: 3

quest-slots:
  slots: '1...7'
menu:
  '21':
    item:
      material: yellow_dye
      customModelData: 56
      name: '&aDaily Quests &7(%daily_time_left%)'
  '23':
    item:
      material: yellow_dye
      customModelData: 57
      name: '&6Weekly Quests'
    actions:
      - '[menu] {week}'
      - '[sound] {UI_BUTTON_CLICK:1:2}'

### Server Log

no errors

**Comment by Timoti11** [comment]
up

**Comment by KPGTB** [comment]
Hey! To make a button that opens weeks menu, you should use `{quest-overview}` instead of `{week}`
