### ISSUE TITLE
Quests Beyond Week 7 are hidden in Immersive UI

### ISSUE THREAD

**Issue by duhneeno** [GC-spigot/battle-pass#400]
### Describe the bug

Players cannot view quests beyond week 7 in the immersive UI add-on. This is a major problem as 7 weeks is not nearly long enough for a battlepass

### How to reproduce

Make 8 weeks of quests and you will not be able to see beyond week 7.

**Comment by duhneeno** [comment]
If this cannot be fixed quickly, just adding a command that opens directly to a specific weeks quests would work in the meantime.

**Comment by GC-spigot** [comment]
It's not a bug, it just wasn't designed for this. We'll add it asap!
