### ISSUE TITLE
"doesnt-have-pass" doesn't work, when player doesn't have premium pass, he won't show what he should

### ISSUE THREAD

**Issue by gary81013** [GC-spigot/battle-pass#402]
### Describe the bug

"doesnt-have-pass" doesn't work, when player doesn't have premium pass, he won't show what he should

### How to reproduce

"doesnt-have-pass" doesn't work, when player doesn't have premium pass, he won't show what he should

### Screenshots / Videos

https://imgur.com/a/3fzRYgE

### Server Log

https://pastebin.com/1zv41DJT

**Comment by KPGTB** [comment]
Hey! I don't see `doesnt-have-pass` variable in plugin's configurations. I see only `doesnt-have-pass-item` that is used in tier rewards menu
