### ISSUE TITLE
Please, add Folia support

### ISSUE THREAD

**Issue by roggy666** [GC-spigot/battle-pass#403]
### Describe the feature

I didn't find support for Folia anywhere, but I would like to add a battle pass to my server, please let me know when you add support for this core

**Comment by roggy666** [comment]
https://github.com/PaperMC/Folia

**Comment by GC-spigot** [comment]
Less than 200 servers use it, we won't add it unless there's a significant amount of servers using it https://bstats.org/plugin/server-implementation/Folia/18084

It's time consuming to add support for it
