### ISSUE TITLE
Extra NBT data being added to potions

### ISSUE THREAD

**Issue by Dakotaa** [GC-spigot/battle-pass#404]
### Describe the bug

When I have the BattlePass plugin installed, any potions brewed are having additional NBT data added. This is causing issues with shop plugins that compare item data, causing identical potions to not be identical.

### How to reproduce

Brew a potion with BattlePass installed
It will not have the same item data as a potion brewed when the plugin is not installed

**Comment by Dakotaa** [comment]
> This is used to indecate to the plugin if a potion has been already tracked for the `brew` quest type, in order to make it impossible to cheat.

Right, that makes sense, but perhaps an option to disable this mechanic so that it doesn't affect item data? I don't use brew type quests, so the protection is useless to me.

**Comment by KPGTB** [comment]
Hey! I added option to disable brewing protection. It will be available in the next update
