### ISSUE TITLE
My custom UI isn't working for the battlepass

### ISSUE THREAD

**Issue by 5tartv** [GC-spigot/battle-pass#405]
### Describe the bug

I followed the instructions on how to add the UI to the plugin. I am using Oraxen plugin for the UI to work. I provided a screenshot of what the players see when they use the command /battlepass
![image_2023-08-26_160434470](https://github.com/GC-spigot/battle-pass/assets/139995555/67cc1473-bd84-489a-b628-33580c7b41cc)

### How to reproduce

I followed the instructions on how to add the UI to the plugin. I am using Oraxen plugin for the UI to work. I provided a screenshot of what the players see when they use the command /battlepass
![image_2023-08-26_160434470](https://github.com/GC-spigot/battle-pass/assets/139995555/67cc1473-bd84-489a-b628-33580c7b41cc)

### Screenshots / Videos

![image_2023-08-26_160313700](https://github.com/GC-spigot/battle-pass/assets/139995555/3442e54d-2cdf-4798-8181-fbea59b06138)

**Comment by SirJben** [comment]
Open a ticket in Discord instead for this kind of issue, it is not a bug.
