### ISSUE TITLE
Could not pass event CrateOpenEvent

### ISSUE THREAD

**Issue by daniel-skopek** [GC-spigot/battle-pass#407]
### Describe the bug

https://pastebin.com/raw/sxvKtG9h

### How to reproduce

Open crate with BattlePass v3.19.1

**Comment by Erdi-GitHub** [comment]
Which version of ExcellentCrates are you using? This shouldn't be an issue in 4.x.x

**Comment by Erdi-GitHub** [comment]
I guess I was wrong, haha
I managed to recreate the issue, fixing it right now

**Comment by Erdi-GitHub** [comment]
Should be fixed in the next update.
