### ISSUE TITLE
block-break quest breaking for certain ores with smelting enchant

### ISSUE THREAD

**Issue by Bluzbur** [GC-spigot/battle-pass#411]
### Describe the bug

It seems when using the "smelting (in this case, level 3)" enchant, it bypassing the feature battlepass has where players can't place blocks and break it to complete the quest. I've only tested deepslate emerald ores but lead to believe it could be all deepslate ores.

Yes, im on latest version for both plugins.

### How to reproduce

Create a bp quest for block break and set it as deepslate emerald ore
Add your smelting enchant to a pickaxe
Mine the emerald ore

### Server Log

Nothing shown in logs

**Comment by Erdi-GitHub** [comment]
Fixed, the patch will be included in the upcoming update
