### ISSUE TITLE
Quest "craft" isn't working anymore after latest update.

### ISSUE THREAD

**Issue by dahbawz** [GC-spigot/battle-pass#414]
### Describe the bug

Quest "craft" isn't working anymore after latest update. Always worked untill version (4.0.2.). 
Also on version 4.0.3 it's not working

 
![image](https://github.com/GC-spigot/battle-pass/assets/16670770/1d8bf260-5c36-4d1a-94c9-7caf3c07ee3e)

### How to reproduce

Make a craft quest for tools.

### Screenshots / Videos

![image](https://github.com/GC-spigot/battle-pass/assets/16670770/eb60b501-bf6c-4022-9be8-f472f55df89d)

**Comment by Erdi-GitHub** [comment]
Fixed and thoroughly tested, the patch will be included in the next update!
