### ISSUE TITLE
plot auto bug

### ISSUE THREAD

**Issue by SladeHazard** [GC-spigot/battle-pass#415]
### Describe the bug

typing /plot auto does not progress the quest, only /plot claim does in the plotsquared_claim variable

### How to reproduce

typing /plot auto does not progress the quest, only /plot claim does in the plotsquared_claim variable

### Screenshots / Videos

na

### Server Log

na

**Comment by Erdi-GitHub** [comment]
Fixed!
Additionally, the next update will contain a new variable for plotsquared_claim, which will either be manual (for /plot claim) or auto (for /plot auto)
