### ISSUE TITLE
Thread spam causing server to crash

### ISSUE THREAD

**Issue by RWslayer** [GC-spigot/battle-pass#416]
### Describe the bug

The plugin is spamming so much thread's that it hit the pterodactyl PID limit. In terms of specs we have the best possible options. 

### How to reproduce

/

### Server Log

https://mcpaste.io/7fc59ade30c6777e

**Comment by GC-spigot** [comment]
The error does not indicate that limit of threads is reached, it's something else. I'll fix this.
