### ISSUE TITLE
Ability to localize placeholder, such as %battlepass_time_to_next_week%

### ISSUE THREAD

**Issue by IIHaunted** [GC-spigot/battle-pass#421]
### Describe the feature

Ability to localize placeholder, such as %battlepass_time_to_next_week%. It would be very convenient to localize such placeholders. There is already a similar opportunity, but with the daily quest: 
daily-quest-time-format: 
# The time format used for saying how long until daily quests expire.
  with-months-weeks: "%dмес. %dн. %dд. %dч. %dм. %dсек."
  with-weeks-days: "%dн. %dд. %dч. %dм. %dсек."
  with-days-hours: "%dд. %dч. %dм. %dсек."
  with-hours-minutes: "%dч. %dм. %dсек."
  with-minutes-seconds: "%dм. %dсек."
  with-seconds: "%dсек."

**Comment by PKBCRAFT** [comment]
+1, I would like to be able to localize that placeholder as well.

**Comment by KPGTB** [comment]
Hey! I added that feature. It will be available in the next update. It will use configuration from daily quest locale format
