### ISSUE TITLE
Character array contains more than one decimal point error

### ISSUE THREAD

**Issue by austv** [GC-spigot/battle-pass#425]
### Describe the bug

In 3.18.4 version was added support for decimal placeholders but now I have this error for more thhan one decimal point. Every time that a player logged in, the error show. The only quest that i'm using placeholder type is this placeholder: **%VotingPlugin_Total_Daily%**

I added the error log below

### How to reproduce

Create this type of quest:

```
    type: placeholderapi_integer_VotingPlugin_Total_Daily
    variable: none
```

### Server Log

https://mclo.gs/q1id2t4

**Comment by KPGTB** [comment]
Hey! I can't recreate problem with integer papi quests. Please test, if that bug still exists in the newest battlepass version. If it still exists, please send me output of your placeholder (%VotingPlugin_Total_Daily%). You can make it using i.e. `/papi bcparse`
