### ISSUE TITLE
Velocity 'quest-glow-on-completion' Bug

### ISSUE THREAD

**Issue by ggm801** [GC-spigot/battle-pass#426]
### Describe the bug

When I complete a weekly quest the Item glows for me and other players that didn't complete the quest. The quest still is not completed for other player but the item glows.

Velocity server
Paper 1.19.4
 MySQL

### How to reproduce

Complete a Week quest in a velocity server with battlepass connected to MySQL, see if the item glow for other players

**Comment by KPGTB** [comment]
Hey! Problem has been fixed in the last update
