### ISSUE TITLE
PlayerUseCraftingStationEvent to BattlePass v4.0.8

### ISSUE THREAD

**Issue by Nogginth** [GC-spigot/battle-pass#429]
### Describe the bug

there is error spam on the console it says "PlayerUseCraftingStationEvent"
it might relate to the MMOItem plugin with get crafting station.

"there is no quest about crafting thing in mmoitem station"

all plugin relate to MMOItem are the last version.
BattlePass-4.0.8
MMOCore-1.12
MMOItems-6.9.4
MythicLib-1.6.1

### How to reproduce

try to interact with mmoitem crafting station.
then the error will randomly show up.

### Server Log

https://mcpaste.io/b656eca6c0f4a063

**Comment by Erdi-GitHub** [comment]
Fixed, the patch will be included in the next release
