### ISSUE TITLE
Mysql Errors

### ISSUE THREAD

**Issue by Toki-teki** [GC-spigot/battle-pass#43]
**Describe the bug**

**To Reproduce**
Mysql connection not work
Credentions 100% corrected.
https://pastebin.com/Se9LPBd2

**Screenshots / Video**
If applicable, add screenshots or videos to help explain/ show your problem.

**Server Information (please complete the following information):**
- Server Version: SSSpigot 1.16.5
- Plugin Version: 3.36

**Comment by Toki-teki** [comment]
Perhaps you should take full control of the MySQL connection so that the plugin connection does not depend on the core code.

**Comment by Toki-teki** [comment]
how to download old versions?

**Comment by GC-spigot** [comment]
Fixed in next version
