### ISSUE TITLE
legacy mc version | item-break not work

### ISSUE THREAD

**Issue by Canobe1314** [GC-spigot/battle-pass#430]
### Describe the bug

Item-break does not work in the legacy Minecraft server version

spigot.1.12.2

### How to reproduce

The default configuration file also has bugs.
Simply use spigot1.12.2 and the default battlepass configuration file to trigger this bug

### Screenshots / Videos

![bbec19b3c51f16bc5f04c78bf57e18f5](https://github.com/GC-spigot/battle-pass/assets/123566440/f4a07f72-2434-44c7-9b04-4dddbecda05c)

**Comment by Canobe1314** [comment]
Variable: Unable to filter

**Comment by Canobe1314** [comment]
battlepass v4.0.8

**Comment by Canobe1314** [comment]
battlepass v4.0.10

**Comment by Canobe1314** [comment]
battlepass v4.0.11

**Comment by Canobe1314** [comment]
pls help me

**Comment by Erdi-GitHub** [comment]
Fixed, the fix will be included in the next update. In the meanwhile, you can use `diamond_pickaxe:-1` instead of `diamond_pickaxe:0`
