### ISSUE TITLE
Changing the region whitelist

### ISSUE THREAD

**Issue by mrfiveV** [GC-spigot/battle-pass#432]
### Describe the feature

Make the white list of regions prohibit all other regions.
Now if the region is not on the white list, nothing happens.
If you add "else return true"
in checking a region in a whitelist, this should disallow other regions

This is necessary to create separate regions for completing tasks that may be affected by other plugins (Custom enchantments or skills that will be prohibited in these regions)

**Comment by GC-spigot** [comment]
Will be added ty
