### ISSUE TITLE
Gradient Hex Color?

### ISSUE THREAD

**Issue by Merunko** [GC-spigot/battle-pass#433]
### Describe the feature

Does Battle Pass plugin support gradient hex colors?

**Comment by SirJben** [comment]
It does, I believe use `&x&r&r&g&b&b&b` format. e.g. `&x&0&0&F&F&E&0B&x&1&A&E&3&E&3a&x&3&4&C&6&E&7t&x&4&E&A&A&E&At&x&6&8&8&E&E&El&x&8&3&7&1&F&1e&x&9&D&5&5&F&5p&x&B&7&3&9&F&8a&x&D&1&1&C&F&Cs&x&E&B&0&0&F&Fs`
