### ISSUE TITLE
EconomyShopGUI

### ISSUE THREAD

**Issue by ItsOn3x** [GC-spigot/battle-pass#436]
### Describe the feature

Hello!
I have the EconomyShopGUI plugin and i want to use it in my quests. Unfortunately, it is not supported. It is a widely used plugin and it would be great if this one could be supported as well!

**Comment by aXe18** [comment]
I will upvote for this 100%, planning to start using this plugin and i want use it with battlepass too :)

**Comment by KPGTB** [comment]
Hey! I added support for this plugin
