### ISSUE TITLE
Placeholder

### ISSUE THREAD

**Issue by Mineacc00** [GC-spigot/battle-pass#440]
### Describe the feature

I wanna suggest to create a place holder that displays the amount of quests a user has **YET** to completed in a specific week.

![image](https://github.com/GC-spigot/battle-pass/assets/103889962/601d79aa-4084-4584-8c97-562c27b21259)

**Comment by GC-spigot** [comment]
It should be pretty easy to just set yourself this without a placeholder, it shouldn't change that much
