### ISSUE TITLE
Swim Quest Bug

### ISSUE THREAD

**Issue by DecypherMC** [GC-spigot/battle-pass#441]
### Describe the bug

Flying in water progresses the swim quest. This happens in survival with fly and spectator mode with fly. It may also happen in creative/adventure mode but I haven't tested.

### How to reproduce

Create a swim quest, then fly in water. It's best to do in an ocean because you'll see it progress faster.

**Comment by Erdi-GitHub** [comment]
Fixed! The fix will be included in the next update
