### ISSUE TITLE
Wrong variable name,

### ISSUE THREAD

**Issue by SirJben** [GC-spigot/battle-pass#442]
### Describe the bug

the variable for carrots when using `/bpa material` command display as `carrots:` but it does not work when creating a quest for it but `carrot:` without `s` does.
Clarification for right variable name. 

### How to reproduce

use `/bpa material` command and try to use the variable in block-break quest and it will not work 
but use the `carrot:` it will.

**Comment by GC-spigot** [comment]
Because hand items and blocks are always different, it's a different material always
