### ISSUE TITLE
CrazyEnvoy not compatible with battlepass

### ISSUE THREAD

**Issue by DragonssDEV** [GC-spigot/battle-pass#443]
### Describe the bug

Using the latest version of battlepass and crazyenvoy and the verbal for the open crates isn't working was told to submit this by your dev. server version is 1.16.5

### How to reproduce

idk

**Comment by Erdi-GitHub** [comment]
CrazyEnvoys 1.4.x (the latest 1.16.5-compatible versions) and BattlePass are no longer compatible due to changes in CE 1.5.0, you'll have to upgrade your server and CrazyEnvoys to be able to use CE and BP together
