### ISSUE TITLE
BP Integer Placeholder Breaks Past 2.147B (Should be an easy fix)

### ISSUE THREAD

**Issue by skycar** [GC-spigot/battle-pass#444]
### Describe the bug

Hi there, the value seen in green in the screenshot I attached is coming up as a negative integer (underflow) in the battlepass and it is also the incorrect value. I am using the latest version of BattlePass, 4.0.13

The value is EdPrison Tokens Balance, stems from EdPrison plugin. I asked EdPrison dev and he said to contact BP support, it’s not due to his plugin as there is no way it'd be possible for EdP to display a negative token balance. He said all the BP dev needs to do is change the **int** variable to a **double** (super easy fix). 

The placeholder in question (in BP) is **placeholderapi_integer_nf_#_edprison_tokens**. This is the only placeholder that works, according to the BP developer.

This is an OP Prison server so token accumulation is very high (inflated economy) so I can't really change that, i'd have to remove all token quests and I have 3 of them. They're an important aspect to the server. 

### How to reproduce

Accumulate any value of tokens or any value in any plugin above 2147483647 and it'll break the BP input. 

I can also confirm that when a number above that BP "cap" is parsed through PAPI, including in the trillions and quadrillions, it is correctly parsed. Zero issues with it being displayed. As in when you do **/papi parse me %nf_#_edprison_tokens%**. So it's definitely a BP issue. Again, very simple fix. Once **int** variable is changed to a **double** it'll be able to parse extremely large values without a hitch.

### Screenshots / Videos

https://prnt.sc/nDU8vlSn_Xwf

**Comment by GC-spigot** [comment]
Fixed! Thanks for reporting
