### ISSUE TITLE
MySQL password using special characters containing "&" causes connection issues

### ISSUE THREAD

**Issue by jhqwqmc** [GC-spigot/battle-pass#447]
### Describe the bug

MySQL password using special characters containing "&" causes connection issues

### How to reproduce

MySQL password uses special characters containing "&"

**Comment by Lerphie** [comment]
@GC-spigot plz fix it

**Comment by GC-spigot** [comment]
Are you guys surrounding the password with quotes? e.g. "password@!#$!%!". This works completely fine for me and other users
@Lerphie @jhqwqmc

**Comment by jhqwqmc** [comment]
@GC-spigot Inverted commas are used, but the problem persists

**Comment by Lerphie** [comment]
> Are you guys surrounding the password with quotes? e.g. "password@!#$!%!". This works completely fine for me and other users @Lerphie @jhqwqmc

The commas didn't work for me, I used them too

**Comment by KPGTB** [comment]
Hey! I also can't reproduce that problem. Are you guys sure, that database credentials are correct? Also, please check, if database allows connecting using that user from your server.
