### ISSUE TITLE
[Request]

### ISSUE THREAD

**Issue by Weymouth87** [GC-spigot/battle-pass#45]
**Describe the Request**

Support for BentoBox (BSkyBlock & Addons), Aurelium Skills, MoreFish, Jackpot if possible please :) 

Links to the plugins: 
https://www.spigotmc.org/resources/bentobox-bskyblock-acidisland-skygrid-caveblock-aoneblock-boxed.73261/
https://www.spigotmc.org/resources/aurelium-skills-advanced-skills-stats-abilities-and-more.81069/
https://www.spigotmc.org/resources/morefish-improved-fishing-and-fishing-competition.22926/
https://www.spigotmc.org/resources/jackpot-1-8-1-16-⭐-automatic-lottery-system-cosmicpvp-replica.80811/

**Comment by GC-spigot** [comment]
Meanwhile you can use PlaceholderAPI placeholders to add support while we're working on adding support directly: https://battlepass.advancedplugins.net/features/placeholderapi-endless-quests
