### ISSUE TITLE
ShopGUI+ Quest Issue

### ISSUE THREAD

**Issue by djcflores** [GC-spigot/battle-pass#450]
### Describe the bug

When Daily Quests resets and a ShopGUI+ Quest is picked, the Quest progress doesn't work immediately unless you do **/bpa reload** and it will start recording progress. It's a hassle to always do the command everyday just to fix this concern.

### How to reproduce

1. Create a Quest for ShopGUI+ Plugin
(This is the Code I used)
`  'shopguiplus': # Quest id
    type: shopguiplus_spend
    variable: none
    name: Daily Shopping
    required-progress: 50
    points: 10
    item:
      material: chest
      name: '&6Daily Shopping'
      lore:
      - '&7Purchase atleast &e$50 &7from &eHollgrehenn'
      - ''
      - '&7Information:'
      - '&8 » &7Points: &f10'
      - '&8 » &7Progress &e%total_progress%&7/&e%required_progress%'`

2. Refresh Daily Quest until the ShopGui+ quest appears on the daily quest.
3. Try to complete the Quest (Progress wont work)
4. Do **/bpa reload** and it will start working again.

### Screenshots / Videos

https://github.com/GC-spigot/battle-pass/assets/142185223/60672ebe-f320-44d8-9f4f-eb3cf6430905

**Comment by KPGTB** [comment]
Hey! I can't reproduce that problem
