### ISSUE TITLE
Abusing premium rewards

### ISSUE THREAD

**Issue by lDoomerl** [GC-spigot/battle-pass#457]
### Describe the feature

I remember an issue when player bought a BP premium for 1 month, complited questes, claimed premium rewards, then premium is expired and after this he bought one more month and claimed rewards for the second time for the quests he completed in the 1st month. 

Can you fix it pls?

What do I mean: make a rewards to be claimed only one time
Because if the player has a default permission, then permission premium, then default and premium again - he will claim rewards 2 times. It's very abusive

I suggest to fix it in database of the plugin like "playername claimed reward #1" for example
So the plugin will remmember it and will not allow to get it 2 times

**Comment by KPGTB** [comment]
Duplication of #285 - Problem fixed. Fix will be available in the next update
