### ISSUE TITLE
BigDecimal error Vault placeholder and other plugins

### ISSUE THREAD

**Issue by NixsSa2d** [GC-spigot/battle-pass#458]
### Describe the bug

My problem is that using the placeholderapi_integer, with all the plugins it does not let me put large numbers, since my server is prisonop, in this case I tried the vault

### How to reproduce

the video I uploaded to mediafire looks exactly

### Screenshots / Videos

https://www.mediafire.com/file/lomc2mx6ib5rfmi/Desktop_15-11-2023_11-27-49_a._m..mp4/file

### Server Log

https://mcpaste.io/ceaebf719685896d

**Comment by GC-spigot** [comment]
Please try updating, we've changed a few things since that version. These numbers work completely for me:
![image](https://github.com/GC-spigot/battle-pass/assets/13188801/cccdca33-9f7e-42af-b4b9-42e1fbfef813)

**Comment by NixsSa2d** [comment]
Which placeholder exactly do you use?

**Comment by GC-spigot** [comment]
Update first, we did changes with exactly this feature few updates ago:
![image](https://github.com/GC-spigot/battle-pass/assets/13188801/0f018247-2038-46f2-8c49-6e6a86799211)

**Comment by NixsSa2d** [comment]
2 billion? I would need trillions if possible, plus it not only happens to me with the vault, but with ALL the placeholders, but I'm going

**Comment by GC-spigot** [comment]
Have you tried the version yet? Sounds like trillion is over 2 billion, which is what the update says.

**Comment by NixsSa2d** [comment]
but I want trillions, and I know what it is, I said it right, it's just that the translation is different since I'm using Google Translate

**Comment by NixsSa2d** [comment]
![image](https://github.com/GC-spigot/battle-pass/assets/150930296/ea9f5ade-c76f-4448-8e02-89aa3bba7660)


The other problem is that your plugin does not have placeholders formatted, so the progress looks horrible

**Comment by GC-spigot** [comment]
Okay, but you have yet to confirm that this issue is resolved for you. Is it resolved - yes/no?

**Comment by NixsSa2d** [comment]
It works in that if you score correctly now, and when you reach 100% it is completed but it doesn't give you points, nor does it tell you a message in the chat or anything

**Comment by NixsSa2d** [comment]
List seems to be working now, bug fixed
