### ISSUE TITLE
Smelt/craft bug abuse

### ISSUE THREAD

**Issue by memosoff** [GC-spigot/battle-pass#459]
### Describe the bug

A bug with smelt/craft type quests, if you fill ur inventory and click 1-9 on keyboard on smelted item in furnace - item remains, but plugin counts it, so you can infinity clicking to it and with 1 item complete 5k quest, for example. 

If you need video, you can find it on ur discord channel, battlepass-1425 ticket.

### How to reproduce

1. Smelt 1 item (or craft, work with many types)
2. Fill your inventory
3. Open furnace and click 1-9 (on keyboard) on smelted item
4. Plugin counts every click on item

**Comment by memosoff** [comment]
i feel premium bugfix speed, do not rush, let the players continue to abuse 😍😍😍

**Comment by memosoff** [comment]
don't rush, bro let players abuse more🤟🤟🤟

(for a example, same bug in other similar plugin fixed by 1 day o_O)

**Comment by KPGTB** [comment]
Hey! Problem has been fixed. Fix will be available in the next update
