### ISSUE TITLE
FREE PASS - Required Points placeholder doesn't work in the locked-tier-item in free.yml

### ISSUE THREAD

**Issue by PKBCRAFT** [GC-spigot/battle-pass#460]
### Describe the bug

The placeholder %required_points% doesn't work in free.yml, in the lore of the section of locked-tier-item.
The placeholder displays just the number 0, but not the required points that have been setup.

I am using BattlePass-4.0.18.jar version.
1.20.1 Paper

### How to reproduce

1. Go to Battlepass folder
2. Go to passes folder
3. Open free.yml
4. Search for locked-tier-item
5. Add a line and use the placeholder %required_points%
6. Go on your serve
7. Use /bpadmin reload
8. Open Battlepass
9. Go to Rewards section
10. Go in the lore of the free rewards
11. See that the placeholder %required_points% displays just the number 0 instead of the number you have in your config for required points to unlock the tier

### Screenshots / Videos

![image](https://github.com/GC-spigot/battle-pass/assets/147991120/382ba558-9aa9-4dbe-bb85-52c67ee7c88e)
![image](https://github.com/GC-spigot/battle-pass/assets/147991120/8794cd43-1781-48e1-bfa9-252c2564bba4)

**Comment by Drakified** [comment]
This appears to be working in the latest version (4.1.8-2).

**Comment by PKBCRAFT** [comment]
Issue still occuring on version 4.1.9

**Comment by KPGTB** [comment]
Hey! I also can't recreate that problem on the latest version of plugin

**Comment by PKBCRAFT** [comment]
Hello, I am still able to reproduce this issue, I am pretty sure it happens because the next tier doesn't have a rewards, can you please retry like this? I have a reward at Tier 2 and then another one at Tier 6, tier 3, 4, 5 are empty.

**Comment by KPGTB** [comment]
Can you send me your passes configuration files?

**Comment by PKBCRAFT** [comment]
I can give it to you on discord or somewhere else private. Let me know if that works for you.

**Comment by KPGTB** [comment]
My discord: `kpgtb`

**Comment by PKBCRAFT** [comment]
Sent a friend request.

**Comment by KPGTB** [comment]
Hey! Problem has been fixed. Fix will be available in the next update
