### ISSUE TITLE
Quests don't count blocks that were generated by regen plugin

### ISSUE THREAD

**Issue by Morakelone** [GC-spigot/battle-pass#462]
### Describe the bug

Hello, I have a problem that when mining in our mine in our oneblock & DUngeons mode the blocks are not counted. They are generated by this plugin: https://www.spigotmc.org/resources/mine-x-farm-regen-1-17-1-20.107060/

### How to reproduce

Play the feature on a test server. Information dc Bug report

**Comment by KPGTB** [comment]
Hey! I can't reproduce that problem. Can you send quests configuration file and video of that issue?
