### ISSUE TITLE
i18n support

### ISSUE THREAD

**Issue by gamingcodedev** [GC-spigot/battle-pass#470]
### Describe the feature

Hey, i have an multilanguage server and i would ask if you could add i18n support

**Comment by Drakified** [comment]
This would take a lot to implement, so we are not going to be adding this.

Thanks for the suggestion though!

**Comment by gamingcodedev** [comment]
Maybe you add an API that i can do it myself or something like that? It would be fine if users have set an language and search the messages from there i would pay extra for it!
