### ISSUE TITLE
Immersive BattlePass UI

### ISSUE THREAD

**Issue by SliqSuicide** [GC-spigot/battle-pass#472]
### Describe the bug

The UI has 7 slots for the free pass and 7 slots for the premium pass in the quest overview menu.
When you add 8 free quests to week one the 8th one will be in the first slot of premium quests.
Before I installed it UI, there was a button for the next page which might even be in one of the menu's .yml's but it's not showing up. I saw on disoord at least 1+ another user had the same problem.

### How to reproduce

The reproduce is the descrption. Even when you reinstall everything there is no chance to do 8 free quests.

### Screenshots / Videos

https://prnt.sc/Rm6ztloaF7fc
https://prnt.sc/NO6lSZNFbaNJ
Missing: https://prnt.sc/2QWDTmc2zjjY
Also missing here: https://prnt.sc/-77viz-22W4x

### Server Log

https://mclo.gs/vaBx6xd

**Comment by Drakified** [comment]
Hello. We are working on adding pages to this, so this should be resolved in a future update.

Thanks!
