### ISSUE TITLE
/bpa reload cause crash

### ISSUE THREAD

**Issue by FrancescoJacovo** [GC-spigot/battle-pass#473]
### Describe the bug

If you use /bpa reload multiple times the server crash for out of memory / can't create more threads. Probably it doesn't end his threads and continue to create new ones

### How to reproduce

Install last version, make /bpa reload multiple times.

**Comment by Drakified** [comment]
I cannot reproduce this on the latest version.
Does this still persist for you?

**Comment by FrancescoJacovo** [comment]
I saw that theese guy https://github.com/GC-spigot/battle-pass/issues/445 have the same problem

**Comment by sqwkz** [comment]
We are also having the same exact issue. If the plugin is reloaded more than 2-3 times within a small span of time the entire server crashes. We are running Arclight 1.16.5.

**Comment by KPGTB** [comment]
Duplication of #445
