### ISSUE TITLE
BattlePass Plugin Interferes with Vanilla Minecraft Potions

### ISSUE THREAD

**Issue by DimaSergeew** [GC-spigot/battle-pass#474]
### Describe the bug

Encountered an issue with the BattlePass plugin where it inadvertently affects vanilla Minecraft potions. Specifically, potions brewed through the standard brewing stand process are being tagged with an NBT (Named Binary Tag) related to BattlePass. This tagging disrupts the normal functionality of the vanilla potions, causing compatibility issues with many plugins that do not recognize these altered potions.

### How to reproduce

Install the BattlePass plugin on a Minecraft server.
Use a brewing stand to brew any potion in vanilla Minecraft.
Once the potion is brewed, check the potion's NBT data.
Observe that the potion has an NBT tag related to BattlePass.
Attempt to use the potion with other plugins that interact with vanilla potions.
Notice that these plugins fail to recognize or properly interact with the potion due to the added NBT tag.

### Screenshots / Videos

![image](https://github.com/GC-spigot/battle-pass/assets/75163645/5fbd6d5b-e47b-4254-b63d-467036644e5e)

**Comment by DimaSergeew** [comment]
!!!

**Comment by KPGTB** [comment]
Hey! Our plugin adds NBT tag to potions to make sure that players won't abuse `brew` quests using only one potion. If you don't use a `brew` quest, I added an option to settings.yml to disable that protection. It will be available in the next update.

Duplication of #404

**Comment by DimaSergeew** [comment]
I have updated the jar, but I cannot find this option.

**Comment by KPGTB** [comment]
> I have updated the jar, but I cannot find this option.

Settings file doesn't have option to auto update, so you can remove settings file to generate new one, or manually add
```
brewing-protection: false
```
