### ISSUE TITLE
Weekly Premium Quests, but free?

### ISSUE THREAD

**Issue by Jochhz** [GC-spigot/battle-pass#476]
### Describe the bug

BattlePass weekly quest, with quest with `exclusive: premium` but it still shows in free quest.. but it will work with giving it a later ID. Visited support, and seemed to be a bug.
Image is provided
Code is provided as below:

name: 'Week 1 - Premium Social' # The name given to the quest.
    type: chat # The type of quest
    variable: none # The block the player must break.
    required-progress: 150 # The amount of times the player should break the coal ore block.
    points: 10 # The amount of points that will be rewarded
    exclusive: premium
    item: # The item that will be displayed in menus.
      material: paper:0
      amount: 1
      name: '&ePremium Only - Social'
      lore:
        - '&7Talk in chat &e150 times'
        - '&7&oExclusive to premium members only.'
        - ''
        - '&7Progress &e%total_progress%&7/&e%required_progress%'

### How to reproduce

`exclusive: premium` isn't working properly.. was told

### Screenshots / Videos

![Screenshot 2024-01-07 232509](https://github.com/GC-spigot/battle-pass/assets/117247462/90a6a33d-75f0-41a7-a329-26848e6e1acd)
![Screenshot 2024-01-07 232231](https://github.com/GC-spigot/battle-pass/assets/117247462/13a17274-589c-4b23-9020-3c48c1b3eb52)

**Comment by KPGTB** [comment]
Duplication of #351
