### ISSUE TITLE
charcoal variable does not work with smelt

### ISSUE THREAD

**Issue by qq851411536** [GC-spigot/battle-pass#477]
### Describe the bug

The quest type smelt does not work with charcoal

### How to reproduce

I have set the quest type to be smelt with variable charcoal, I put logs in the furnace and turn it into charcoal and the quest doesnt progress

### Screenshots / Videos

![QQ图片20240108060852](https://github.com/GC-spigot/battle-pass/assets/28604766/54b469da-0790-477f-8e27-b2e35e16865a)

### Server Log

https://mcpaste.io/644aee90f89c7cf6

**Comment by KPGTB** [comment]
Hey! Battlepass plugin requires specific item name (material:data). Data means number that was used in old minecraft versions to identify block variation. In most cases it's 0, but in the case of charcoal, it's 1. So, you need to put as variable `charcoal:1`. Full list of data's value you can check i.e. [here](https://minecraftitemids.com/) (Look at the value after `:` in numerical id column. If it's empty - it's 0)
