### ISSUE TITLE
[Issue] Error on plugin disable

### ISSUE THREAD

**Issue by WarnDangerous** [GC-spigot/battle-pass#48]
**Describe the bug**
I got an error when I stop the server

**To Reproduce**
Install plugin, and restart the server

**Screenshots / Video**
https://pastebin.com/QEfNQmLx

**Server Information (please complete the following information):**
- Server Version: git-Airplane-"9f0a29b" (MC: 1.16.5)
- Plugin Version: 3.38

**Comment by GC-spigot** [comment]
Fixed
