### ISSUE TITLE
battlepass.premium

### ISSUE THREAD

**Issue by Abood8001** [GC-spigot/battle-pass#480]
### Describe the feature

Hello, there should be a permission that can give the player access to the premium pass instead of using /bpadmin set pass <player> premium, because like we want to use luckperms to give players premium access like we could use luckperms to give them a temp access to the pass like 10d, 20d or 30d

**Comment by KPGTB** [comment]
Hey! In pass config (`passes/premium.yml`) you can enable permission system by removing `#` from 3rd line
From: `#required-permission: 'battlepass.premium'`
To: `required-permission: 'battlepass.premium'`
