### ISSUE TITLE
CrazyCrates and CrazyEnvoys update

### ISSUE THREAD

**Issue by KubikTheGamer** [GC-spigot/battle-pass#481]
### Describe the bug

Hi, for some time now CrazyCrates and CrazyEnvoys hooks haven't been working, so I was told to post the errors on here so here you go:

```
00:00:45[ERROR] [BattlePass] Failed to register events for class net.advancedplugins.bp.impl.actions.external.CrazyCratesQuestsNew because com/badbones69/crazycrates/paper/api/events/PlayerPrizeEvent does not exist.
00:00:45[ERROR] [BattlePass] Failed to register events for class net.advancedplugins.bp.impl.actions.external.CrazyEnvoyQuests because com/badbones69/crazyenvoys/paper/api/events/EnvoyOpenEvent does not exist.
```

Versions:
Paper 1.20.4
Battlepass 4.2.5
CrazyCrates 1.19.1
CrazyEnvoys 1.8.2

### How to reproduce

The errors appear on server startup with version mentioned above

### Screenshots / Videos

![image](https://github.com/GC-spigot/battle-pass/assets/138825723/39fe35e1-3b6b-4a1a-96e2-840ea9a5cfe2)

### Server Log

https://mcpaste.io/6b23e7f8943d2795

**Comment by KPGTB** [comment]
Hey! Problem has been fixed. Fix will be available in the next update

**Comment by KPGTB** [comment]
Hey! That's strange. We will check it

**Comment by KPGTB** [comment]
Should be fixed now

**Comment by KubikTheGamer** [comment]
Yep, it works fine now.
Thank you!
