### ISSUE TITLE
Block Break Quest do not work

### ISSUE THREAD

**Issue by gamingcodedev** [GC-spigot/battle-pass#482]
### Describe the bug

If i enter a quest like mine 10 diamond ore's, than the quest will not progress if i break diamond ore

### How to reproduce

1: # Quest id
    name: 'Woche 1 - Miner' # The name given to the quest.
    type: block-break # The type of quest
    variable: diamond_ore:0 # The block the player must break.
    required-progress: 10 # The amount of times the player should break the coal ore block.
    points: 10 # The amount of points that will be rewarded
    item: # The item that will be displayed in menus.
      material: diamond_pickaxe:0
      amount: 1
      name: '&eMiner'
      lore:
        - '&7Baue &e10 Diamanten §7ab'
        - ''
        - '%progress_bar% &7(&a%percentage_progress%&7)'

**Comment by KPGTB** [comment]
Hey! How do you test that quest? Please notice that breaking block that is placed by player is not counted. To progress block-break quest, you need to break naturally placed block or block placed by commands

**Comment by gamingcodedev** [comment]
oh i see i want to have both diamond_ore and deeplate how to setup this?

**Comment by KPGTB** [comment]
`diamond_ore:0 OR deeplate:0`

**Comment by gamingcodedev** [comment]
i mean diamond_ore and deeplate_diamond_ore

**Comment by KPGTB** [comment]
`diamond_ore:0 OR deepslate_diamond_ore:0`

**Comment by gamingcodedev** [comment]
can't i enter both to one quest?

**Comment by KPGTB** [comment]
You can use both materials in one quest:
```
variable: diamond_ore:0 OR deepslate_diamond_ore:0
```

**Comment by gamingcodedev** [comment]
ah
