### ISSUE TITLE
mcmmo variables not working 

### ISSUE THREAD

**Issue by dragonfruit26** [GC-spigot/battle-pass#484]
### Describe the bug

Both variables mcmmo_gain_exp and mcmmo_level_up_skill arent working when i put them in quests. There are no errors in console at all. Whenever a player gains exp or level up a skill for a quest, it doesnt progress or complete. I am up to date on both plugins, battlepass and mcmmo.

Also when doing /plugman info battlepass, mcmmo is not on the softdepend list for the plugin but MMOCore is.

### How to reproduce

![image](https://github.com/GC-spigot/battle-pass/assets/155488283/66d703db-b5cf-4f2d-a5aa-3ba2122930bb)
![image](https://github.com/GC-spigot/battle-pass/assets/155488283/50ca53c7-efc2-496a-8f6c-05e45b90bfaf)

**Comment by GC-spigot** [comment]
Hmm, this is working for me. We'll do some changes, let us know if this is fixed for you next update 
![image](https://github.com/GC-spigot/battle-pass/assets/13188801/e975afb0-e88d-4164-94aa-85b6881eda51)
