### ISSUE TITLE
Add PlayerBlockTracker

### ISSUE THREAD

**Issue by Mithranduil** [GC-spigot/battle-pass#485]
### Describe the feature

possible to add support for https://github.com/Flo0/PlayerBlockTracker

Cause the currently block tracker didnt allow the tracking after server restart.
With this plugin its possible to track them without any performance issues and also after restart, piston movement, etc.

**Comment by Mithranduil** [comment]
> PlayerBlockTracker uses PersistentDataContainer, we can use that. Thanks, accepted!

thank you very much!

will there be any eta for the coming future?

**Comment by KPGTB** [comment]
Hey! This feature will be available in one of the next larger updates 😉

**Comment by KPGTB** [comment]
Hey! I'm sorry but it seems that PlayerBlockTracker is very problematic addon - it can even cause crashes in some cases. I removed it and switched back to old system :c
