### ISSUE TITLE
Sync daily quests between multiple servers

### ISSUE THREAD

**Issue by gamingcodedev** [GC-spigot/battle-pass#488]
### Describe the feature

Hey, i am using an bungeecord network, and i want to suggets if you can add sync for the daily quests, but it is weird if players have on each servers other daily quests, so i would to like if you add this as feature.

**Comment by KPGTB** [comment]
Hey! We added that option in BattlePass 4.2.8. To make it work, on one server set `daily-quests-use-bungee` to `false`. On other servers in bungee network, set that option to `true`

**Comment by gamingcodedev** [comment]
So i set on my bungee network on one server it to false and on all others to true?

**Comment by KPGTB** [comment]
Yes
