### ISSUE TITLE
BattlePass Aliases not working

### ISSUE THREAD

**Issue by BorisOZ** [GC-spigot/battle-pass#492]
### Describe the bug

In `settings.yml,` I have set a few aliases under `battle-pass-aliases`. This worked in previous versions, but I updated from 3.18.5 to 4.2.11 and they are now unknown commands when I try to run them. There are no warnings/errors in the console. The normal `/bp` command still works fine.

### How to reproduce

In `settings.yml`, add a few aliases under `battle-pass-aliases`.
For example
```
battle-pass-aliases:
  - 'bpalias'
```
  Start the server
  Try to run the alias you just defined.

**Comment by KPGTB** [comment]
Hey! Problem has been fixed. Fix will be available in the next update
