### ISSUE TITLE
Executing Commands when Daily Quest is completed

### ISSUE THREAD

**Issue by NaTorOG** [GC-spigot/battle-pass#496]
### Describe the feature

Hello, I believe it would be easy, since just need to add a ConfigurationSection and also cool, to run commands when a DailyQuest is completed.

In my specific case, I would like to use DailyQuests that when completed don't give points and I can already do this by settings the points to 0.
Problem is that this way I can not give rewards to player without breaking my Tiers System

**Comment by KPGTB** [comment]
Hey! I added that feature. It will be available in the next update. That option will work in daily quests and in weekly quests
