### ISSUE TITLE
Daily quest not reset and alredy complited

### ISSUE THREAD

**Issue by VOIDDERtm** [GC-spigot/battle-pass#499]
### Describe the bug

It was repeatedly noticed that some tasks were completed by (daily) players immediately, while neither progress nor a command was given to complete the task.
The task immediately considers itself completed, even if the tasks have just been updated by time (daily).

### How to reproduce

It’s impossible to specify specifically. Players who complete tasks complain that on the next day, new (the task is chosen randomly) tasks are indicated completed, there is no progress, and there is not even a reward for advancing through the Battle Pass. It was as if the task had not been completed that day.

### Screenshots / Videos

https://media.discordapp.net/attachments/975427941599178853/1219553074687770734/2024-03-19_14.46.54.png?ex=660bb84f&is=65f9434f&hm=4e54eb478d08fdf8ef43418dfb98b41acd14f6575f45e8b020f29b2e7c5ff3a0&format=webp&quality=lossless&width=887&height=499&

### Server Log

https://mcpaste.io/19c19e1e3235bd29

**Comment by KPGTB** [comment]
Hey! I tested it, but I can't recreate that problem.
