### ISSUE TITLE
[Request] Improve BattlePass GUI with resource pack

### ISSUE THREAD

**Issue by danechek** [GC-spigot/battle-pass#5]
There are already many plugins that, using the resource pack, change the appearance of the inventory, GUI and even ESC menu.  I would like the same with this plugin, so that there is not a simple GUI, but more like real battle passes in modern games

**Comment by GC-spigot** [comment]
That's for 1.13+ servers, this plugin supports 1.8 - 1.16, you can set items you want using customModelData, but that's about it at the moment.

**Comment by danechek** [comment]
> That's for 1.13+ servers, this plugin supports 1.8 - 1.16, you can set items you want using customModelData, but that's about it at the moment.

This could be implemented as an addon using ItemsAdder for users of the BattlePass plugin 1.13+

**Comment by GC-spigot** [comment]
Exactly, it’s for another plugin - you will have to create it yourself.
