### ISSUE TITLE
[Request] Progress command working for offline players

### ISSUE THREAD

**Issue by Dakotaa** [GC-spigot/battle-pass#50]
**Describe the Request**
/bpa progress command working for offline players.

Since the command quest type was removed a while back, I use block-break quests with barriers as the variable in order to create "custom" quests, which I progress with the /bpa progress command. The issue is that this command does not work for offline players, the quests will not be progressed.

**Comment by GC-spigot** [comment]
What could we add quests wise to fix this issue? We can't add offline player support with `/bpa progress` but we might be able to solve it by adding quest you need.

**Comment by Dakotaa** [comment]
> What could we add quests wise to fix this issue? We can't add offline player support with `/bpa progress` but we might be able to solve it by adding quest you need.

There used to be a "command" quest type in the plugin a few years back, which could only be progressed by a certain command, that would work perfectly.
