### ISSUE TITLE
Plugin BattlePass v4.2.17 generated an exception while executing task 380336

### ISSUE THREAD

**Issue by iFranticman** [GC-spigot/battle-pass#500]
### Describe the bug

Error randomly in console

### How to reproduce

Run a server

### Server Log

https://mcpaste.io/25668bc28ab4ac2a

**Comment by KPGTB** [comment]
Hey! It seems that one/some of files with user data are empty. You should delete them manually. I also added small fix which should skip these files

**Comment by iFranticman** [comment]
This is still happening

**Comment by GC-spigot** [comment]
We'll fix this asap

**Comment by KPGTB** [comment]
> Please delete empty files from /plugins/BattlePass/users

When you delete empty files, please let me know - if that won't work, please send me your logs file again. I tested it and currently I can't recreate that problem

**Comment by iFranticman** [comment]
That's a lie i had one that said 0 i deleted it i will look out for more issues

**Comment by KPGTB** [comment]
> That's a lie i had one that said 0 i deleted it i will look out for more issues

Hey! Issue that your reported was caused by empty files/files with wrong content. Obe of the latest updates should fix it (these file should be skipped). If you still has this problem. Please send me your logs once again
