### ISSUE TITLE
whitelisted-regions do not work

### ISSUE THREAD

**Issue by Ekkoy06** [GC-spigot/battle-pass#501]
![imagine_2024-03-24_173601953](https://github.com/GC-spigot/battle-pass/assets/113153015/6c8364b0-647c-4fb6-8a5a-662f48921f36)
### Describe the bug

Hi, a few days ago you add this feature (whitelisted-regions, blacklisted-regions, whitelisted-worlds and blacklisted-worlds).
I tried to make a quest (in daily and weekly), but this feature do not work

plugin ver: 4.2.19
server version: 1.20.1 (paper, build 196)

### How to reproduce

```  1:
    name: 'test'
    type: kill-mob
    variable: vindicator
    whitelisted-regions: ["dt"]
    required-progress: 1000
    points: 1500
    item:
      material: head:eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYWMxYWFlZjZkY2Q4ODBhNzllY2FmYjNiYzM3OGVjODM1YTE3ODM1NTk1ZjdjY2JiNDUzMTc4YzY4OTQ2Yzk5NiJ9fX0=
      amount: 1
      name: '&ftest'
      lore:
        - ''
        - '&c➥ &fProgres: &c%total_progress%&f/&c%required_progress%'
        - ''
        - '&c➥ &eT-XP: &31.500'
        - ''

**Comment by KPGTB** [comment]
Hey! I fixed that problem. Fix will be available in the next update

**Comment by Ekkoy06** [comment]
> Hey! I fixed that problem. Fix will be available in the next update

sorry to reply here, but still don't work this feature

**Comment by KPGTB** [comment]
Hey! I tested it and it should work, but I'll test it once again today tonight

**Comment by KPGTB** [comment]
Hey! It seems that your problem is caused due to sync error which has been described by @GC-spigot in #507 It will be fixed as soon as possible

**Comment by KPGTB** [comment]
Hey! Can you check if it works in the latest version? (4.3.4)

**Comment by Ekkoy06** [comment]
hello, yep, now works perfectly, ty sm ;3
