### ISSUE TITLE
Dump Items from gamepass bug

### ISSUE THREAD

**Issue by Rangelito1** [GC-spigot/battle-pass#505]
### Describe the bug

Hi, recently a lot of people in my server report to me a bug to obtain the items from the battlepass menu in the player inventory and use it as normal vanilla items

https://github.com/GC-spigot/battle-pass/assets/75523966/8852170b-5b73-42ff-adf6-9358742f3d82

### How to reproduce

open the battlepass menu and shift click multiple times any slot, then press esc
![imagen_2024-03-26_163943727](https://github.com/GC-spigot/battle-pass/assets/75523966/569ebd81-46b5-475b-8f90-ee026e64d82c)

**Comment by KPGTB** [comment]
Hey! Problem has been fixed. It seems that error was only in the creative mode - players in survival mode couldn't use these items. Fix will be available in the next update
