### ISSUE TITLE
Using latest version wipes out all progress made.

### ISSUE THREAD

**Issue by dahbawz** [GC-spigot/battle-pass#506]
### Describe the bug

After updating battlepass from4.2.4 to 4.2.19, all players lose their progress.
If I go to the file "users" their history is still there, but get's overwritten by a new uuid file.

### How to reproduce

Update to newest version.

**Comment by KPGTB** [comment]
Hey! We will try to find this issue as soon as possible. Can you tell me what do you mean by "get's overwritten by a new uuid file."? It's just a new file? (old stays), or it removes old file and creates new one?

**Comment by KPGTB** [comment]
I'm asking, because I made it like you described (I updated from 4.2.4 to latest) and I don't see any problem with progress

**Comment by dahbawz** [comment]
The files were getting overwritten. 

You probably can't reprrduce, because after I reported it here on github, the plugin was quickly updated:
![image](https://github.com/GC-spigot/battle-pass/assets/16670770/19dbc401-1a8e-4029-9957-4c810c2c30b4)

**Comment by KPGTB** [comment]
That bugfix doesn't fix your issue. I don't know why plugin overrides your files

**Comment by dahbawz** [comment]
Just tested the newest version
Again everything get overwritten. 

no errors in console.

De plugin creates a new UUID file under "user" (database) en overlaps the old one. Everybody who is in week 9-10-11-12 is ressetted to week 1

**Comment by dahbawz** [comment]
it makes people able to redo the quests over again but it still maintained the proper tiers

**Comment by KPGTB** [comment]
Hey! Could you send me some users data files which hasn't been overwritten yet? Maybe there is something unusual in these files? If you don't want to share it publicly on github, you can send me these files on discord `kpgtb`

**Comment by KPGTB** [comment]
Hey! I finally found the issue thanks to #520. Problem will be fixed in the next update (you can use buckup to get old user data files)

**Comment by dahbawz** [comment]
> Hey! I finally found the issue thanks to #520. Problem will be fixed in the next update (you can use buckup to get old user data files)

That is fantastic news!
