### ISSUE TITLE
Read placeholders in the titles, next level for custom gui's

### ISSUE THREAD

**Issue by Mercurick** [GC-spigot/battle-pass#507]
### Describe the feature

All of the placeholders doesnt works in menu titles. It will be good if these can be parsed there. Some features in GUI like text over the textures will make sense, this can make new level of gui interactions for players.
![Снимок экрана 2024-04-01 165210](https://github.com/GC-spigot/battle-pass/assets/133431929/c0a890c3-389b-497f-bfba-d672e034d204)
![Снимок экрана 2024-04-01 165236](https://github.com/GC-spigot/battle-pass/assets/133431929/975cda87-7170-49f0-b6e0-d532afc9c1b3)

**Comment by Mercurick** [comment]
Or we can animate textures with placeholderapi's javascript addon.

**Comment by KPGTB** [comment]
Hey! I added placeholders to menus title. It will be available in the next update. I added these placeholders which you can use in menu items. To get i.e. player name, you'll need to use `PlaceholdersAPI` with `Player` extension and use `%player_name%` placeholder

**Comment by Mercurick** [comment]
Thank you so much!

**Comment by Mercurick** [comment]
![Снимок экрана 2024-04-09 001807](https://github.com/GC-spigot/battle-pass/assets/133431929/00cb9db6-817c-4d2a-8144-8d7f6d6403d5)
It's not working :(

**Comment by Mercurick** [comment]
> Hey! I added placeholders to menus title. It will be available in the next update. I added these placeholders which you can use in menu items. To get i.e. player name, you'll need to use `PlaceholdersAPI` with `Player` extension and use `%player_name%` placeholder

![image](https://github.com/GC-spigot/battle-pass/assets/133431929/976980dd-d6c6-49fe-95dd-89a9e5a5080f)

**Comment by Mercurick** [comment]
I'm have expansion Player btw. And standart BattlePass placeholders doesnt works too :(

**Comment by GC-spigot** [comment]
Hey! This will be fixed asap, for some reason my cloud sync program failed to sync new updates correctly. Sorry about inconvenience!

**Comment by Mercurick** [comment]
> olders to menus title. It will be available in the next update. I added these placeholders which you can use in menu items. To get i.e. play

Oh ok <3
