### ISSUE TITLE
Sound Console Error Bug

### ISSUE THREAD

**Issue by PirataGu** [GC-spigot/battle-pass#508]
### Describe the bug

[13:23:53 ERROR]: [BattlePass] Incorrect sound format. Must me specified as such: NAME:volume:pitch.
This error is appearing in my console
But
The sound is working well
'[sound] {UI_BUTTON_CLICK:0.5:1.3}'
and here is the config of the item in the menu that is doing this
oh AND every each one...
but here is one of them

### How to reproduce

Just put any sound on a menu item action and it appears on the console. With any sound and its costumizations.

**Comment by KPGTB** [comment]
Hey! I fixed that issue. Fix will be available in the next update
