### ISSUE TITLE
Big console error

### ISSUE THREAD

**Issue by xProMDFKx** [GC-spigot/battle-pass#511]
### Describe the bug

Basically, this bug just fills your console with errors like: 

[message.txt](https://github.com/GC-spigot/battle-pass/files/14903039/message.txt)

### How to reproduce

To reproduce this bug you just need to configure a quest from a week (i am not sure if it depends if you configure with hex colors or normal colors), and after that the error appears when you finish atleast one quets from that week and the item quest that you finished is replaced with that barrier in the GUI menu - and each time you open that quests menu that has that barrier the error appears in console, but it doesn't happen if there is no barrier (i use rgb/hex colors)

### Server Log

https://mclo.gs/9X9mBcw

**Comment by KPGTB** [comment]
Duplication of #510
