### ISSUE TITLE
Lastest Version Item menu Console Error

### ISSUE THREAD

**Issue by PirataGu** [GC-spigot/battle-pass#514]
### Describe the bug

This appears on the console (some items appear as Barrier: DIAMOND_BOOTS for example) 
[message(6).txt](https://github.com/GC-spigot/battle-pass/files/14907509/message.6.txt)

### How to reproduce

idk... just join the server with some Weekly Missions activated with the items that is presented in the error i think.

**Comment by PirataGu** [comment]
![Captura de ecrã 2024-04-08 222624](https://github.com/GC-spigot/battle-pass/assets/30275479/db70e9ea-4f80-4462-a27a-22e43e541484)
In this picture is a mission where I use diamond boots as the item. It erases the name and lore and no one can see what mission is... Btw this mission was working in a version before the latest. (All missions were)

**Comment by KPGTB** [comment]
Duplication of #510
