### ISSUE TITLE
Quests error

### ISSUE THREAD

**Issue by Yurkhun** [GC-spigot/battle-pass#516]
### Describe the bug

Every time a player open the quests menu it just spamm lots of errors in console, I tried deleting all quests files for the plugin to generate again, but the bugs still persist 

### How to reproduce

Just open quests menu and it appears in consol

### Screenshots / Videos

https://i.imgur.com/3HKM0yS.png

### Server Log

https://mcpaste.io/f251424f82ae710a

**Comment by KPGTB** [comment]
Hey! Problem has been already resolved. Fix will be available in the next update. You can also use simple fix to make it work on current version as described in #510
