### ISSUE TITLE
Using Latest version reset the quest progress

### ISSUE THREAD

**Issue by TechGe3ks** [GC-spigot/battle-pass#520]
### Describe the bug

I upgraded to the latest version on spigot and when I went to log in, all my progress had been reset.

When I looked add the JSON data from a backup and compare it with the way the json data showed in the database currently I  noticed there was an alteration.

Old:
{"uuid":"707a894c-445a-4f7b-ab78-b175fb39d8a9","quests":"{\"a\":{\"week-7\":{\"11\":5,\"1\":274,\"12\":9,\"2\":3,\"13\":30,\"6\":9,\"9\":16881},\"week-6\":{\"1\":275,\"13\":24,\"3\":3,\"6\":294,\"7\":500,\"8\":2010,\"9\":20000,\"10\":18},\"week-5\":{\"1\":4579,\"13\":19,\"2\":5,\"14\":1,\"3\":3,\"5\":6,\"6\":523,\"7\":200,\"8\":2220,\"9\":10000},\"week-4\":{\"11\":500,\"1\":18,\"14\":300,\"3\":10,\"6\":500,\"7\":5000,\"9\":4},\"week-3\":{\"11\":7,\"1\":1893,\"12\":12,\"13\":110,\"14\":200,\"4\":1,\"6\":702,\"7\":5,\"9\":50000,\"10\":100},\"week-2\":{\"11\":746,\"1\":7,\"13\":26837,\"2\":1,\"3\":10,\"5\":1,\"6\":1,\"7\":50000,\"8\":64,\"10\":200},\"daily\":{\"4\":735,\"7\":1},\"week-1\":{\"11\":27,\"12\":702,\"13\":1,\"14\":5500,\"1\":1898,\"2\":256,\"3\":7,\"5\":1,\"6\":702,\"7\":5,\"8\":18,\"9\":50000,\"10\":100}}}","pass-id":"premium","tier":14,"points":"125","currency":"0","bypass-locked-weeks":false,"pending-rewards":"{\"premium\":[1,2,3,4,5,6,7,8,9,10,11,12,13,14],\"free\":[2,3,4,6,8,10,12,14]}","claimed-rewards":"{}"}

New:
{
    "uuid": "707a894c-445a-4f7b-ab78-b175fb39d8a9",
    "quests": "{\"p\":{\"daily\":{\"7\":1}}}",
    "pass-id": "premium",
    "tier": 14,
    "points": "150",
    "currency": "0",
    "bypass-locked-weeks": false,
    "pending-rewards": "{\"premium\":[1,2,3,4,5,6,7,8,9,10,11,12,13,14],\"free\":[2,3,4,6,8,10,12,14]}",
    "claimed-rewards": "{}"
}

It seems that it may be looking for the "p" value from the json and when not finding it(because it was an a) it is resetting the progress of that player

### How to reproduce

Use mysql and use a version earlier then the current. And make progress towards a quest.

Leave the server and restart the server with the latest version and you will see that your progress has been reset.

**Comment by KPGTB** [comment]
Hey! Fix will be available in the next update.

**Comment by TechGe3ks** [comment]
Question, will I need to do any massaging of data in order to support the coming update?

**Comment by TechGe3ks** [comment]
Such as changing the value of “p” back to “a” for all the quest json
