### ISSUE TITLE
Gradient Support for colors

### ISSUE THREAD

**Issue by OfficialBlueseph** [GC-spigot/battle-pass#522]
### Describe the feature

Hello, I'd like to request the ability to **use gradients** in formatting options within Battlepass.
Particularly **in the rewards.yml** but this could be useful other areas as well such as menus.

**Use Suggestion:**
- Formatting similar to this: `{#2ee600>}Battlepass{#e60060<}` could be used to create a smooth transition between the 2 provided colors.
- Optionally, something similar to this: `{#2ee600>}Battle{#568260<>}pass{#e60060<}` could be used to blend 3 or more colors into eachother.

Please note what I've suggested is just a concept of how it _could_ be implemented - Any formatting resulting in gradient use will work. :)

Thanks for your time!

**Comment by KPGTB** [comment]
Hey! I added gradient support. It will be available in the next update

Gradient syntax
```
<gradient:FIRST_COLOR,SECOND_COLOR>TEXT</gradient>
```

Example

```
<gradient:#FF0000,#0000FF>Okay?</gradient>
```

It supports only 2 colors

**Comment by OfficialBlueseph** [comment]
Thank you very much! :)
