### ISSUE TITLE
Reloading causes Overloaded resources

### ISSUE THREAD

**Issue by Celipa** [GC-spigot/battle-pass#525]
### Describe the bug

Me and my team have set up battlepass on our testing server so we can use it on our main server in a few days, however this has become a repeating issue that is very concerning, in the video i am spamming the command but spamming is not needed, it was just to hasten the process. All it takes is 2-3 reloads with 5 minute intervals for this issue to begin.
Basically, when you reload the Battlepass plugin, it will eventually begin to spam a warning message in console about being overloaded or resource limits reached. you can see videos, images and the log below.

### How to reproduce

All we need to do to reproduce this bug is simply using /bpa reload a few times and the server will stop responding to normal actions like talking in chat or running certain commands. That's when the yellow warning message has begun and eventually after a while of spamming console the server crashes and restarts. Which it then boots up like normal and everything is okay again.

### Screenshots / Videos

https://gyazo.com/20fed41ea43dbb17985a4d03287b9f0a
https://gyazo.com/62fb1a3d8ab61c697f061e4628fe2c54

![image](https://github.com/GC-spigot/battle-pass/assets/143783754/d45dce3d-ce89-4e7b-b2a7-9ec1cbd390db)

### Server Log

https://mcpaste.io/59bf78ef2cb5b93a

**Comment by Celipa** [comment]
Did some more debugging, and we found out that the the plugin seems to be slowly making a ton of pids which causes the server to crash due to the docker instance it's running on hitting it's max pids.
@KPGTB 

We tested with battlepass disabled as well and it stopped increasing in pids once battlepass was disabled.

**Comment by KPGTB** [comment]
Hey! I tested it multiple times and I still can't reproduce that problem. Maybe there are some settings in pterodactyl panel which causes that problem with our plugin? Did you configure anything about cpu, pids etc on your pterodactyl panel or it's just ptero with default settings? Also how did you make debugging?

**Comment by PKBCRAFT** [comment]
Hello, I am adding here some more info from my console cause I am able to reproduce this issue for months.
Yeah, most likely it's something with pterodactyl.

CONSOLE:
`>....[1233.630s][warning][os,thread] Failed to start thread "Unknown thread" - pthread_create failed (EAGAIN) for attributes: stacksize: 1024k, guardsize: 0k, detached.
[1233.631s][warning][os,thread] Failed to start thread "Unknown thread" - pthread_create failed (EAGAIN) for attributes: stacksize: 1024k, guardsize: 0k, detached.
[1233.632s][warning][os,thread] Failed to start thread "Unknown thread" - pthread_create failed (EAGAIN) for attributes: stacksize: 1024k, guardsize: 0k, detached.
[1233.639s][warning][os,thread] Failed to start thread "Unknown thread" - pthread_create failed (EAGAIN) for attributes: stacksize: 1024k, guardsize: 0k, detached.
[1233.640s][warning][os,thread] Failed to start thread "Unknown thread" - pthread_create failed (EAGAIN) for attributes: stacksize: 1024k, guardsize: 0k, detached.
[1233.640s][warning][os,thread] Failed to start thread "Unknown thread" - pthread_create failed (EAGAIN) for attributes: stacksize: 1024k, guardsize: 0k, detached.
[1233.640s][warning][os,thread] Failed to start thread "Unknown thread" - pthread_create failed (EAGAIN) for attributes: stacksize: 1024k, guardsize: 0k, detached.
[1233.643s][warning][os,thread] Failed to start thread "Unknown thread" - pthread_create failed (EAGAIN) for attributes: stacksize: 1024k, guardsize: 0k, detached.
[1233.643s][warning][os,thread] Failed to start thread "Unknown thread" - pthread_create failed (EAGAIN) for attributes: stacksize: 1024k, guardsize: 0k, detached.
[1233.643s][warning][os,thread] Failed to start thread "Unknown thread" - pthread_create failed (EAGAIN) for attributes: stacksize: 1024k, guardsize: 0k, detached.
[1233.643s][warning][os,thread] Failed to start thread "Unknown thread" - pthread_create failed (EAGAIN) for attributes: stacksize: 1024k, gu`

And I also attached a screenshot from pterodactyl. 
![panel](https://github.com/GC-spigot/battle-pass/assets/147991120/ffe0aa8d-80ca-4d34-b4cc-2b7a2aa44f55)

**Comment by KPGTB** [comment]
Can you show me your wings configuration file? Ofc, you can hide sensitive data

**Comment by Celipa** [comment]
> Hey! I tested it multiple times and I still can't reproduce that problem. Maybe there are some settings in pterodactyl panel which causes that problem with our plugin? Did you configure anything about cpu, pids etc on your pterodactyl panel or it's just ptero with default settings? Also how did you make debugging?

So i had been noticing that reloading would cause the server to crash.
And one of our devs went into putty and wrote in container docker stats, which showed all our servers and their memory usage and such, it also showed pids (which the image above from the other guy mentions)
My dev had me restart the server, so he could see how the servers resources were used right after a restart. they seemed normal up to the point where i joined the server which then the pids jumped up a bit. and when i was just idle we noticed the pids continued going up (when it's supposed to stay around the same number with a +/- 1 to 3 pids fluctuate.) 

So then i tried reloading the plugin which made the pids jump from example: 260 pids to 289 pids in the matter of a minute.
reloading shouldnt be taking up that much to begin with, but even after the reload were done, it increases constantly.
So when reloading 1-5 times, it cause the resources to max out at 512 pids, which then it can't process any more resources and the server goes into a crash cycle of trying to create new threads but failing. 
Console begins spamming the same error message as   [PKBCRAFT] pasted in the comment above. as well as ''Is the server Overloaded?''
And after a while it just begins to restart itself.

Ive been able to replicate this over and over again. And so have many other server owners that have used battlepass. Im not so sure it is pteradactyl because if we were to increase the container_pid_limit in the wings it would only be putting a bandaid on the problem.
My server is expected to be able to handle more and more players the upcoming months, and if each player increases the pid amount with 20-30 pids each, it's just a matter of time until the server crashes again.

**Comment by Celipa** [comment]
we are using default pteradactyl configuration btw.

**Comment by Celipa** [comment]
@KPGTB any updates?

**Comment by KPGTB** [comment]
Hey! I finally reproduced your problem. We will be working on fixing it

**Comment by KPGTB** [comment]
Hey! Finally I probably fixed this problem. You can check it in one of the next updates

**Comment by Celipa** [comment]
yeah it got fixed, Thank you!!!!
