### ISSUE TITLE
Chat bug with advancedchat version 1.19

### ISSUE THREAD

**Issue by Sizzle08** [GC-spigot/battle-pass#526]
### Describe the bug

Basically whenever I type something in chat on 1.19 it puts a ton of permissions in chat above my message 
![help](https://github.com/GC-spigot/battle-pass/assets/140993362/10ded970-be44-402e-bb86-74d746ad497a)

### How to reproduce

Whenever you type something in chat on 1.19 server this will happen even without changing any config I attached a picture of the problem I am having 

### Screenshots / Videos

![help](https://github.com/GC-spigot/battle-pass/assets/140993362/3c79f034-00b7-4fd1-b8bc-e0a824d69459)

**Comment by KPGTB** [comment]
Hey! Please report this bug on advancedchat github page -> https://github.com/AdvancedPlugins/Chat/issues
