### ISSUE TITLE
Folia support...

### ISSUE THREAD

**Issue by roggy666** [GC-spigot/battle-pass#528]
### Describe the feature

Please, add folia support... I am tired by waiting...

**Comment by KPGTB** [comment]
Hey! I added basic Folia support to BattlePass plugin, but due to some changes, we need to make more tests before publishing it

**Comment by Raidware** [comment]
> Hey! I added basic Folia support to BattlePass plugin, but due to some changes, we need to make more tests before publishing it

How can i  test?

**Comment by KPGTB** [comment]
Hey! Currently, we are testing this update. When we publish it, you will be able to test it by yourself
