### ISSUE TITLE
Nobody can open weekly quests in GUI

### ISSUE THREAD

**Issue by Nunchakin** [GC-spigot/battle-pass#529]
### Describe the bug

Nobody (we tested admins with allowed bypass) can open weekly quests. (as soon as I lock bypass, I cant even click the first week, it says I have to complete the previous week...)
https://pastebin.com/hdKE50Zz

### How to reproduce

I have no idea, it worked, but for some reason it stopped working... 

### Screenshots / Videos

https://www.youtube.com/watch?v=GM7s24gMQ84

**Comment by Nunchakin** [comment]
Update: not even regular players that had never gotten bypass can open each quests, it tells them ("you have to complete the previous week)

**Comment by Nunchakin** [comment]
Sure!
Week quests configuration (only first and second yet): https://pastebin.com/P2athjWK https://pastebin.com/zCFtFepC
Week menu:  https://pastebin.com/8mh2rSfR

**Comment by KPGTB** [comment]
Hey! In week menu config, in line 207, you set `name: []`. You need to change it to `name: ""`. It caused your error

**Comment by Nunchakin** [comment]
Thank you very much!
