### ISSUE TITLE
Custom heads bugging in quest-overview.yml

### ISSUE THREAD

**Issue by Nunchakin** [GC-spigot/battle-pass#530]
### Describe the bug

Hey! I use custom heads for menus and they work fine, but they "blick" or bug in quest-overview.yml menu as recorded in the video below. 

### How to reproduce

Set custom heads to quest-overview.yml menu and open  it.

### Screenshots / Videos

https://www.youtube.com/watch?v=-UN0LTZnOyE

### Server Log

https://pastebin.com/yA05Ku91

**Comment by KPGTB** [comment]
Hey! Which version of BattlePass and Minecraft do you use?

**Comment by Nunchakin** [comment]
BattlePass-4.4.1
paper-1.20.4-496

**Comment by KPGTB** [comment]
Hey! I can't still reproduce that problem, but I added small update for skull creator which should optimize the entire process. It will be available in one of the next update. I'll let you know when it will be updated and please check it after that

**Comment by Nunchakin** [comment]
Okay sure!

**Comment by Nunchakin** [comment]
Fixed!
Thank you very much.
