### ISSUE TITLE
battlepass editor command error

### ISSUE THREAD

**Issue by HoKKaiDo97** [GC-spigot/battle-pass#531]
### Describe the bug

after installation i tried to use /bpa editor command and then i got a whole lot of error.

### How to reproduce

after installation i tried to use /bpa editor command and then i got a whole lot of error.
Server Version 1.20.4 purpur

### Server Log

https://mcpaste.io/b8350ba3635e31dc

**Comment by KPGTB** [comment]
Hey! Fix will be available in the next update

**Comment by HoKKaiDo97** [comment]
Thankyou!

This issue is Closed as Completed!
