### ISSUE TITLE
Effect regenerate doesn't work for a Battlepas

### ISSUE THREAD

**Issue by dahbawz** [GC-spigot/battle-pass#532]
### Describe the bug

Quest doesn't work

after makign a ticket on the discord, they told me to make a bug issue here.

![image](https://github.com/GC-spigot/battle-pass/assets/16670770/e07f9f0b-088e-41c4-a405-ad90b182d73b)

![image](https://github.com/GC-spigot/battle-pass/assets/16670770/ff7e9d0f-8906-4eaa-a7ee-cc4cda278017)

![image](https://github.com/GC-spigot/battle-pass/assets/16670770/b028dbfe-f6c2-4443-8b1f-a7dfb329148c)

### How to reproduce

Using latetest version of battlepas, using paper mc 1.19.4

**Comment by KPGTB** [comment]
Hey! In your case, you should use `root: SATIATED`
```
SATIATED - When a player regains health from regenerating due to their hunger being satisfied
```
`EATING` is triggered when health is regenerated directly from eating. There is probably small mistake in dpigot docs, because itsn't only for players - it's mostly for animals. You can i.e, regenerate health of tamed wolf by giving him food - it triggers `EATING`

**Comment by dahbawz** [comment]
Oke thank you,

so it will become:

 7:
    name: 'Niveau 12 - Appelplukker II'
    type: regenerate
    root: SATIATED
    variable: EATING
    required-progress: 200
    points: 267
    item:
      material: APPLE:0
      
      ?



> Hey! In your case, you should use `root: SATIATED`
> 
> ```
> SATIATED - When a player regains health from regenerating due to their hunger being satisfied
> ```
> 
> `EATING` is triggered when health is regenerated directly from eating. There is probably small mistake in spigot docs, because it isn't only for players - it's mostly for animals. You can i.e. regenerate health of tamed wolf by giving him food - it triggers `EATING`



Oke thank you,

so it will become:

 7:
    name: 'Niveau 12 - Appelplukker II'
    type: regenerate
    root: SATIATED
    variable: EATING
    required-progress: 200
    points: 267
    item:
      material: APPLE:0
      
      ?

**Comment by KPGTB** [comment]
Oh, sorry, just `variable: SATIATED`

**Comment by dahbawz** [comment]
Thank you!
