### ISSUE TITLE
error consol on start server

### ISSUE THREAD

**Issue by googleWKL** [GC-spigot/battle-pass#533]
### Describe the bug

When i start my server i have this error on my consol

### How to reproduce

restart or start the server

### Server Log

https://mcpaste.io/5c1d9f143356d3a6

**Comment by KPGTB** [comment]
Hey! Can you check if this error still exists in the latest version of battlepass? (4.4.1)

**Comment by googleWKL** [comment]
yes, it is still
And when i craft any item i have this error : https://mcpaste.io/f6759a22d2f34296

**Comment by KPGTB** [comment]
Sorry, but we support only versions from 1.17. It seems that you use 1.8 which isn't supported

**Comment by googleWKL** [comment]
Do you think that's where the mistake came from? 
you can close this after the answer

**Comment by KPGTB** [comment]
> Do you think that's where the mistake came from? you can close this after the answer

Yeah, it works fine on supported versions
