### ISSUE TITLE
ItemsAdder image parse in title/actionbar

### ISSUE THREAD

**Issue by Jackerugo** [GC-spigot/battle-pass#534]
### Describe the feature

Add support for parsing ItemsAdder images through titles/actionbar. These parse fine in chat messages as shown in screenshots however not in titles or actionbar messages. If 'chat and actionbar' is enabled for quest updates it shows the image in chat but the placeholder on actionbar/title.

![2024-05-11_14 11 49](https://github.com/GC-spigot/battle-pass/assets/37919015/982ea93e-cdef-412d-b23d-6ea5e9a00e56)
![2024-05-11_14 12 54](https://github.com/GC-spigot/battle-pass/assets/37919015/36f36c00-8354-4fb7-bcc2-1a9305effde3)

**Comment by KPGTB** [comment]
Hey! I added PlaceholderAPI to these messages. It will be available in the next update

**Comment by Jackerugo** [comment]
> Hey! I added PlaceholderAPI to these messages. It will be available in the next update

Hi! Was this merged to latest update? This is still occuring in 4.4.2 released yesterday.
