### ISSUE TITLE
CrateReloaded not working

### ISSUE THREAD

**Issue by ArefyNetwork** [GC-spigot/battle-pass#536]
### Describe the bug

CrateReloaded type quest isn't working, using latest versions of both plugins (BattlePass-4.3.6, and CrateReloaded 2.3.9-hotfix)

### How to reproduce

Creating a quest with cratereloaded type:

  10: 
    name: 'Week 5 - Tags' 
    type: cratereloaded_open
    variable: 'Tags'
    required-progress: 10
    points: 160
    item: 
      material: tripwire_hook:0
      amount: 1
      name: '&e&lLLAVES TAGS'
      lore:
        - '&7&o(( Abre &f&o10 llaves tags &7&oen &f&o/crates &7&o))'
        - ''
        - '&e&lINFORMACIÓN'
        - '&8 ❙ &7Progreso: &a%total_progress%&8/%required_progress%' 
        - '&8 ❙ &7EXP: &f+100'

**Comment by KPGTB** [comment]
Hey! Fix will be available in one of the next updates
