### ISSUE TITLE
Milking cow can be done even without actual milking - just clicking the ocw with bucket

### ISSUE THREAD

**Issue by bobhenl** [GC-spigot/battle-pass#537]
### Describe the bug

Hello, I got this report by the player:
>  By the way, you can also do the milking challenge faster (from battlepass) by clicking on the cow multiple times using a bucket before you get a milk bucket

### How to reproduce

Try to milk the cow with bucket but just click on it without actually milking it

**Comment by KPGTB** [comment]
Hey! Fix will be available in the next update
