### ISSUE TITLE
bedrock menu

### ISSUE THREAD

**Issue by brunoR1000** [GC-spigot/battle-pass#539]
### Describe the feature

Since we don't have a menu for bedrock, we can create one using CrossPlatforms, but we need a command that directly opens the weekly missions, or new placeholders that tell us the description and progression of the mission, for example %quest_week_[weekActive]_[QuestID ]%

**Comment by KPGTB** [comment]
Hey! I added command `/bp open week <weekId>`. It will be available in the next update

**Comment by brunoR1000** [comment]
Oh Men, you're the Boss, thanks for ALL!


Em qua., 5 de jun. de 2024, 15:49, KPG-TB ***@***.***>
escreveu:
