### ISSUE TITLE
what is compatible version for 1.8.9 paper?

### ISSUE THREAD

**Issue by hungdx-t1** [GC-spigot/battle-pass#540]
### Describe the bug

I have installed latest version of BattlePass (v4.4.6) in my 1.8.9 paper server, but when i initialize new data, i have many error code that appear as in photos. I think that version is not compatible for my server, and can i fix this issue?

### How to reproduce

Install new version and run but have many error code.

### Screenshots / Videos

[
![Screenshot 2024-06-04 182601](https://github.com/GC-spigot/battle-pass/assets/168153034/b52457a9-1fc3-44b8-aa45-f62d18227082)
](url)

**Comment by KPGTB** [comment]
The last version which supports minecraft 1.8.9 is 4.1.4
