### ISSUE TITLE
Next page button doesn't work

### ISSUE THREAD

**Issue by Nunchakin** [GC-spigot/battle-pass#541]
### Describe the bug

Next page button in week.yml doesn't work. I have it configured by myself but it doesn't even work when I regenerated the file and kept it.

Settings.yml: https://pastebin.com/Ln1r39Ay

menu:
  '39':
    item:
      material: arrow:0
      name: '&f&l<- &ePředchozí stránka'
      lore: ''
    actions:
      - '[menu](page = 1) {quest-overview}' # If the page is 1, take them to the portal page
      - '[menu](page ! 1) {previous-page}' # If their page is not 1, take them to the previous page
  '41':
    item:
      material: arrow:0
      name: '&eDalší stránka &f&l->'
      lore: ''
    actions:
      - '[menu] {next-page}'

### How to reproduce

idk try next page in the latest version
BattlePass: [4.4.6]
Version: This server is running Paper version git-Paper-496 (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT) (Git: 7ac24a1 on ver/1.20.4)
/bpa reload: https://pastebin.com/JzC1nW9a

### Screenshots / Videos

![weeks](https://github.com/GC-spigot/battle-pass/assets/151460657/e72b364e-9018-44d2-8322-8d507510ee29)
https://youtu.be/nNSn2HZGmFg

**Comment by KPGTB** [comment]
Hey! I can't reproduce your problem. Can you send me quest configuration files and menu configuration files?

**Comment by Nunchakin** [comment]
Sure! Sent all BP files on your Discord server: battlepass-1707 TICKET

**Comment by KPGTB** [comment]
I checked these files. In every week you have 8 quests which are visible on first page of week. When you add more quests to week, next page button will move you to next page of week.

**Comment by Nunchakin** [comment]
Hey! Thank you very much for your time! Can I request you to fix this? I really want to have 8 quests, I will disable this button right now, but I'm asking for the future, thanks.
