### ISSUE TITLE
Adding items with specific nbt data into variable

### ISSUE THREAD

**Issue by VOIDDERtm** [GC-spigot/battle-pass#543]
### Describe the bug

How to add a mushroom block with nbt to a block breaking task?
minecraft:brown_mushroom_block[down=false;east=false;north=false;south=true;up=false;west=true]
The essence of the issue lies in the nbt of the block.
The mushroom block has 160 nbt variations, which allows you to make custom ores through it, which was implemented. But at the same time, it is not clear in the task how to specify nbt tags in the block itself.
https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html
BROWN_MUSHROOM_BLOCK
BlockData: MultipleFacing

### How to reproduce

daily-quests.yml:

quests:
  1: # Quest id
    type: block-break
    variable: brown_mushroom_block[down=false;east=false;north=false;south=true;up=false;west=true]
    name: 'CustomBlock'
    required-progress: 9
    points: 10
    item:
      material: iron_pickaxe
      name: '&a&lQuest: &fCustomBlock'

### Screenshots / Videos

https://media.discordapp.net/attachments/1250353158199185459/1250354308998762560/image.png?ex=666bf431&is=666aa2b1&hm=65c9d53303790d88fc29fa55b54ba83ef8818e1912b9082f7597a40f572619ce&=&format=webp&quality=lossless&width=907&height=499

https://media.discordapp.net/attachments/1250353158199185459/1250354309531570247/image.png?ex=666bf431&is=666aa2b1&hm=0dd89ad591212ad62df7b32446d9e55f4f208ceb699109ce35f4ab81969edffd&=&format=webp&quality=lossless&width=907&height=499

minecraft:brown_mushroom_block[down=false;east=false;north=false;south=false;up=false;west=true]

minecraft:brown_mushroom_block[down=false;east=false;north=false;south=true;up=false;west=true]

**Comment by VOIDDERtm** [comment]
> Hey! Currently you can't use items with specific NBT data inside variables

The spigot api documents indicate that it can be used, nbt I call this out of habit, but this is called a block component, internal data.
https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html

**Comment by KPGTB** [comment]
I know that's possible to make it work, but currently our plugin doesn't support it

**Comment by VOIDDERtm** [comment]
> I know that's possible to make it work, but currently our plugin doesn't support it

Is it planned to be introduced?
If so, approximately when should we expect it (I’m surprised that no one has ever encountered this before)?

**Comment by KPGTB** [comment]
Hey! This feature will be available in one of the next larger updates 😉

**Comment by VOIDDERtm** [comment]
Thank!
