### ISSUE TITLE
Windows identifies new BattlePass version as a virus

### ISSUE THREAD

**Issue by Nunchakin** [GC-spigot/battle-pass#544]
### Describe the bug

The BattlePass version: BattlePass-4.4.9
It identifies it as Trojan:Script/Wacatac.B!ml

![image](https://github.com/GC-spigot/battle-pass/assets/151460657/ddac4791-198c-468d-97c5-de427860258b)
(in Czech language)

### How to reproduce

Download the latest BattlePass 4.4.9 version from Spigot and then try to upload it to WinSCP FTP client

**Comment by KPGTB** [comment]
Hey! We can't make anything with it. Please read more about that error on [official spigot page](https://www.spigotmc.org/threads/windows-defender-false-positives.639507/)
