### ISSUE TITLE
add hide attributes parametr

### ISSUE THREAD

**Issue by wundertraume** [GC-spigot/battle-pass#545]
### Describe the feature

![image](https://github.com/GC-spigot/battle-pass/assets/118831819/be29420a-780f-42eb-8bb4-cbaeefcea765)

**Comment by KPGTB** [comment]
Hey! Item attributes are already hidden. DO you use the latest version of BattlePass?

**Comment by KPGTB** [comment]
I finally recreated that problem. It seems that it's caused by 1.20.6 or 1.21 update. I'll try to fix it asap

**Comment by KPGTB** [comment]
Fix will be available in the next update
