### ISSUE TITLE
Bad API Documentation

### ISSUE THREAD

**Issue by RayBytes** [GC-spigot/battle-pass#546]
### Describe the feature

Please improve your API documentation, it seems very outdated and unusable. A java docs would even help.
At this stage, I ask for any example projects which use the battle pass API, so I can see how to model my own project to it, as currently standing the current API docs do not suffice.

**Comment by RayBytes** [comment]
I have also checked out the code in #483 as well, however the code didn't seem to work? Triggering the quest did nothing, unless im meant to prefix my custom quest types with something for it to be able to work in battlepass..

**Comment by RayBytes** [comment]
<img width="833" alt="Screenshot 2024-06-17 at 1 38 47 PM" src="https://github.com/GC-spigot/battle-pass/assets/108236317/be62a00a-3c9e-40f5-8051-04ac78864838">
I have also tried this code, which did not work either

**Comment by KPGTB** [comment]
@GC-spigot can you update docs?

Example of external quest

```java
public class ASkyblockQuests extends ActionQuestExecutor {

    public ASkyblockQuests(JavaPlugin plugin) {
        super(plugin, "askyblock");
    }

    @EventHandler(ignoreCancelled = true)
    public void onNewIsland(IslandNewEvent event) {
        Player player = event.getPlayer();
        String schematicName = event.getSchematicName().getName();
        if (schematicName == null) {
            return;
        }
        this.execute("create_island", player, result -> result.root(schematicName));
    }
}
```

registering:

```java
ActionRegistry registry = BattlePlugin.getPlugin().getActionRegistry();
registry.hook("ASkyblock", ASkyblockQuests::new);
```

action name: `askyblock_create_island`

**Comment by RayBytes** [comment]
@KPGTB Do you have an example of a internal quest?

**Comment by RayBytes** [comment]
@GC-spigot ?

**Comment by KPGTB** [comment]
> @KPGTB Do you have an example of a internal quest?

Internal quests are designed to use inside BattlePass plugin. If you are making external plugin, you should use external quests
