### ISSUE TITLE
error when opening external menus

### ISSUE THREAD

**Issue by Z3r0xh** [GC-spigot/battle-pass#547]
### Describe the bug

In the main menu of /bp I have a button to go to my menu created with zmenu.

in this one it looks like this

![image](https://github.com/GC-spigot/battle-pass/assets/138524212/5c297f93-9b60-4d04-b827-9d418c1f7c20)

If you look at the /bp, the slot that my button occupies to go to the /menu is slot 9

![image](https://github.com/GC-spigot/battle-pass/assets/138524212/86bbc1ed-e442-45b6-b267-834be46c3ac0)

When I click on slot 9 to return to the /menu, this same click is also automatically made in the /menu, by clicking on slot 9 of the /menu.

That is, you click on both the /bp menu and /menu

![image](https://github.com/GC-spigot/battle-pass/assets/138524212/0197e637-d2a7-4d59-bfb9-b69c6ff83cbd)

the problem is that when you open another menu before the pb closes and they overlap on top of each other

### How to reproduce

have a menu with zmenu, now in /bp add a button to open a zmenu menu in slot 9

In the zmenu create a button in slot 9 that performs some action.

When clicking on slot 9 in /bp this same click is also reproduced on the zmenu slot 9 button, making it impossible to show the zmenu menu

with other plugins it opens fine.

I had this problem with Urewards and the dev told me that it was a bug in how the external menus were opened

### Screenshots / Videos

https://www.youtube.com/watch?v=EzhX2da7TDM

*If you don't see the video well due to the quality, tell me and I'll upload it again.

**Comment by KPGTB** [comment]
Hey! I fixed this problem by adding option to set delay inside actions. After next update you will be able to open zmenu i.e. after 0.1s by setting action to `[console-command] <0.1> {zmenu open ...}`

**Comment by Z3r0xh** [comment]
> Hey! I fixed this problem by adding option to set delay inside actions. After next update you will be able to open zmenu i.e. after 0.1s by setting action to `[console-command] <0.1> {zmenu open ...}`

thank you so much! I already thought I was doing it wrong and I was getting frustrated.
