### ISSUE TITLE
Adding NBT properties to a variable & material

### ISSUE THREAD

**Issue by DrSlabber** [GC-spigot/battle-pass#549]
### Describe the bug

https://mcpaste.io/a7dd920ed73f3b38

Trying to create a quest to craft pokeballs - works fine with a default pokeball as it has a set ID in pixelmon. However since pixelmon defines different pokeballs (great/ultra/ect..) with NBTs I can't get them to register as the display material.. Haven't even tried to add all 3 as a variable yet 

### How to reproduce

https://mcpaste.io/a7dd920ed73f3b38

**Comment by KPGTB** [comment]
Hey! This feature will be available in one of the next larger updates 😉
