### ISSUE TITLE
booster placeholder

### ISSUE THREAD

**Issue by wundertraume** [GC-spigot/battle-pass#550]
### Describe the feature

Is there any placeholder for the presence of a booster in a player?

Could you add, because I don't want the player to be able to buy multiple identical boosters and I need to check for an existing booster

Thanks

**Comment by KPGTB** [comment]
Will be available in the next update

Syntax:
`%battlepass_has_booster_<SERVER/PLAYER/ANY>_<PROGRESS/POINTS/REWARDS/ANY>_<**PERCENT**/ANY>_<**AFFECTS**/ANY>%`

PERCENT - Booster percent
AFFECTS - Affects condition same as in booster command

Examples:

1. %battlepass_has_booster_player_any_any_week-1-2% - Returns `true` if player has any booster which affects exactly 2nd quest in 1st week.
2. %battlepass_has_booster_player_POINTS_10_all% - Returns `true` if player has points booster which adds 10% to all quests
3. %battlepass_has_booster_SERVER_ANY_100_ANY% - Returns `true` if server has any booster which adds 100%
