### ISSUE TITLE
Add option for giving no points for daily quests

### ISSUE THREAD

**Issue by Nunchakin** [GC-spigot/battle-pass#552]
### Describe the feature

I request to add option for daily quests to give no battlepass points, because it messes up with servers battlepass rewards settings. One weekly quest gives for example 10 points and daily quests points mess up with these numbers. Now when you set in daily quests points to 0, it writes a message:
"You have a broken quest.  Category: daily | ID: 1 | This quest's points reward is not set or is lower than one."

**Comment by KPGTB** [comment]
Will be added in one of the next updates

**Comment by Nunchakin** [comment]
hey, have you already added this?
