### ISSUE TITLE
Harvesting

### ISSUE THREAD

**Issue by DreamLandUA** [GC-spigot/battle-pass#553]
### Describe the bug

Hi, I haven't updated the plugin for a long time, but today I did and when loading the following error occurred in the console on the account of quests
I noticed it had something to do with harvest-crops

  20:
    name: 'Фермер'
    type: harvest-crops
    variable: carrots
    required-progress: 64
    points: 5
    item:
      material: iron_hoe
      name: '§2Фермер'
      lore:
        - '§fЗібрати 64 моркви.'
        - '§fПрогрес: §b%total_progress%&7/§b%required_progress%'
I planted carrots.
waited for them to grow and picked them.
but it didn't count.
an older version of the plugin had the same problem, but I wrote carrots and everything worked
it doesn't work now(

### How to reproduce

if I change the carrots to carrot parameter, the quest will not be credited to me

### Screenshots / Videos

![image](https://github.com/GC-spigot/battle-pass/assets/168473750/bd9156f4-53ed-4136-ab91-e8893250dedf)

### Server Log

https://mcpaste.io/0c8d5b93643cf4bc

**Comment by DreamLandUA** [comment]
Then what do you say?

**Comment by KPGTB** [comment]
> Then what do you say?

Hey! This bug will be fixed in the next larger update, which will rework the current variables system 😉
