### ISSUE TITLE
Shear colored sheep

### ISSUE THREAD

**Issue by leon37921** [GC-spigot/battle-pass#556]
### Describe the feature

The ability to specify the color as a variable for the quest-type: shear, so that a player has to shear 16 pink sheep, for example

**Comment by KPGTB** [comment]
Hey! `color` subroot will be available in the next update. Example usage:

```
variable:
    root: sheep
    color: pink
```

**Comment by leon37921** [comment]
> Hey! `color` subroot will be available in the next update. Example usage:
> 
> ```
> variable:
>     root: sheep
>     color: pink
> ```

hey, thanks for the quick implementation!
But I can't get it to work, sorry.
`This server is running Paper version git-Paper-435 (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT) (Git: 681bbff)`
Battlepass 4.5.6
PlaceholderAPI 2.11.6
no other plugins
no errors
```
type: shear
variable: 
  root: sheep
  color: pink
```

**Comment by KPGTB** [comment]
Hey @leon37921! I'm sorry, but I made small mistake - `root` is a custom name of entity - not type. So, just use

```
variable:
    root: none
    color: pink
```

and it will work

Sorry for the inconvenience,
kpg_tb
