### ISSUE TITLE
Use upper case in subroots

### ISSUE THREAD

**Issue by PirataGu** [GC-spigot/battle-pass#559]
### Describe the bug

Well if I try to enchant a Diamond Sword with this missions that I've created it doesnt count:

6:
    name: 'Week 7 - Encantador de Espadas'
    type: enchant
    variable:
      root: SHARPNESS
      item: DIAMOND_SWORD:0
    required-progress: 8
    points: 95

### How to reproduce

It doesnt count up the mission if you get sharpness in the diamond_sword

**Comment by KPGTB** [comment]
can you try:

`item: diamond_sword`

**Comment by PirataGu** [comment]
yep. It only works with tiny letters... Maybe still a bug? Or put an warning on the wiki at least

**Comment by KPGTB** [comment]
That's not a bug - technically it should work only with lower case, but don't worry, one of the next updates will add an option to use lower OR upper case

**Comment by KPGTB** [comment]
Hey! This feature will be available in one of the next larger updates 😉
