### ISSUE TITLE
BP Issue List

### ISSUE THREAD

**Issue by OJsGaming** [GC-spigot/battle-pass#56]
BP:
- Daily Quests Don't Refresh Automatically and Return to blank state after server restart
- Your own plugins in External Quest Types don't work but yet other external plugins like Lands work
- Pre-made configs listed in you wiki are outdated and broken
- Plot rate quest does not work**

**Comment by BroEdits** [comment]
Hi, Just a update on the "Pre-made configs listed in you wiki are outdated and broken" That has been resolved. Also I think Daily Quests have been fixed :)
`https://battlepass.advancedplugins.net/useful/premade-configurations`

**Comment by OJsGaming** [comment]
Brilliant thank you BroEdits!

**Comment by GC-spigot** [comment]
Fixed
