### ISSUE TITLE
The block-break option is not working for me.

### ISSUE THREAD

**Issue by jetrikx** [GC-spigot/battle-pass#561]
### Describe the bug

After adding the plugin to the server, I wanted to configure it, but first, I wanted to check how it works and if everything is functioning properly. It turned out that it doesn't count my progress with mining blocks.

### How to reproduce

The server is running on 1.17.1 Spigot. It only has the BattlePass plugin installed, nothing else, and it has the original configuration that comes with the plugin upon installation.

### Screenshots / Videos

Video : https://www.youtube.com/watch?v=D7x_Os69-lg

**Comment by KPGTB** [comment]
You won't get progress if broken block was placed by player. It's anti abuse system 😉

(You can also disable it in settings.yml `break-protection`)
