### ISSUE TITLE
Adding sorting of daily quests by difficulty

### ISSUE THREAD

**Issue by thesqu1d** [GC-spigot/battle-pass#562]
### Describe the feature

I would really like to see the sorting of daily quests by difficulty for those cases when you need to make quests with different difficulties and a different number of points issued. 

This feature would help evenly distribute an equal number of tasks with the same difficulty level and points to each player. 

For example, so that you can implement the following system for issuing daily quests:
- One Hard quest with a lot of points
- Two quests with less difficult execution and less points
- Two quests with medium difficulty and medium points
- Two quests with easy difficulty and small points.

This sorting system can be implemented in different ways, it is really sorely lacking in the plugin.

**Comment by KPGTB** [comment]
Hey! Feature will be available in one of the next updates. 

[Article on wiki will also be available soon](https://battlepass.advancedplugins.net/quests/daily-quests-difficulty)
