### ISSUE TITLE
It is not possible to put battelpass placeholders in tier lore

### ISSUE THREAD

**Issue by noaskers** [GC-spigot/battle-pass#566]
### Describe the bug

Hello its not possible to put battlepass placeholders in tier items (Locked, Unlocked, Claimed) 
![image](https://github.com/user-attachments/assets/abe8f69f-30ab-4fab-915b-826bafcf0609)

### How to reproduce

Put placeholder in battlepass tier item it won't work

### Screenshots / Videos

![image](https://github.com/user-attachments/assets/e4a7317c-9809-461f-9656-cfb2f04f585e)

**Comment by noaskers** [comment]
https://github.com/GC-spigot/battle-pass/issues/560

Not sure if this is the same issue! but looks like it!

**Comment by KPGTB** [comment]
Duplication of GC-spigot/battle-pass/issues/560
