### ISSUE TITLE
Add block with BlockStateTag send error

### ISSUE THREAD

**Issue by VOIDDERtm** [GC-spigot/battle-pass#567]
### Describe the bug

On quest send error:
  4:
    type: block-break
    variable: brown_mushroom_block{BlockStateTag:{down:"false",east:"false",north:"false",south:"false",up:"false",west:"true"}} OR brown_mushroom_block{BlockStateTag:{down:"false",east:"false",north:"false",south:"true",up:"false",west:"false"}}
    name: 'Рудокоп - Олово'
    required-progress: 76
    points: 10
    item:
      material: iron_nugget
      customModelData: 452
      name: '&a&lЗадание: &fРудокоп - Олово'
      lore:
        - '&7 » &7Для завершения задания, вы должны'
        - '&7 » &7Сломать %required_progress% блока руды.'
        - '&7Уровень добычи = 1'
        - ''
        - '&a&lИНФОРМАЦИЯ'
        - '&7 » &7Очков гильдии: &f10x'
        - '&7 » &7Прогресс (&a%percentage_progress%&7): &a%total_progress%&8/&c%required_progress%'

### How to reproduce

Minecraft command to give this block:
/give @p minecraft:brown_mushroom_block{BlockStateTag:{down:"false",east:"false",north:"false",south:"false",up:"false",west:"true"}}

### Server Log

https://mclo.gs/vlNARDV

**Comment by KPGTB** [comment]
Duplication of #543
