### ISSUE TITLE
Give points error

### ISSUE THREAD

**Issue by neviskcubo** [GC-spigot/battle-pass#568]
### Describe the bug

give command does not correctly deliver the points

### How to reproduce

Use /bpadmin to give points with a value greater than 100 and it will exceed the limit:
![image](https://github.com/user-attachments/assets/826bd9f3-605c-4844-8c1d-16e40e1f7127)

console error: https://mclo.gs/T4evHhL

**Comment by KPGTB** [comment]
Hey! You wrongly configured `tier-up-actions` in passes/free.yml or passes/premium.yml
