### ISSUE TITLE
Majority of Addons Do Not Work

### ISSUE THREAD

**Issue by James-Cotterill** [GC-spigot/battle-pass#57]
**Describe the bug**
Majority of addons failing to work making this plugin have very little functionality 

**To Reproduce**
Run the plugin with the same addons 

**Screenshots / Video**
https://pastebin.com/7WmXqjFb

**Server Information (please complete the following information):**
- Server Version: Paper 1.17 #74
- Plugin Version: 3.40

**Comment by BroEdits** [comment]
Hi, it would help if you listed the ones that do not work if you remember. During time of this issue being open GC has reworked some and most work. If the case is that this issue is no longer relevant please close it if you can.
