### ISSUE TITLE
Not working on Paper 1.21 #124

### ISSUE THREAD

**Issue by SliqSuicide** [GC-spigot/battle-pass#572]
### Describe the bug

It's not starting at 1.21 Paper #124

### How to reproduce

Re-Installed Plugin but still doesnt work

### Screenshots / Videos

https://mclo.gs/rlShUC4

### Server Log

https://mclo.gs/rlShUC4

**Comment by KPGTB** [comment]
Hey! Fix will be available in the next update (probably in the next few hours).
