### ISSUE TITLE
Farming quests not working?

### ISSUE THREAD

**Issue by AdamDAuria** [GC-spigot/battle-pass#577]
### Describe the bug

Using the latest version of the plugin 
adding in the Harvesting Crops quests using block-break quest
using the latest version of the plugin

### How to reproduce

Use Example #1 in the wiki 

quests:
  1:
    name: 'Daily - Farmer' 
    type: block-break 
    variable: POTATOES:7
    required-progress: 10 
    points: 10 
    item: 
      material: diamond_pickaxe:0
      amount: 1
      name: '&eFarmer'
      lore:
        - '&7Mine &e10 Potatoes'
        - ''
        - '&7Progress &e%total_progress%&7/&e%required_progress%'
        -

**Comment by KPGTB** [comment]
Hey! Variables systems have been recently updated, and it seems that some topics on wiki haven't been updated yet.

To create a quest to harvest potatoes, please use one of these examples:

1)
```yaml
type: harvest-croops
variable: potatoes
```

2)
```yaml
type: block-break
variable: potatoes{age: 7}
```

**Comment by AdamDAuria** [comment]
i don't think this is working
