### ISSUE TITLE
Add support for VotifierPlus

### ISSUE THREAD

**Issue by ISN-Bulma** [GC-spigot/battle-pass#579]
### Describe the bug

When voting for the server the vote goes through and everything works, but for the battlepass the player doesnt recieve any progress.

This is the config
'8':
    name: Week 1 - Voter
    type: votifier_vote
    variable: none
    required-progress: 10
    points: 10
    item:
      material: written_book:0
      name: '&6&lVoter'
      lore:
      - '&7Vote for the server 10 times'
      - ''
      - '%progress_bar% &7(&a%percentage_progress%&7)'

### How to reproduce

using the config above as a weekly quest and try voting. No progress gets aquired

### Screenshots / Videos

https://gyazo.com/45a83092c10f270a01c594bd8f02e089

**Comment by KPGTB** [comment]
Hey! Can you send me server logs?

**Comment by KPGTB** [comment]
Also do you use Votifier, NuVotifier or other fork of it?

**Comment by ISN-Bulma** [comment]
> Also do you use Votifier, NuVotifier or other fork of it?

We use VotifierPlus, is that okay? We're using VotingPlugin as our sideplugin.

**Comment by KPGTB** [comment]
Hey! I added support for VotifierPlus. It's a fork of Votifier, but devs of that plugin changed its name in `plugin.yml` (they shouldn't do it) and it caused your problem. BattlePass couldn't detect Votifier, so it didn't register action. This integration will be available in one of the next updates.

**Comment by ISN-Bulma** [comment]
Thank you for the help!
