### ISSUE TITLE
[Request] Extended compatibility needed

### ISSUE THREAD

**Issue by GazpaNova** [GC-spigot/battle-pass#58]
I need to set up daily/weekly missions that allow me to kill multiple mythicmobs of different types. Say, I have multiple bandit mobs (for different varieties) and I need it so you can kill any of the types and it will count towards battlepass completion
There are two ways in which this could be easily achieved
first method would be to support multiple types of mythicmobs as variables (it currently doesn't work) like MythicMob1, MythicMob2.... MythicMobN

The second method would be to add support for mythicmobs factions (a function that's incorporated into the base plugin, isn't an addon or anything)
and that would have you enable the quest type ''mythicmobs_kill_faction''
and the faction name as a variable

**Comment by iqtesterr** [comment]
Any update of this? It stop me from buying the plugin.
