### ISSUE TITLE
Mcmmo Track total levels?

### ISSUE THREAD

**Issue by ISN-Bulma** [GC-spigot/battle-pass#583]
### Describe the feature

For mcmmo, is it possible to have a progress system that instead track whenever the player levels up, it tracks the players total level of each skill?
So it track your progress to getting to level 100.

name: 'Week 2 - Evasive'
    type: mcmmo_level_skill_total
    variable: acrobatics:0
    required-progress: 100
    points: 10
    item:
      material: rabbit_foot:0
      name: '&6&lEvasive'
      lore:
        - '&7Get to level 100 in acrobatics skill'
        - ''
        - '&7Progress &e%total_progress%&7/&e%required_progress%'

**Comment by KPGTB** [comment]
Hey! Will be added soon
