### ISSUE TITLE
Lands(plugin) error.

### ISSUE THREAD

**Issue by barannnnnns** [GC-spigot/battle-pass#584]
### Describe the bug

I added the lands create task and received this error while doing this task.

https://mclo.gs/ZN95CCo

Config:

`'15': 
    name: 'Arazi Oluştur - &7(1.Hafta)'
    type: lands_create
    variable: none 
    required-progress: 1 
    points: 10 
    item: 
      material: GRASS_BLOCK:0
      amount: 1
      name: '&fGörev: &7Arazi Oluştur'
      lore:
      - '&7/arazi oluştur komutunu kullan.'
      - ''
      - '%progress_bar% &7(&a%percentage_progress%&7)'`

### How to reproduce

Up.

### Server Log

https://mclo.gs/ZN95CCo

**Comment by KPGTB** [comment]
Hey! Fix will be available in one of the next updates
