### ISSUE TITLE
The battlepass.use permission also determines whether you can perform quests or not.

### ISSUE THREAD

**Issue by barannnnnns** [GC-spigot/battle-pass#587]
### Describe the feature

I want the "battlepass.use" permission to also be tied to missions.

Accordingly, players with "battlepass.use" permission can complete the quests. 
If the "battlepass.use" permission is set to false, I want it to not be able to perform quests.

The main reason for this is that I make players use BattlePass after a certain process. 
For example, you can use battlepass after playing for 10 minutes (a random example) I need to block BattlePass until this time.

Currently, battlepass.use permission only blocks commands, not quests. This doesn't make much sense to me. I used translation while writing this. Please feel free to edit.

**Comment by KPGTB** [comment]
Hey! It seems that `battlepass.use` permission is only for commands. If you want to block certain players from progressing quest, just set `enable-ban-permission` to `true` in `settings.yml` and then add permission `battlepass.block` for these players. This permission is more important that `.use`, so if someone has this permission, he won't be able to progress questt **AND** open battlepass menu
