### ISSUE TITLE
Optimizing QuestMove tracker

### ISSUE THREAD

**Issue by NaTorOG** [GC-spigot/battle-pass#592]
### Describe the bug

![image](https://github.com/user-attachments/assets/941dadf4-2426-4000-9029-2b4c36539ea2)

### How to reproduce

//

### Screenshots / Videos

//

**Comment by NaTorOG** [comment]
I don't know how you handle it, but a simple and quick idea would be a single thread executor where you submit the calculation stage process (which is the method most consuming)

**Comment by KPGTB** [comment]
Hey! I improved performance of movement actions (and some other). It will be available in one of the next updates
