### ISSUE TITLE
Could not pass event PlayerItemConsumeEvent to BattlePass v4.6.1

### ISSUE THREAD

**Issue by Z3r0xh** [GC-spigot/battle-pass#593]
### Describe the bug

https://mclo.gs/KIGm1A3

### How to reproduce

I don't know

### Screenshots / Videos

https://mclo.gs/KIGm1A3

**Comment by Celipa** [comment]
Yeah my consume quests havent been working either

**Comment by KPGTB** [comment]
Hey! There was probably sync error when building BattlePass 4.6.11 and 4.6.12. We'll fix it asap. Until update, please use BattlePass 4.6.10 which should work

**Comment by KPGTB** [comment]
Fixed in 4.6.13
