### ISSUE TITLE
Very high usage in timings report

### ISSUE THREAD

**Issue by Vehzx** [GC-spigot/battle-pass#595]
### Describe the bug

As seen in these timings, BattlePass and AdvancedJobs use significantly more % than all my other plugins combined, but it's only the KillMobQuest that's causing it. I assume this is something to do with how the plugin tracks mob kills.

I have made a seperate bug report on github for BattlePass also.

https://timings.aikar.co/dev/?id=aab4da66acb4486189e521cfc466b3e3

Incase you need a reference to the discord ticket I opened, it's ticket #bp-sirjben-1831

### How to reproduce

I use default battlepass config, start a timings report with

/timings on

leave for 10min

/timings report

### Screenshots / Videos

![image](https://github.com/user-attachments/assets/ed1d3982-a009-4583-91bf-a62bc25032c2)

### Server Log

https://mcpaste.io/d4037d9ff311aaaa

**Comment by KPGTB** [comment]
Hey! Please use latest version of BattlePass (4.6.13). Problem should be solved
