### ISSUE TITLE
Bad performance of interact action

### ISSUE THREAD

**Issue by GG-MD** [GC-spigot/battle-pass#597]
### Describe the bug

```
[19:20:09 INFO]: Current Purpur Version: 1.21.1-2299-5c0d2f7 (MC: 1.21.1)*
* You are 1 version(s) behind
Download the new version at: https://purpurmc.org/downloads
Previous: 1.21.1-2298-a61db94 (MC: 1.21.1)
[19:20:10 INFO]: theZe3 issued server command: /tpa ra
 ver BattlePass
[19:20:11 INFO]: BattlePass version 4.6.13
```

### How to reproduce

-

### Screenshots / Videos

<img width="981" alt="image" src="https://github.com/user-attachments/assets/29a9abd3-fbee-4dfc-8456-ad6700559f89">

[spark](https://spark.lucko.me/Mu1wGYAHot)

### Server Log

completely clean.

**Comment by KPGTB** [comment]
Hey! I improved performance of interact action. It will be available in one of the next updates

**Comment by GG-MD** [comment]
> Hey! I improved performance of interact action. It will be available in one of the next updates

yay
