### ISSUE TITLE
bug battle pass ui

### ISSUE THREAD

**Issue by ICBEST01** [GC-spigot/battle-pass#598]
### Describe the bug

there are gold nuggets present on the battle pass ui
![FML_early_loading_progress_2024-09-01_17_17_38](https://github.com/user-attachments/assets/89a6e67a-475f-4526-935e-6d76cbb97c96)

### How to reproduce

Je ne sais pas du tout

### Screenshots / Videos

![FML_early_loading_progress_2024-09-01_17_17_38](https://github.com/user-attachments/assets/83427353-1ffc-476c-84b1-8109a7b18500)

**Comment by KPGTB** [comment]
Closed due to no response
