### ISSUE TITLE
Leaderboards lags 2

### ISSUE THREAD

**Issue by bobhenl** [GC-spigot/battle-pass#601]
### Describe the bug

Hello, it's continue to this issue: https://github.com/GC-spigot/battle-pass/issues/591

There are still regualr TPS drops to like 9 tps...
https://spark.lucko.me/mYqDoi9UPc as you see battlepass is normally on 0% and then it goes to 9%

### How to reproduce

enable leaderboards

**Comment by KPGTB** [comment]
Hey! According to your previous issue, it seems that you disabled leaderboard cache. Did you enable it again after updating plugin? If yes, please send me your user cache - it can be really helpful to fix this issue.

User cache location:
- `plugins/BattlePass/users` folder when you use JSON storage method
- `battlepass-users` table when you use MySQL storage method

If you don't want to send it here, you can send me it on discord `kpgtb`

**Comment by bobhenl** [comment]
yeah the caching was enabled, I had to disable it again

Sent you message on Discord, username: Renzotom

**Comment by KPGTB** [comment]
Hey! I made some changes in leaderboard controller. Please wait for the next update and check if it works better (with caching enabled)
