### ISSUE TITLE
Cant use /battlepass comand, getting errors

### ISSUE THREAD

**Issue by SirvydasS** [GC-spigot/battle-pass#604]
### Describe the bug

Plugin stop working after purpur and battlepass updates.

### How to reproduce

Use latest version of purpur and battlepass.

Current Purpur Version: 1.21.1-2309-be61a07 (MC: 1.21.1)
BattlePass version: 4.6.19

### Server Log

https://mcpaste.io/37e80a73f644bf3f

**Comment by KPGTB** [comment]
Hey! Fix will be available in the next update. It seems that Mojang made some changes in skull's code in internal build which caused compatibility issues between spigot/paper/purpur builds
