### ISSUE TITLE
BrewingQuest.handleItem(): Cannot invoke "org.bukkit.potion.PotionType.name()" because "<local9>" is null

### ISSUE THREAD

**Issue by BigScary** [GC-spigot/battle-pass#606]
### Describe the bug

Getting lots of spam in logs similar to below. Assume you can cure it with some simple null checks.

Could not pass event InventoryClickEvent to BattlePass v4.6.7
java.lang.NullPointerException: Cannot invoke "org.bukkit.potion.PotionType.name()" because "<local9>" is null
	at BattlePass.jar/net.advancedplugins.bp.impl.actions.internal.BrewingQuest.handleItem(BrewingQuest.java:66) ~[BattlePass.jar:?]

Thank you VERY much for not requiring me to upload logs, run the version command, and update to the latest version of the plugin just to file a simple report. <3

### How to reproduce

Unclear. I just see lots of this in my logs. Probably some custom potions from /give command, or some other plugin don't have all the data you assume a potion will have.

**Comment by KPGTB** [comment]
Hey! Please update plugin to the latest version 😉This problem should be already fixed. After update, please let me know if everything works fine.

**Comment by KPGTB** [comment]
Closed due to no response. As I said, update should help
