### ISSUE TITLE
Update the Wiki

### ISSUE THREAD

**Issue by BorisOZ** [GC-spigot/battle-pass#607]
### Describe the feature

There are so many things that are out of date, missing or simply broken. Can you please take some time to go through the whole wiki and update it.

For example under commands, some of those commands no longer exist and new ones have been made. 
Under quests/actions there are broken and missing links and missing details for quest types. 
Under permissions, it says `Set the premium pass permission in the premium.yml as so:` and then doesn't actually have an example.

**Comment by SirJben** [comment]
Will work on it.

**Comment by KPGTB** [comment]
Updated most part of BattlePass wiki
