### ISSUE TITLE
[Issue] Error that disables the plugin

### ISSUE THREAD

**Issue by koyere** [GC-spigot/battle-pass#66]
**Describe the bug**
An error that happens in a new installation, I have nothing configured, it starts from scratch and gives the error

**To Reproduce**
Put a new installation with Airplane 1.17.1 (# 48)

**Screenshots / Video**
https://pastebin.com/tyB1WnK6

**Server Information (please complete the following information):**
- Server Version: Airplane version git-Airplane-48 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 15822af on HEAD)
- Plugin Version: BattlePass v3.46

**Comment by GC-spigot** [comment]
Fixed
