### ISSUE TITLE
Enchant Type + Plants block break error

### ISSUE THREAD

**Issue by nivcoo** [GC-spigot/battle-pass#75]
**Describe the bug**

ENCHANT:
Hello i've tried lot of things for enchant type and it doesn't works. https://pics.revolis.fr/2021-08/03/22-46_1Pmz.png https://pics.revolis.fr/2021-08/03/22-46_xtL3.png https://pics.revolis.fr/2021-08/03/22-46_qPhl.png

PLANTS:
Hello, the ID for plants not works, i've this config https://pics.revolis.fr/2021-08/03/22-58_D2xr.png (Same issue with all plants which have the same item and drops). When i place the plant and wait the growth it doesn't works but if //set nether_warts:3 it works so i think the plugin catch for the protection the block place but with wrong id/data or something like that. I think it's that because i've do another test : I place plant and //replace with world edit nether_warts: and it doesn't works also.

**To Reproduce**
ENCHANT:
Try the enchant type with iron shovel

PLANTS:
Place plante, wait, break it when it is full growth. Try with //set and break it.

**Screenshots / Video**
If applicable, add screenshots or videos to help explain/ show your problem.

**Server Information (please complete the following information):**
- Server Version: Kspigot 1.12.2
- Plugin Version: 3.49

**Comment by nivcoo** [comment]
Any news ?

**Comment by GC-spigot** [comment]
Can you post the error as well?

**Comment by nivcoo** [comment]
I havent error just not works

**Comment by nivcoo** [comment]
Any news ?

**Comment by nivcoo** [comment]
It not works also with mycelium maybe block break protection isn't correct and save the wrong block so the block break not works also

**Comment by nivcoo** [comment]
Any news ?

**Comment by nivcoo** [comment]
Any news ?

**Comment by nivcoo** [comment]
Any news ?

**Comment by GC-spigot** [comment]
https://battlepass.advancedplugins.net/useful/harvesting-crops
