### ISSUE TITLE
[Issue] About Block-Break

### ISSUE THREAD

**Issue by Oxygen0621** [GC-spigot/battle-pass#77]
**Describe the bug**
I create a quest to mine Ancient Debris
can't place then mine is normal that a great setting
but if i _**place**_ a _**Ancients Debris**_ then **use Piston** push that and break
that will count to my quest

**Server Information (please complete the following information):**
- Server Version: [paper-1.16.5-786 1.16.5]
- Plugin Version: [BattlePass 3.50]

**Comment by BroEdits** [comment]
Hi, So the plugin registers blocks naturally place. Or you can place them with worldedit and it will count. Also you can place with your hand and do `/bpa reload` It will then count :)
