### ISSUE TITLE
[Issue] Block-break not working

### ISSUE THREAD

**Issue by OverBrave** [GC-spigot/battle-pass#78]
**Describe the bug**
block-break quest type not working in daily-quests. I tried all materials but not any block working in this quest type.

**Server Information (please complete the following information):**
- Server Version: ![image](https://user-images.githubusercontent.com/47111280/129461636-d8955be7-ef0b-46ec-9b8f-a5714608a70f.png)
- Plugin Version: 3.51

**Comment by nivcoo** [comment]
I've almost the same issue

**Comment by BroEdits** [comment]
Hi, Please can you join our Discord, I will be able to assist you
`https://discord.com/invite/tm9QzqvmQA`
