### ISSUE TITLE
Smelt Quest

### ISSUE THREAD

**Issue by RinNiko** [GC-spigot/battle-pass#8]
**Describe the bug**
Quest not count exactly 
for example : I smelt 10 iron ore but just receive 1 point of that quest

**To Reproduce**
Example Daily Quest : 
  24:
    name: 'Hằng ngày - Thợ rèn'
    type: smelt
    variable: iron_ingot:0
    required-progress: 100
    points: 1
    item:
      material: furnace:0
      name: '&7[&a&lNhiệm vụ&7] &a&lNung sắt'
      lore:
        - ''
        - '&c&lYÊU CẦU:'
        - '&7* Nung &6100 &fquặng sắt'
        - ''
        - '&c&lTIẾN ĐỘ:'
        - '&7* &a%total_progress%&7/&a%required_progress%'
        - ''
        - '&c&lPHẦN THƯỞNG:'
        - '&7[&e+&7] &a&l1 XP'
        - ''

**Screenshots / Video**
Hmm i don't think i need this u guys can test my quest above

**Server Information (please complete the following information):**
- Server Version: Paper 1.15.2
- Plugin Version: 3.13

**Comment by GC-spigot** [comment]
Fixed!
