### ISSUE TITLE
[Request] Add Integration of Mythic Plugin (MMOItem, MMOCore)

### ISSUE THREAD

**Issue by RookieAND** [GC-spigot/battle-pass#80]
Recently I try to use BattlePass plugin and I'm shocked of its content. (It's amazing!)

But I can't find the way to add some bridge between BattlePass & MythicPlugin (MMOItem, MMOCore)

So If you have some time and have a plan to add integration. I'm truly glad.

**Comment by OpticFusion1** [comment]
There is not enough information here for us to be able to do anything. Please re-make the issue using the new "Quest Type" issue template.
