### ISSUE TITLE
Premium Progress Track slots do not auto fill

### ISSUE THREAD

**Issue by VINRED5** [GC-spigot/battle-pass#82]
Minecraft version: 1.17.1
Plugin version: 3.51
Premium Progress Track slots do not auto fill with a Glass Pane, When there is a slot empty.
![battlepass_bug](https://user-images.githubusercontent.com/74217586/130245529-9166bc9e-7702-4863-9c57-ffdbc8468e89.png)
BroEdits looked at my files and couldn't fix it
My filse -  (plugins/BattlePass)

**Comment by GC-spigot** [comment]
Fixed
