### ISSUE TITLE
[Issue] no menu

### ISSUE THREAD

**Issue by NezihEge** [GC-spigot/battle-pass#85]
hai
I'm setting up daily quests. Even when I type the command "/bpa daily quest ids", the tasks are listed, but the menu in /bp > quest > daily quest is very empty. how can i solve it?
![image](https://user-images.githubusercontent.com/80573002/131486671-69d874a8-d5ad-4076-a11b-a3e57dce12f9.png)

this is the "daily quests" part menu but it's empty

![image](https://user-images.githubusercontent.com/80573002/131486716-9235496d-81b6-498e-a2f1-f8481b97dc54.png)
this is ids:

**Comment by NezihEge** [comment]
I guess the "daily-quests" part in the menus folder is not working.

**Comment by GC-spigot** [comment]
Fixed
