### ISSUE TITLE
[Request] Add EliteBosses in Quests (Maybe all Elite plugins)

### ISSUE THREAD

**Issue by Drevya** [GC-spigot/battle-pass#86]
The EliteBosses plugin is one that has been on the rise recently. I think good things will come out if it is added to Quest. Additionally, we use EliteBosses in the Dungeon system. It would be great to integrate it with BattlePass.

**Comment by Radio-active69** [comment]
We have the same suggestion. There is a another plugin like mythic mobs called elitemobs and I want to use that elitemobs as quest for the battlepass. Hope the developer would consider.
