### ISSUE TITLE
[Issue]

### ISSUE THREAD

**Issue by yellow-pillow** [GC-spigot/battle-pass#87]
**Describe the bug**

in general, I have a problem with enchantment tasks, I think that this is a bug, because I have already contacted technical support for correct examples of the task config and, following their example, I made my tasks that work BUT only half

there is a task with the enchant-all check, but it only works on the anvil, although it is stated that it should check enchantments from both the anvil and the enchantment table, I recorded a whole video with this bug and tried to show it as briefly as possible

and at the end, as in the video, I will ask you to make a wikipedia with examples so that people do not have to contact technical support for examples
(maybe I'm stupid myself, but it's better that Wikipedia could convey information to everyone, even the most incomprehensible, than to go towards complication and soon no one will understand Wikipedia)

file of my tasks/quests https://drive.google.com/file/d/1semwg2jWNL3wiiM1Y-yQMsRhRec8rhnR/view?usp=sharing

**To Reproduce**
idk

**Screenshots / Video**
video https://drive.google.com/file/d/17GPQufnPpKRzgCHYywMORitVO1uoArwW/view?usp=sharing

**Server Information (please complete the following information):**
- Server Version: [e.g. PaperSpigot-123 1.8.8]
- Plugin Version: [e.g. 6.7.8]

**Comment by GC-spigot** [comment]
Fixed
