### ISSUE TITLE
[Issue]

### ISSUE THREAD

**Issue by Lizardz** [GC-spigot/battle-pass#9]
Whenever server is stopped, this error occurs: https://paste.helpch.at/aqudikezaq.css

Also in /passes/premium.yml

"doesnt-have-pass" lore/item does not work. For free players it still shows PREMIUM's version of "locked-tier-item" and  "unlocked-tier-item" And not JUST "doesnt-have-pass" section. 

When trying to reload plugin: https://i.imgur.com/rqVhWxI.png

**Comment by GC-spigot** [comment]
Fixed!
