### ISSUE TITLE
[Issue] Implementing & loading error

### ISSUE THREAD

**Issue by DrShell-HCFrench** [GC-spigot/battle-pass#93]
**Describe the bug**
I just downloaded your api and implemented it with MAVEN. I followed the documentation to create new quest type.
But when the server start it send me a message error.

**To Reproduce**
Just reproduce the documentation.

**Screenshots / Video**
https://gyazo.com/78abc02585c1cf32d242fa61c9ae582c

**Server Information (please complete the following information):**
- Server Version: ImanitySpigot (a 1.8.8 Tacospigot fork)
- Plugin Version: battle-pass-3.59
- API Version : LATEST

**Comment by GC-spigot** [comment]
Add battlepass to your server
