### ISSUE TITLE
Broken Harvesting?

### ISSUE THREAD

**Issue by Moosebobby** [GC-spigot/battle-pass#94]
Whenever my players attempt to do quests for harvesting crops (in this case potatoes) it doesnt count any as harvested despite being harvested.  
https://gyazo.com/83f8d5100029784ee4fd236493f811bf

  10:
    name: 'Week 1 - Farmer'
    type: break-block
    variable: potato:0
    required-progress: 640
    points: 500
    item:
      material: potato:0
      name: '&eFarm'
      lore:
        - '&7Harvest &e640 &7potatoes'
        - ''
        - '&7Progress &e%total_progress%&7/&e%required_progress%'

**Comment by GC-spigot** [comment]
It's gonna be `POTATOES:7` on 1.16+. `POTATOES` is the block type and `7` is the state of them being fully grown.
