### ISSUE TITLE
[Issue] Own implementation of quests are not working after refreshing

### ISSUE THREAD

**Issue by JoseArquesGomez** [GC-spigot/battle-pass#95]
**Describe the bug**
I have my own quests registered in my minigame plugin. Every time the plugin refreshes the daily or the weekly quests, if the quests came from my plugin they don't work until the server restarts. Reload battlepass doesn't fix this problem.

Example: I have implemented a loot chest in match quest. If daily quests refresh, appear this mission but they can't progress it. If server restarts, it works again. The same occurs with the unlocking of weekly quests.

**To Reproduce**
Registering quest:
`	public void loadQuests() {
		QuestRegistry questRegistry = BattlePlugin.getApi().getQuestRegistry();
		questRegistry.quest(instance -> new LootChestQuest(instance));
	}`

QuestExecutor class:
`public class LootChestQuest extends QuestExecutor implements Listener {

	@SuppressWarnings("deprecation")
	public LootChestQuest(BattlePlugin plugin) {
		super(plugin);
	}

	@SuppressWarnings("deprecation")
	@EventHandler (ignoreCancelled = true)
	public void onLootChest(PlayerLootChestEvent e) {
		String mode = e.getMatch().getMode().getName();
        super.execute(PrimeAPI.getApi().getCommandPrefix() + "_loot_chest", e.getPlayer(), result -> {
            return result.root(mode);
        }, replacer -> replacer.set("mode", mode));
	}
}`

**Server Information (please complete the following information):**
- Server Version: [e.g. TacoSpigot - 1.8.8]
- Plugin Version: [e.g. 3.59]

**Comment by GC-spigot** [comment]
Should be resolved
